### ISSUE TITLE
[CoreWM] Widgets support

### ISSUE THREAD

**Issue by rubengc** [os-js/OS.js#122]
Add a desktop widgets support from apps installed

Something like Android/iOS widgets, where an app can contains some widgets with different sizes support

- [ ] Create Widget class
- [ ] Create Widget configuration(s)
- [ ] Add configuraition to Settings
- [ ] Create *Clock* widget as example

**Comment by andersevenrud** [comment]
This was [also] suggested in #100 and moved to #49. Do you have any specific types of widgets in thought ?

**Comment by rubengc** [comment]
An interesting widget to test this can be a clock for some reasons:
Needs to get update every min (or every second)
Has different sizes
Has different date formats
Has different styles (normal or digital)

In the future, sure that some apps will have a really useful widgets (the weather, a system usage visor, a RSS feed from your favourite page, a task pending visor, etc)

**Comment by andersevenrud** [comment]
I think it would be better to make the widgets a "package" just like how the applications run. This way it's super easy to maintain them with install/uninstall. Also, then you can decide for yourself where to put the files. You can basically have some cake, and eat it too :) Sounds reasonable ?

A clock widget would be a nice place to start. Should be pretty stratight forward and easy. Thanks!

**Comment by rubengc** [comment]
So the user now will see in the store: apps, widgets and themes right?
If someone publish an app, will be interesting add widgets to this installation (asking to the user if he wants to install them too)
For example, a twitter app, would want to include a widget with latest tweets
In the store, the developer can mark what widgets are included in this app

**Comment by andersevenrud** [comment]
This can be a store spesific feature. In the manifest for a store item there could be some entries that define an association. That way it works more or less like you described :)

**Comment by MrSchism** [comment]
I think a system resource panel would be single handedly the best, especially if you can see usage per user in a separate tab

Simple, like Virtual Machine Manager's interface... but instead of VMs, show users.

![](http://virt-manager.org/wp-content/uploads/2013/04/virt-manager-vm-list.png)

**Comment by andersevenrud** [comment]
@MrSchism 

> Simple, like Virtual Machine Manager's interface... but instead of VMs, show users.

Which users ?

**Comment by MrSchism** [comment]
Any 'user' accounts on a system.  Like field 2 of `top`.

OR alternatively, if used in a multi-user mode.

**Comment by andersevenrud** [comment]
@MrSchism But do you mean in OS.js or the underlying system ?

**Comment by MrSchism** [comment]
In the first instance, the underlying system.

In the second, OS.js.  It'd ideally be set for only an elevated user to see.

**Comment by andersevenrud** [comment]
Yeah, because an OS.js user does not run on the underlying system... so getting any statistics for that would be pretty limited (only what the webserver has). If you had a handler that actually used PAM (which I have tested successfully) you can get some stats if a user actually executes some background tasks etc, but again limited.

But yes. The original intent of OS.js was to manage the underlying system. I was using it for virtual machine setups and webservers etc. Had a few D3.js charts going etc to see realtime traffic etc. Maybe I should redo these for v2 ?! ;)

**Comment by MrSchism** [comment]
It wouldn't be a bad idea.  The ability for an admin/mod/op to monitor is always good, in my book.

**Comment by andersevenrud** [comment]
@MrSchism I could basically just include a bunch of wrappers and attach them to the API for cases just like this. Sort of like munin (but not that awful custom scripting stuff.... just pure js)

**Comment by MrSchism** [comment]
That'd be awesome.  I was thinking something between the monitor I linked above and [conky][1]

[1]: http://conky.sourceforge.net/screenshots.html

**Comment by andersevenrud** [comment]
@MrSchism Yeah. That'd be nice :)

**Comment by MrSchism** [comment]
I say between the two because while conky is nice, it might be offputting to casual and new moderators/administrators.

**Comment by eraffaelli** [comment]
Totally need this ^^
I'm working on a Weather app (well, more a playground for now but) and it would be nice to have a "favorite" city widget.

**Comment by andersevenrud** [comment]
I am closing this issue in favour of #329.

Just FYI: I've started on an implementation on this that uses a `<canvas>` based system (so everything scales correctly). So it will not be long until you finally can do this -- but for progress, se #329 :)

**Comment by andersevenrud** [comment]
You can now follow the progress in #479 :)
