### ISSUE TITLE
[Applications] IDE/Interface Designer

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#134]
Issue for official OS.js IDE and Interface Designer.

This is developer parallel to the APIs, so suggesions are appreciated!

**REPOSITORY:** https://github.com/os-js/OS.js-IDE

![Screenshot](http://i.imgur.com/hjOwbbP.jpg)

* [x] Simple project loading
* [x] Window Rendering
* [x] GUI Element toolbar
* [x] Proper project loading and sessions
* [x] Project saving
* [x] Multiple window support
* [x] Adding elements
* [x] Removing elements
* [x] Parameter viewing
* [x] Parameter setting
* [x] File Browser
* [x] Project File Format

*The TODO items are taken straight from repo and might not be synced*

**Comment by andersevenrud** [comment]
@junland :)

**Comment by junland** [comment]
:+1: Nice. Good job! @andersevenrud

**Comment by andersevenrud** [comment]
Blocked by #136

**Comment by andersevenrud** [comment]
I'm closing this for now. Will reopen after gui-ng is finished

**Comment by ComputeLinux** [comment]
GUI-NG is finshed.

**Comment by andersevenrud** [comment]
But I still don't have enough feedback to actaually call it finished :(

**Comment by andersevenrud** [comment]
@ComputeLinux I was just about to look into this... and it seems I have *deleted* what I made earlier and there is no record of it on github :( So I have to start over... but not to worry, *I'm on the case* :)

**Comment by andersevenrud** [comment]
@ComputeLinux I've started on this again and this time it will be in it's own repo: https://github.com/andersevenrud/OS.js-v2-IDE So follow the progress there :)

**Comment by andersevenrud** [comment]
@ComputeLinux I will now re-open this issue. I have made quite some progress this weekend :)

**Comment by andersevenrud** [comment]
I am closing this issue now because there is a working version in https://github.com/os-js/OS.js-development that you can now use. It's not finished, but you can design your UI with it :)

**Comment by andersevenrud** [comment]
For anyone interested, here is a demo: https://www.youtube.com/watch?v=qPhBpkbeZBU
