### ISSUE TITLE
[Applications] Shell and CLI APIs

### ISSUE THREAD

**Issue by fazo96** [os-js/OS.js#182]
Hi! Nice project :+1: 

A cool thing I thought would be the ability to run most node tools **on the client**. This can be done by having a _terminal_ app and a _shell_ running inside it. Then, when executing a program (which would be javascript) the shell injects some stuff into the global env of the executed script, such as:
- the _require_ function which works like node's _require_
- an implementation of the standard node API such as `fs` and `http` (of course not everything is possible but most of the stuff actually is and implementations for the browser already exsit)

This would allow most node CLIs to actually run in the browser and the ability to have a useful, powerful shell in the OS for scripting.

**Comment by andersevenrud** [comment]
I have a Terminal application here https://github.com/andersevenrud/OS.js-v2-extras that works fairly well :)

> the require function which works like node's require

This could by simply loading requirejs, couldnt it ?

> an implementation of the standard node API such as fs and http (of course not everything is possible but most of the stuff actually is and implementations for the browser already exsit)

OS.js already have a filesystem abstraction layer that works very similar to nodes.

I am planning to add more CLI tools and such (which is in progress on another branch), so stay tuned

**Comment by fazo96** [comment]
Wow cool!

What I meant is writing part of the node standard library using your file system abstraction, so that node modules and applications using `require('fs')`, `require('http')` and similar __will work in the browser__. That would allow almost all existing CLI tools written in javascript to work in OS.js :+1: My point was allowing a command line environment with a full shell similar to bash and applications and tools written in javascript to work in the browser.

**Comment by andersevenrud** [comment]
So, like a JavaScript REPL with console output ? That could be done!

**Comment by nickdeis** [comment]
You could just use the browsers dev tools to start out. I often find myself using ctrl+alt+i in Atom and playing around with node modules in the dev tools.

**Comment by andersevenrud** [comment]
ping @marktopper -- just to remind myself

**Comment by andersevenrud** [comment]
I'm closing this issue and moving it to another repository; https://github.com/os-js/OS.js-development
