### ISSUE TITLE
[Compability] 'Script error'

### ISSUE THREAD

**Issue by joecracko** [os-js/OS.js#185]
**Update from @andersevenrud**

~~This only happens on demo server, so it has got to be a network/connectivity or external resource issue. So far it has not mattered which platform, browser or device it has been tested on. 7 reports so far spanning almost every possible configuration. I am not able to replicate this myself (at first I thought it was adblock, but I not on my side).~~

Possible causes:

- ~~Google Analytics API fails to load~~
- ~~Google AdSense API fails to load~~
- ~~A WebKit feature seizes and produces this error (like automatic translation. prevension has been implemented)~~
- **Multi-touch handling fails**

**Update, again**

~~It seems that the commit has fixed this problem. No more reports have been made -- and considering the frequenzy they came in at and now, nothing; tells the story.~~

*Leaving it open for at least one more week*

**Another update**

~~I have been able to trigger this in IE (but not reproducable) and on multi-touch devices (simply try to use native zoom out gesture)~~

**Yet another update**

This seems to be triggered by multi-touch events! I'm waiting for an Android Tablet so I can debug this. iPads need XCode on OSX running, and there's no way in hell I want to use my old MacBook Pro for that :P

---

An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```

Replication steps:
1. Navigate to http://os.js.org/
2. Click "Try the Demo" (http://osjsv2.0o.no/)

Using Google Chrome version 47.0.2526.106
Using Windows 8.1

Work-around: 
Simply close the error message and the application seems to work fine.

**Comment by andersevenrud** [comment]
You land on http://osjsv2.0o.no/ , right ?

I have never seen this error before... What browser are you using ?

You might want to try again. Maybe the server was overloaded (I have a lot of traffic right now)

**Comment by joecracko** [comment]
Updated with browser and OS

**Comment by joecracko** [comment]
Updated with work-around. It's probably a non-critical issue.

**Comment by andersevenrud** [comment]
That is really strange. Right now I am on the same browser and OS!

Maybe it is a browser plugin misbehaving or something ? That's my guess at least. I will leave this issue open anyway

**Comment by andersevenrud** [comment]
@joecracko @mgmoody42 @	flinn2112 @warranlin @brianNnelson @dexterlabora @davidthewatson 

Could you try to clear your browser cache and retry the demo and see if you stil get this error message ? I might have found a fix for it, but not sure since I'm not able to replicate :)

**Comment by andersevenrud** [comment]
This has been solved in a recent commit. Turns out it was due to the touch input handler which is being worked on as we speak! :)

**Comment by andersevenrud** [comment]
For now, I've simply added a workaround for this (not showing error dialog on exception for this spesific case), because it is a vendor issue.

**NB** Demo server has not been updated yet, but will be by next week
