### ISSUE TITLE
[GoogleAPI] Two google accounts for Drive

### ISSUE THREAD

**Issue by mlopezgva** [os-js/OS.js#193]
Error inesperado, puede que sea un bug.

> Por favor, informa de esto si piensas que es un bug. Incluye una breve descripción sobre cómo se produjo el probleñam y si es posible, cómo reproducirlo. Gracias

```
window::onerror()
Filename: https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.es.iivQWRxF-l8.O/m=auth,client/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCOmvRFEt7LZm2SLvcjD0hRtZd-ZIw/t=zcms/cb=gapi.loaded_0
Line: 0:0
Message: Script error.
```

I was authorizing OS.js in my google account... but... I have a personal and a corporate (Google Apps) account. I granted access for both...

**Comment by andersevenrud** [comment]
Thanks you for reporting! :)

I will look into this

**Comment by andersevenrud** [comment]
I am closing this issue in favour of #40 -- any updates will be made there :)
