### ISSUE TITLE
[UX] Window positioning/gravity is not playing nice with browser zoom

### ISSUE THREAD

**Issue by colinbrislawn** [os-js/OS.js#240]
Update from @andersevenrud:

I just need to make a wrapper for the functions that make use of `this._dimension`

---

In the Welcome window that first appears when opening the demo, the red close button is blocked by the top menu, as shown here:

![screen shot 2016-01-03 at 10 53 00 pm](https://cloud.githubusercontent.com/assets/10355152/12084787/fc278c8a-b26c-11e5-94da-8a0ede836e94.png)

I find this happens when I launch OS.js with a high default zoom (150% scale in Chrome). It works fine at lower zoom levels and when I zoom-in after launch.

**Comment by andersevenrud** [comment]
Thanks for reporting!

I will fix this issue ASAP

**Comment by andersevenrud** [comment]
I am closing this issue in favour of #112. There's a lot of incoming updates for mobile UI and other scaled browsers, so it will all be done in the forementioned issue.

I will make a comment in this issue when this issue has been completely resolved :)

**Comment by andersevenrud** [comment]
It seems that the Chromium people solved this in the Chrome browser itself. Gravity now seems to behave normally! :)
