### ISSUE TITLE
[Misc] Creating an companion app for Windows 10

### ISSUE THREAD

**Issue by TRoskop** [os-js/OS.js#254]
Hello Guys,
I think a lot of people would like to try another OS apart from Windows. But they are probably to shy to try, and they don't known how to try it without damaging the machine. 

As your OS.js runs inside a normal Browser, I would suggest to introduce an "companion app" for Windows 10. This enables the users to test it and get the look&feel of linux-OSes in general.

If the user likes the OS, he can simply use this app also to download the most recent image of this OS or at least the setup: http://os.js.org/installer.exe

This App would rely on the demo server: http://osjsv2.0o.no/
Is this server strong enough to accept more users? 

If you would like, I can design/implement the Windows Universal App and publish it, too.

As I would use an embedded Browser, I can also add some "custom" APIs to Javascript, which you could use to stay in touch with the users using Toast Notifications, Messages on the tiles etc.

Tell me, if you like this idea.

~Thomas

**Comment by andersevenrud** [comment]
> As your OS.js runs inside a normal Browser, I would suggest to introduce an "companion app" for Windows 10. This enables the users to test it and get the look&feel of linux-OSes in general.

Not sure I understand what you mean by "companion app" still.

> If the user likes the OS, he can simply use this app also to download the most recent image of this OS or at least the setup: http://os.js.org/installer.exe

But, you are still booting into windows... making it something else entirely. 

Now, OS.js comes with a X11 launcher so you can use it as a full-blown operating system (running on top of Debian), but that involves installing a Linux distribution on to your computer.

> Is this server strong enough to accept more users?

Yes.

> If you would like, I can design/implement the Windows Universal App and publish it, too.

I provide a NW.js build which is a native executable. Is this sort of what you mean ?

https://www.dropbox.com/s/pj5zpim0mw62dci/win64.zip?dl=0

> As I would use an embedded Browser, I can also add some "custom" APIs to Javascript, which you could use to stay in touch with the users.

This is pretty much not doable if you run in a browser becasue of CORS. The only way to make a browser would be to have a proxy running in the background, or use something like NW.

**Comment by TRoskop** [comment]
I'm sorry that I was not able to explain my idea correctly.

My Idea is an app, which allows user to test and try you OS very easy.
If the app is in the Windows Store [https://www.microsoft.com/de-de/store/apps], more people can see it. And they can try it very simple: just pressing "install" and waiting a few seconds. Once loaded, the users starts the app and it shows tutorials, informations and of course the OS. 

The user can try the app and if he likes it, he can click one button to download the setup or any supported Debian-ISO for installing.
All in all it is like a big "demo" so normal users can try the OS. 

Javascript-API: My Idea about API is that you can inform the user when a new version is available or when something happened. Like an newsfeed.

If you are interested, I can give more details in a few days. Including Concept-Art etc.

**Comment by andersevenrud** [comment]
But I don't understand why :) Isn't it easier to just link to a site where OS.js runs with a specialized application with a tutorial or something that simply has links to the download page and such ?

> Javascript-API: My Idea about API is that you can inform the user when a new version is available or when something happened. Like an newsfeed.

Do you mean like a notification in OS.js (after you installed it) that tells you an update is avalable ?

If so, that could be useful. Not to sure about the same thing for newsfeed -- It could be an optional thing, sure, but not on by default. I'd be pissed off if I suddenly got notifications about news I did not really care about :p 

> If you are interested, I can give more details in a few days. Including Concept-Art etc.

Sure!

**Comment by TRoskop** [comment]
Of course, a link is very easy, but it always runs in a normal browser, which cuts you possibility down. But this app can offer a lot more features - for you as developer and for the consumer.

You known how the tiles on Win8/8.1/10 look like? If not, google it. You can use them to show new informations in an non-invasive way, it just looks like a small notifications. 

And the APIs can be extended in a bigger way. Using these APIs you can use almost everything the device has to offer, including storage, quering user-name and using the users music- or image-files. With a normal browser you can't do that, can you? 
Here is a *small* overview, what function the JS-API could unlock for you. https://msdn.microsoft.com/en-us/library/windows/apps/br211377.aspx

And the app would allow to have a good user experience regardless of the browser.

I'll bring some concept later, just for you to see what I mean. I think you'll like it, once you understand what I mean.
And I'm sorry, I'm from Germany so my English is probably not the best :smile:

**Comment by andersevenrud** [comment]
... I still don't understand what you mean. And by "APIs" are you talking about WinJS ?

To me it seems that the NW build is what you're looking for. It is a standalone version of OS.js that runs without a browser in a self-contained executable.

> And I'm sorry, I'm from Germany so my English is probably not the best :smile:

Well, I'm from Norway -- so probably not the best here either.

**Comment by TRoskop** [comment]
First, on a lot of devices normal apps cannot run anylonger, only windows apps are supported. Seconds, users trust store apps more as they know they cannot harm their computer. 

I'll explain the APIs later.

**Comment by NoNameProvided** [comment]
//Off
> And I'm sorry, I'm from Germany so my English is probably not the best :smile:

Never apologize because of your language, you speak it better than the how other speaks your language.

// Off 2
> Well, I'm from Norway

I like Norwegians, they are crazy :smile: So it's nice to meet you!

//On

>> As I would use an embedded Browser, I can also add some "custom" APIs to Javascript, which you could use to stay in touch with the users.

> This is pretty much not doable if you run in a browser becasue of CORS. The only way to make a browser would be to have a proxy running in the background, or use something like NW.

 >> Of course, a link is very easy, but it always runs in a normal browser, which cuts you possibility down. But this app can offer a lot more features - for you as developer and for the consumer.

He means that he could bridge some Universal App feature to the JS, so you can reach it when your app running in his universal app. This makes no sense to me, since almost everything is possible in the evergreen browsers what you can do in an universal app except accessing the file system of the device. (You have notifications, background workers, etc. in browsers too)

> And the app would allow to have a good user experience regardless of the browser.

Today browsers are evergreen, except IEs under IE10 but if someone still use IE10 then they are not the target audience for this project. 

> Seconds, users trust store apps more as they know they cannot harm their computer.

An app could do more harm than a webpage. :wink:

**Comment by NoNameProvided** [comment]
>First, on a lot of devices normal apps cannot run anylonger, only windows apps are supported. Seconds, users trust store apps more as they know they cannot harm their computer.

I don't know from where did you get that people trust universal apps more? Can you provide some source? 

I see your point (that a lot of windows 10 devices like phones cant run Win32 apps), but the idea what you are talking about is very hard to work with. Because if we make an app to give special features to the OS.js on WIndows then we should do it on the other first class citizen platforms like iOS, Android, Mac, Linux and this makes any change 5x more harder to implement. 

> Edit: And you UI will look nicer, because you will not have the big and ugly browser frame around you, just a normal window border.

Yes, as it's not visible in the NW.version either.

**Comment by TRoskop** [comment]
Hello, I'm back again.
Here are the "concept designs" I promised you.
![desktop-viewsplashscreen](https://cloud.githubusercontent.com/assets/13079737/12204483/bda2f820-b634-11e5-9aa3-02a445ba6f57.png)
![desktop-viewfirstruntutorial](https://cloud.githubusercontent.com/assets/13079737/12204531/03940c48-b635-11e5-8137-075cceb7f6b9.png)
![desktop-viewosself](https://cloud.githubusercontent.com/assets/13079737/12204482/bd8c17ae-b634-11e5-9133-53339154976a.png)
![desktop-viewossettings](https://cloud.githubusercontent.com/assets/13079737/12204484/bdaff098-b634-11e5-96f5-f56726ddc36e.png)


Moreover, I thought what to do with APIs.
I think I can be able to add APIs to the Javascript-Interface which allow your app to do some native stuff.
For example:
> OSjsAppRuntimeEngine.QueryAllUserPictures() 
might return you a list of the images in the users "Picture" folder. 
or:
> OSjsAppRuntimeEngine.ReadFile(filename) | OSjsAppRuntimeEngine.StartUpload(filename, targetUrl, callbackEventHandler)
enables you to read a complete file (like pictures, text files or videos)
[Note: These APIs are one for demonstrating, these are not the final ones, just to show what would be possible]

In these arts I've not included the live tiles or toast, but they should be well known :smile: 

I'm waiting for you feedback.

**Comment by andersevenrud** [comment]
> OSjsAppRuntimeEngine.ReadFile(filename)

You can do this in OS.js natively with NW

> OSjsAppRuntimeEngine.StartUpload(filename, targetUrl, callbackEventHandler)

Also this.

> OSjsAppRuntimeEngine.QueryAllUserPictures() 

You can also do this by using a filter to scandir() VFS API.


As for the screenshots it looks like you want a NW build with a custom splash screen.

**Comment by andersevenrud** [comment]
> > OSjsAppRuntimeEngine.ReadFile(filename)
> You can do this in OS.js natively with NW

Correction: You can do this in OS.js natively

I forgot to erase a part of a sentence :P

**Comment by TRoskop** [comment]
You understood me wrong. You can't read the *local* user files on my disk! If you could this, browser would have a serious security issue.

**Comment by andersevenrud** [comment]
>  You can't read the local user files on my disk!

Yes, you can with the NW build.

**Comment by andersevenrud** [comment]
The NW build is not running in your browser, only on top of webkit. Just like a normal "windows window" or whatever

**Comment by TRoskop** [comment]
Good. 
It this you final word? 
Well, it's your decision.

**Comment by andersevenrud** [comment]
> It this you final word? 

What do you mean by that ?

> Well, it's your decision.

My decision to what now ?

**Comment by TRoskop** [comment]
You said, that the NW is already enough. So this means for me, that you don't need a windows universal platform app (for the windows store).
I'm I right? 

> My decision to what now ? 
It's your decision whether I'm going to develop it or not.

**Comment by andersevenrud** [comment]
> To me it seems that the NW build is what you're looking for.
> As for the screenshots it looks like you want a NW build with a custom splash screen.

It just means that you have everything you need in place to make a "companion application"; with the description you gave.

**Comment by TRoskop** [comment]
Of course, I have everything to do it. It would also not be very hard.
But as OS.js is your "baby" I want to have your "ok" to do so. And I'm not going to develop the app just for fun. I want to make it so, that people can use it simple and that a lot of people can use it.

**Comment by andersevenrud** [comment]
> Of course, I have everything to do it. It would also not be very hard.

You can make a NW build by using the provided Grunt task: https://github.com/andersevenrud/OS.js-v2/blob/master/doc/NW.md and go from there.

> I want to make it so, that people can use it simple and that a lot of people can use it.

And that'd be good, but I'm not sure if OS.js has enough "stuff" to make a good impression in this use-case. It'd be sweet to have better networking, media integration and proper office applications and that.

It'd be sweed to have it on appstores and such as a sort of demo to see "what is possible", but not to sure if it is ready for it :/

**Comment by TRoskop** [comment]
I understand your thinking.
However, I will try to create an app these *weeks* so you can see a first preview.

And of course, OS.js can be improved, but it is already very good. :laughing:

**Comment by andersevenrud** [comment]
This year will bring *many* goodies to OS.js. Some really awesome stuff in the works and upcoming collaborations :)

**Comment by TRoskop** [comment]
* A Browser would be realy cool. 

See, this means development is stil happening. And if you increase your audience, probably more people will donate money or help you with bug reports, suggestions, patches, pull requests etc.

* Having good marketing (social media, blogs writing about this app, ...) we can increase the audience to a new level.

**Comment by andersevenrud** [comment]
> A Browser would be realy cool.

This will only be available in standalone (NW and X11 builds). But is something coming down the road

> See, this means development is stil happening.

Well, yeah. I don't intend to stop... and have not since the very first build.

> And if you increase your audience, probably more people will donate money or help you with bug reports, suggestions, patches, pull requests etc.

That goes without saying. But still, feedback/visitor rate is extremely low, and usually is in open-source projects. Sometimes you get really lucky (like I've been) and gotten some good connections and buisiness projects out of it.

> Having good marketing (social media, blogs writing about this app, ...) we can increase the audience to a new level.

OS.js is all over social media. It kind of "blew up" this december. Blog post is not much of interest since updates are mostly technical, but I am going to produce a lot of videos about the development side of things.

**Comment by tirrorex** [comment]
And standalone would be cool, i could work on an osx version

**Comment by NoNameProvided** [comment]
NW.js runs on OSX too.

**Comment by andersevenrud** [comment]
Yep, as @NoNameProvided said, it runs on OSX as well (it is not in the Grunt config by default, but can easily be added -- NOT TESTED!).

**Comment by tirrorex** [comment]
The point of making an osx standalone is to take full advantage of osx features

**Comment by NoNameProvided** [comment]
Guys, have you ever read the [nw.js docs](http://docs.nwjs.io/en/latest/)? Nw.js has access almost to all of the native features of windows, osx and linux. Including the filesystem, notifications and few other goodies in a wrapper + everything else what Node.js can reach, so there is **no advantage of implementing a custom host application layer**. It's a better idea to contribute to nw.js to add the missing features.

**Comment by tirrorex** [comment]
Yes i read the doc, there is no mention whatsoever of the possibility to call osx api.
And even if nw.js can do those calls, since the nw version of os.js was most likely design for crossplatform it will not include native api calls, so there is indeed TONS of advantages of implementing real osx code, including memory consumption and thread optimization.

**Comment by andersevenrud** [comment]
NW simply exposes the Node APIs to the client so you have full access to the underlying platform. No need for custom layers. 

> since the nw version of os.js was most likely design for crossplatform it will not include native api calls

There's no need to include anything. Node provides everything you need. (If I am not mistaking you here)

> so there is indeed TONS of advantages of implementing real osx code, including memory consumption and thread optimization.

JavaScript in its current state is single-threaded. NW runs on libwebkit, so it is a memory hog!

**Comment by NoNameProvided** [comment]
> There's no need to include anything. Node provides everything you need. (If I am not mistaking you here)

Yeah, u can call from node anything (there are modules for almost everything), but if @tirrorex  want to have some higher leve abstraction of something, its still a way more simpler to implement it as a native addon for node (so it become usable by nw.js) than implementing everything from scratch.

**Comment by TRoskop** [comment]
Just a small appendix:
The app I started to create is not a "Stand-Alone" Client! It uses a/the server of os.js.

**Comment by andersevenrud** [comment]
I'm doing a "spring cleaning" of the issues right now and wondering about the state of this ? Seing it is kind of unrelated to this project repository, I'm thinking about closing it for the time being.

**Comment by TRoskop** [comment]
I'm still working on the app (or at least I try it), but currently I've a lot of other stuff to do like school.

**Comment by andersevenrud** [comment]
Allright. Just notify me when you get around to uploading it to a repository or something :)

Closing this issue for now

**Comment by TRoskop** [comment]
Hi Guys!
I'm now finished the app. And it passed the certrification kit.
You can see here, how the first version looks like.

![screenshot 21](https://cloud.githubusercontent.com/assets/13079737/12674724/436824e8-c685-11e5-857d-6fc04c54ab09.png)
![screenshot 22](https://cloud.githubusercontent.com/assets/13079737/12674723/4366f15e-c685-11e5-9d6c-e66443ce9548.png)
![screenshot 23](https://cloud.githubusercontent.com/assets/13079737/12674726/436a6fbe-c685-11e5-997f-4efd1fa02481.png)
![screenshot 24](https://cloud.githubusercontent.com/assets/13079737/12674725/4368c204-c685-11e5-8b83-40b854a81ea9.png)
![screenshot 25](https://cloud.githubusercontent.com/assets/13079737/12674727/436cb102-c685-11e5-94eb-434b617355c4.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/13079737/12674728/436da21a-c685-11e5-94be-620dc8a2bcaa.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/13079737/12674732/439fddac-c685-11e5-9eaf-ce4a4438a59e.png)
![screenshot 28](https://cloud.githubusercontent.com/assets/13079737/12674731/439fc6c8-c685-11e5-8092-addb34413e21.png)
![screenshot 29](https://cloud.githubusercontent.com/assets/13079737/12674729/437eea7a-c685-11e5-88d2-97ac6ae0cb3d.png)
![screenshot 30](https://cloud.githubusercontent.com/assets/13079737/12674730/438132f8-c685-11e5-9874-01bbe006f712.png)

I'm going fix the last few things - only UI and language fixes and improving some code.
Later, I'm going to submit the app to the windows store. And the Code will be available once I uploaded the source code to GitHub.

Waiting for your feedback.

**Comment by eraffaelli** [comment]
I will be able to test it (I have win10) so maybe I can make feedback once available ;)

**Comment by TRoskop** [comment]
@eraffaelli  I can send you the appx-file which allows you to install it by side-loading. 
See here how to do: http://www.howtogeek.com/219651/windows-10-allows-you-to-sideload-universal-apps-just-like-android-does/

**Comment by TRoskop** [comment]
@eraffaelli  This would be very nice. I'm hoping to publish it soon.

**Comment by andersevenrud** [comment]
I'm wondering how the Microsoft Store actually works and how people will be able to locate this app there. I don-t have any experience, but I've heard vey worrying things :/

**Comment by khoaakt** [comment]
@andersevenrud Easy man! As I see nothing much to worry about that.
From a windows-fan :smile:

**Comment by andersevenrud** [comment]
But how will people that *dont know about OS.js* find it without hearing about it. Will it appear in a feed at random, or is it just searchable. How good is the search, and how much control do you have over metadata ?

**Comment by TRoskop** [comment]
@andersevenrud 
Of course the app will not appear as the top-most one in the store. But you can find it under the specific category. It works like the Google Play Store.
Moreover, you can define keywords and so on. 

Let's give it a try. We can't lose anything. And who knows, if this works as I hope, it would be good.
So, calm don't and publish :smile:

**Comment by andersevenrud** [comment]
> Of course the app will not appear as the top-most one in the store

No, that much I figured.

I'm just wondering how people would normally find it. If it works like the Play Store and those it might be a bit hard if you're not spesifically looking for it :)

But yeah, there's nothing to lose. I'm just curious

**Comment by TRoskop** [comment]
Do you, @andersevenrud , have Windows 10 (or a virtual machine of it)? Because then I could send you the first stable build to side-load it (No Visual Studio IDE needed).

**Comment by khoaakt** [comment]
@andersevenrud 

> something will have never become a reality if not try it

@TRoskop 
Maybe a winform app looks great for testing on non-Windows 10! After build, the app will automatic start to testing... Right?

**Comment by andersevenrud** [comment]
@TRoskop Nope. Maybe I can use the MS provided browser VM test images. https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/

**Comment by TRoskop** [comment]
@khoaakt 
> Maybe a winform app looks great for testing on non-Windows 10! After build, the app will automatic start to testing... Right?

I'm sorry, but you can't convert/build a windows 10 app (WUP Windows universal platform) on non-windows 10 systems. It's because of the new WinRT (Windows Runtime).
However, those apps are realy not compareable to winform-apps. They are more like Software written in WPF for the desktop.
You need Win10.

**Comment by TRoskop** [comment]
@andersevenrud I will upload the image (which you can install in just a few clicks) to you later. How can I send you a private message with the download-link?

**Comment by khoaakt** [comment]
@TRoskop 
I means write an new winform app. Not convert :smile: !
Maybe in my vacation (2 days later), i'll write it...

**Comment by TRoskop** [comment]
@khoaakt 
I planned to implement some extended JavaScript-API for os.js in my app (and I also created already two ones).
Would you like to say me when starting, so I can give you the APIs so we have the same ones so os.js can use them??

**Comment by TRoskop** [comment]
@andersevenrud 
Instead of downloading those IE-versions, just download the windows 10 ISO and use it as the demo version (30 day trials). This might be more helpful.

**Comment by andersevenrud** [comment]
@TRoskop Good old email is probably easiest, or just a dropbox link. Gitter has private chatting

**Comment by khoaakt** [comment]
@TRoskop
 I'll make an issue when start.

**Comment by andersevenrud** [comment]
@khoaakt These applications are not a part of this repository, hence should not be created here. You can use this issue if you like, or put up your own repository and link it here.

**Comment by TRoskop** [comment]
@khoaakt: Please could you notify me by email in this case. Because I do not regulary look on this issues. 
t.roskop@hotmail.de

**Comment by TRoskop** [comment]
@andersevenrud 
I just send you the email.

**Comment by khoaakt** [comment]
@TRoskop @andersevenrud
OK, guys :smile:

**Comment by khoaakt** [comment]
Well, I began to developing this. I think it would be better to make an IDE (can code, can change setting, change build config, build and testing...) for Windows. @TRoskop  @andersevenrud 
![untitled](https://cloud.githubusercontent.com/assets/6000592/12701803/34db65e2-c848-11e5-954d-9f980450d33c.png)

**Comment by TRoskop** [comment]
I published the app and it has been accepted.
Here is the link to the app: https://www.microsoft.com/store/apps/9nblggh5p91g
[Note: It might need a few hours until the app can be downloaded.]

**Comment by andersevenrud** [comment]
:+1:

**Comment by TRoskop** [comment]
They gave me a New link   https://www.microsoft.com/store/apps/9NBLGGH5P91G.

**Comment by TRoskop** [comment]
Please give me feedback and suggestions for improving. I also accept them by email: t.roskop@hotmail.de
I'll work on it and I'll later publish the source code. :+1:

**Comment by eraffaelli** [comment]
I've try for two or three minutes on mobile but it's not responsive so... xD
I'll try this weekend on desktop

**Comment by eraffaelli** [comment]
I've tried it but I didn't see anything wrong with what I do. Sorry if this doesn't help you much :/

**Comment by TRoskop** [comment]
@eraffaelli:
Could you explain what exacly is wrong? Because on my device (and emulator) it works perfect. 
Give screenshots or something like this. 

My Email: t.roskop@hotmail.de

**Comment by TRoskop** [comment]
For everyone who wants to see the Apps Source Code:
https://onedrive.live.com/redir?resid=6B9D453976CAFCF!18973&authkey=!AJLdvSrT11Apv1M&ithint=file%2czip

License: Public Domain (all Parts, only this Build)

**Comment by andersevenrud** [comment]
@TRoskop It'd be nice if you could upload the sources to your Github profile, so that the "os-js" organization could fork it and have it featured in the feed(s) :)
