### ISSUE TITLE
[Applications] Division by zero in Calculator

### ISSUE THREAD

**Issue by TheZ3ro** [os-js/OS.js#256]
**How to reproduce:**
Open OS.js (http://osjsv2.0o.no/)
Execute the Calculator App
Type "0/0"
Click "=" button
Done. :white_check_mark: 

=========================================

An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationCalculatorWindow.prototype.operation@http://osjsv2.0o.no/packages/default/Calculator/combined.js:228:11
ApplicationCalculatorWindow.prototype.init/</<@http://osjsv2.0o.no/packages/default/Calculator/combined.js:128:9
OSjs.Utils.$bind/cbNormal@http://osjsv2.0o.no/osjs.js:1079:9

```

**Comment by andersevenrud** [comment]
Maybe this should trigger some sort of easter egg? ;)

Any ideas ?

**Comment by junland** [comment]
@andersevenrud that would be cool :)

**Comment by TheZ3ro** [comment]
Good idea!

**Comment by NoNameProvided** [comment]
@andersevenrud  Some kind of black hole, what eat everything? hehe

**Comment by eraffaelli** [comment]
I don't know if this is possible but we could make an effect that blowing up the whole window.
Or the same with a black hole.

**Comment by junland** [comment]
@eraffaelli Ohhhhhhh yesssss that sounds good.

**Comment by andersevenrud** [comment]
Some sort of "black hole" effect could work only using CSS. If the window was to "shatter" or something like that some kind of third party lib is required to make an "image" of a DOMElement and then manipulate it with `<canvas>` or something

**Comment by andersevenrud** [comment]
Just for now I added a little animation that sort of resembles a black hole sucking the calculator into it. I'll have some more fun with this later, but for now I am closing this :)
