### ISSUE TITLE
Creating an organization for the project? 

### ISSUE THREAD

**Issue by NoNameProvided** [os-js/OS.js#258]
There is more than one repo related to the os.js project. Have u considered creating a github organization for it? So people could have a more clear overview over the projects. (However as I see osjs is already taken sadly.)

**Comment by andersevenrud** [comment]
Yeah, this is something I definately should do. It just needs some proper planning!

Thanks for reminding me!

**Comment by andersevenrud** [comment]
https://github.com/os-js :)

I really want to transfer all repositories over here, including renaming "OS.js-v2" to "OS.js", but it will break a lot of stuff... so I am scared :/

**Comment by andersevenrud** [comment]
Also, the homepage will break since it is a part of github pages. I will have to plan this carefully.

It seems Github at least redirects all traffic from old name/repo--so that is a relief.

**Comment by andersevenrud** [comment]
I just tested transfer of ownership + renaming and it worked just fine *phew*.

I just have to ensure that the homepage domain transfers smoothly.

Gitter should take care of this as well so the community does not get lost: https://github.com/gitterHQ/gitter/issues/153

**Comment by andersevenrud** [comment]
I have transfered all the package repositories and renamed them as well. It seems to work just fine :)

**Comment by andersevenrud** [comment]
It has now all been transfered *successfully*.

Thanks to @indus for incredible response time and support!

**Comment by NoNameProvided** [comment]
Yay!
