### ISSUE TITLE
[General] "Countable" translation

### ISSUE THREAD

**Issue by eraffaelli** [os-js/OS.js#291]
Following https://github.com/os-js/OS.js/pull/289, is it possible to make countable translation? To be able to use plural when needed?

For example (in english) :
> Showing 1 file/Showing X file**s**

Another example from symfony project :
> {0} There are no apples|{1} There is one apple|]1,Inf[ There are %count% apples

(from http://symfony.com/doc/current/book/translation.html)

**Comment by andersevenrud** [comment]
It'd be nice, but that example looks very gnarly! Maybe a programatic approach is nicer ? Ex:

```
'LBL_APPLES': function(arg1) {
  if ( arg1 <= 0 ) {
    return 'There are no apples';
  } else if ( arg1 === 1 ) {
    return 'There is one apple';
  }
  return 'There are {0} apples';
}
```

**Comment by eraffaelli** [comment]
Well, the way to do it doesn't really matter ^^
But in many languages the way to write words need that count, so it would be nice to have it.

You want to put that example in the locales.js files? Or in the "main" files and the locales doesn't change?

**Comment by andersevenrud** [comment]
The example was generic, it fits in all usecases.

**Comment by andersevenrud** [comment]
#304 superseeds this
