### ISSUE TITLE
[VFS] WebDAV & OwnCloud

### ISSUE THREAD

**Issue by corbinu** [os-js/OS.js#297]
In reference to my comment in issue #279 but also somewhat separate. It would be very cool to have OwnCloud support for VFS as this would allow an open source VFS/could solution for OS.js to be installable on the host server without any dependency on outside cloud services.

Obviously still think supporting others is great also just would be nice to have the option of an isolated system.

---
- [x] VFS Module
- [x] VFS Basics: scandir/read/write/url
- [x] VFS Advanced: move/rename/copy/delete
- [ ] Extended DAV support
- [ ] DAV Auth Header doc

**Comment by andersevenrud** [comment]
It does not look like OwnCloud has any Client APIs. All I could find is documentation on their REST API that has a supported PHP library.

Do you know anything about this ?

**Comment by corbinu** [comment]
My understanding is that it implements the WebDAV file protocol and that that is the recommend path.

**Comment by andersevenrud** [comment]
Then this might be of use https://github.com/aslakhellesoy/webdavjs at least for the node backend

**Comment by corbinu** [comment]
Looks like it has not been updated in 7 years. I would probably try this https://www.npmjs.com/package/jsDAV

**Comment by andersevenrud** [comment]
jsDAV seems to be a server library. I can't find anything about client abstractions in their wiki, nor examples.

Ex:
- https://github.com/mikedeboer/jsDAV/wiki/Getting-Started
- https://github.com/mikedeboer/jsDAV/wiki/curl

Even though webdavjs has not been updated in 7 years, at least the RFC's have not changed either, hehe. Maybe the code-style is a bit outdated, but I will give it a go

**Comment by corbinu** [comment]
ok ... ya I will try to see if there is a newer client lib

**Comment by corbinu** [comment]
If you want to go strait from the browser then this could work:
https://github.com/sara-nl/js-webdav-client

Or a super low level node lib
https://www.npmjs.com/package/webdav-fs

**Comment by andersevenrud** [comment]
> https://github.com/sara-nl/js-webdav-client

This was the first I looked at. It expects you to use a WebDAV service with JSONP support (or similar). This library expects you to run your own dav server on the *same host*. So it won't work in cases where you host your files remotely.

> https://github.com/perry-mitchell/webdav-fs

This looks kind of over-engineered for its purpose. I think I like webdavjs' simplicity better. After all, all it really is, is a XHR wrapper that does REST calls.

https://github.com/aslakhellesoy/webdavjs/blob/master/src/webdav.js

It also has a lot nicer code (imo) and seems way more friendly to changes.

**Comment by andersevenrud** [comment]
> https://github.com/sara-nl/js-webdav-client

This was the first I looked at. This library expects you to run your own dav server on the *same host*. So it won't work in cases where you host your files remotely.

> https://github.com/perry-mitchell/webdav-fs

This looks kind of over-engineered for its purpose. I think I like webdavjs' simplicity better. After all, all it really is, is a XHR wrapper that does REST calls.

https://github.com/aslakhellesoy/webdavjs/blob/master/src/webdav.js

It also has a lot nicer code (imo) and seems way more friendly to changes.

**Comment by andersevenrud** [comment]
![webdavtest](https://cloud.githubusercontent.com/assets/161548/12583252/05c56da2-c442-11e5-941c-fea5ea80fa03.png)

It seems I don't even have to add any third party libraries. Works like a charm using OS.js internal XHR tools :)

**Comment by andersevenrud** [comment]
I now have the beginnings of a WebDAV VFS module for OS.js :)

**Comment by corbinu** [comment]
Cool sounds good

**Comment by andersevenrud** [comment]
It is now possible to mount WebDAV (Tested with OwnCloud):

```
OSjs.VFS.createMountpoint({
  name: 'ownCloud',
  type: 'webdav',
  description: 'WebDAV Test',
  options: {
    host: 'http://10.0.0.89/remote.php/webdav/',
    ns: 'DAV:',
    username: 'anders',
    password: 'abc123'
  }
});
```

Next step is to make a dialog for actually doing this via GUI.

**Comment by andersevenrud** [comment]
Ref: #304

**Comment by piranna** [comment]
Just to drop by :-P I implemented [Davius](https://github.com/piranna/Davius), my own static HTTP/WebDAV server, if you are interested :-) I'm planning to use it to serve the static content and manage the file operations on NodeOS (that's why I asked about WebDAV support :-P ).

**Comment by andersevenrud** [comment]
@piranna I'll have a look :)

**Comment by piranna** [comment]
Cool :-)

**Comment by corbinu** [comment]
@andersevenrud Sweet!

**Comment by andersevenrud** [comment]
A connection dialog is soon complete (#304) so you don`t have to do it via console :P

**Comment by andersevenrud** [comment]
Closing this issue because it will be separated into https://github.com/os-js/osjs-webdav-vfs when v3 comes along.
