### ISSUE TITLE
[Authenticator] LDAP

### ISSUE THREAD

**Issue by corbinu** [os-js/OS.js#298]
It would be nice to allow OS.js to authenticate against an LDAP server perhaps using: http://ldapjs.org

This way it could be easily integrated into a company's existing authentication stack

(feel free to rename this issue however you like not sure what category it belongs in)

**Comment by andersevenrud** [comment]
This is easily done via http://os.js.org/doc/tutorials/create-handler.html. I'd have to set up a domain and test it locally. Since I have a lot of other stuff on my plate, it might take a while to get around to.

**Comment by corbinu** [comment]
Ok no worries just at least wanted an open issue. If I ever have time I will take a stab. Would you want me to make sure it also works on the PHP backend?

**Comment by andersevenrud** [comment]
I'm not to sure about the future of the PHP backend, but it would be nice to have the same functionality anyway. I know from experience that PHPs LDAP internals are more than good enough for authentication.

If you find the time, then, please, go ahead :)

**Comment by andersevenrud** [comment]
I'm closing this issue because it will be separated out into another repository.

I've set up https://github.com/os-js/OS.js/osjs-ldap-auth (but is private until I have it fully wokring)

**Comment by vlotho** [comment]
your work on LDAP authentication is moving forward?

**Comment by andersevenrud** [comment]
@vlotho I commited what I have so far, and you can look at it here: https://github.com/andersevenrud/osjs-ldap-auth

Login is working, but only tested on OpenLDAP as of now.
