### ISSUE TITLE
Changing style in core.sss and gui.css

### ISSUE THREAD

**Issue by RickGlimmer** [os-js/OS.js#300]
I wanted to change the body background color and did not find an easy way to do that without changing the core.css directly.
I would like the original css to be unchanged and add my styles (overruling the original styles) to it by using a separate file.

The solution i made is to create a os.js\dev\src\client\stylesheets directory and include it in the 200-compile.json file
```javascript
    ...
    "stylesheets": [
        "src/client/stylesheets/core.css",
        "src/client/stylesheets/gui.css",
        "dev/src/client/stylesheets/core.css"
    ]
    ...
```
The css file has 

```css
    body {
        background-color : #e2f6fc;
    }
```
I am just starting with this so it might not be the best way to do it, in that case i would appreciate some advice.

**Comment by andersevenrud** [comment]
This is the "correct" way to do it.

**Comment by andersevenrud** [comment]
Preferably, you'd want to create a custom file, and not modify the inluded ones. Ex, src/conf/900-mystuff.json

```
{
  "stylesheets": [
    "src/client/stylesheets/mycustom.css"
  ]
}
```

**Comment by andersevenrud** [comment]
hmm. Come to think of it, ignore my previous comment! You cannot add items to the list like that.

**Comment by andersevenrud** [comment]
Run `grunt dist-files` afterward to update 'dist-dev'.

If you use 'dist', run `grunt core`

**Comment by RickGlimmer** [comment]
I also added a WebAPI handler (for a IIS WebAPI .NET backend) and noticed that a 900-custom.json file was added. I am not familiar with Grunt so i am a bit on a treasure hunt :) how everything is tied together.
For my use i would also need to change other parts that are a bit deeper in the source. The login page for instance i would need to add a 'Companyname' field as that is how my authentication backend is made. I found what to change, but that also requires me to change original .js files. Ideally i would do a grunt myVersion. Any pointers on how to accomplish that?
I probably will be able to contribute the WebApi handler and IIS server files, this would mean that i would like two version of that handler, one that integrates nicely with os.js and a separate one that is specific for me.

**Comment by andersevenrud** [comment]
the 900-custom.json file appears whenever you do `grunt config:set:something:orother`. 

> The login page for instance i would need to add a 'Companyname' field as that is how my authentication backend is made.

You want to create a custom `dist` distribution. Copy `src/templates/dist/default` and rename it to your liking. Then `grunt config:set:dist.template:mynewname`. You can now customize the login screen without modifying the provided files.

The interaction with the login form all happens in a `handler`. So you probably want to make your own and override the `initLoginScreen` method.

**Comment by andersevenrud** [comment]
`grunt dist-files` rebuilds your dist directory to the forementioned template you made

**Comment by RickGlimmer** [comment]
Ah. Got it!. Thanks.
