### ISSUE TITLE
[Server] Improvements to API calls

### ISSUE THREAD

**Issue by RickGlimmer** [os-js/OS.js#302]
Currently a write to the VFS has nested methods and argument:
```javascript
    { method: "fs",
      arguments: {
        method: "write",
        arguments: ["home:///text.txt", "data:text/plain;base64,cnJnaGk=", {}]
      }
    }
```
The URL is http://osjsv2.0o.no/API

My suggestion is to change that url to http://osjsv2.0o.no/FS/write and the following payload:
```javascript
    {
      path: "home:///text.txt",
      mime: "text/plain",
      options: {},
      encoding: "Base64",
      data:   "cnJnaGk="
    }
```
On the backend a MVC/WebAPI/REST style can be used.
FS would be the controller and write the action. The body would then have a very simple payload with meaningful properties that does not need any parsing.
It is also more in line with for instance what the scandir function returns.
Also adding a option 'overwrite' as mentioned in my other issue would be nice to have to make sure the backend has permission to overwrite a file. Other options could be 'append','touch' and maybe others.

I can get this by changing my custom handler by parsing the object before sending it, but i think it would be nice for others also.
Here is a snippet of my handler that changes the url and content.
```javascript
          //Map to a controller and action
          switch (method) {
              case "login":
              case "logout":
              case "settings":
                  path = APIURI;
                  controller = "/auth/";
                  action = method;
                  break;
              case "fs":
                  path = FSURI;
                  controller = '';
                  action = args.method;
                  break;
          }

          var data = {
              url: path + controller + action,
              method: 'POST',
              json: true,
              body: {
                  'arguments': args.arguments
              },
```
This is without parsing the arguments as i think that would be much better if done before it gets to this function.

**Comment by andersevenrud** [comment]
This is pretty much a goal for the beta :)

Just gotta find time for it. It would involve:

- Refactor the [node and php] HTTP request handling a bit to look up method from URL
- Refactor the [node and php] VFS modules
- Refactor the [client] VFS wrapper
- Refactor the [client] VFS modules and helpers
- Update unit tests (which is very handy in this situation for server)

**Comment by RickGlimmer** [comment]
I am not very familiar with node.js and never used php, so i can not be much help there.
I could do my part with the VFS wrapper, modules and helpers. I currently change everything in my handler so that the backend is already getting this format. Maybe others also have some suggestions so that it can be done at one time. Also some time to think this through might be good.

**Comment by andersevenrud** [comment]
I'll have this in the back of my head for a while to see how it developes. I already have a pretty clear picture over how this should be done, but would like it to mature a bit more :)

**Comment by andersevenrud** [comment]
I'm going to start on this now, in a separate branch.

**Comment by andersevenrud** [comment]
@RickGlimmer New branch https://github.com/os-js/OS.js/tree/new-api-uris now has this pretty much done. Just gotta do a lot of testing (probably some bugs left) and refactor the PHP code as well :)

**Comment by RickGlimmer** [comment]
Great! I will check it out.

**Comment by andersevenrud** [comment]
I think this is pretty much done now! :D 

So now all api functions have respective URIs: `/API/function` and `/FS/function`

**Comment by RickGlimmer** [comment]
You are fast! :) I will test it tomorrow as it is getting late here (03:00) :)
I screwed up my local copy and restoring from origin i seem to miss the file settings.js. And i can't seem to find it and a grunt does not create one. Any idea?

**Comment by andersevenrud** [comment]
> You are fast! :)

When I first get started, it sort of consumes me :)

Currently doing some other improvements for clarity purposes and consistency.

> I screwed up my local copy and restoring from origin i seem to miss the file settings.js. And i can't seem to find it and a grunt does not create one. Any idea?

Someone else had this problem on Windows as well... hmm. Try removing dist and dist-dev then do `grunt checkout -- dist dist-dev` recreate symklinks and run `grunt`

**Comment by RickGlimmer** [comment]
Unfortunately that did not work.
I also did the whole installation process from scratch and that did also not work which is weird as it worked before.
How is settings.js created?

**Comment by andersevenrud** [comment]
`grunt config`. Syntax error in one of your src/conf files ?

**Comment by RickGlimmer** [comment]
i got an error. This is from a fresh clone of your os.js here on github?????

[TypeError: str.replace is not a function] 'TypeError: str.replace is not a func
tion\n    at fixWinPath (F:\\os.js\\src\\build.js:252:18)\n    at F:\\os.js\\src
\\build.js:802:33\n    at Array.forEach (native)\n    at buildServer (F:\\os.js\
\src\\build.js:801:37)\n    at Object.createConfigurationFiles (F:\\os.js\\src\\
build.js:822:7)\n    at Object.<anonymous> (F:\\os.js\\Gruntfile.js:211:14)\n
 at Object.thisTask.fn (F:\\os.js\\node_modules\\grunt\\lib\\grunt\\task.js:82:1
6)\n    at Object.<anonymous> (F:\\os.js\\node_modules\\grunt\\lib\\util\\task.j
s:301:30)\n    at Task.runTaskFn (F:\\os.js\\node_modules\\grunt\\lib\\util\\tas
k.js:251:24)\n    at Task.<anonymous> (F:\\os.js\\node_modules\\grunt\\lib\\util
\\task.js:300:12)'

**Comment by andersevenrud** [comment]
oh. goddamn windows! Fixing now

**Comment by andersevenrud** [comment]
There

**Comment by RickGlimmer** [comment]
I undid commit d190c81a2133a761b04c32b0de9e626c2f6ddcdc, then it worked again.

**Comment by andersevenrud** [comment]
I know.I forgot about the windows spesific path workaround that did not take that into account

**Comment by RickGlimmer** [comment]
At least i can go to sleep now as i got it working again. :) Tomorrow i will test your new branch.

**Comment by andersevenrud** [comment]
nitenite :)

**Comment by andersevenrud** [comment]
Superseeded by #304
