### ISSUE TITLE
[API] Handler VFS method call consistency

### ISSUE THREAD

**Issue by RickGlimmer** [os-js/OS.js#303]
At the moment _NullModule.read (in src\client\javascript\vfs\_null.js) is the only function that does not use the handler that is returned by OSjs.Core.getHandler(). I see that the .write has been changed to use the handler.
Would it not be possible to make a OSjs.VFS.internalCall so that i can process this in my custom handler?

**Comment by andersevenrud** [comment]
Update for this is coming later today. There are some other changes coming relating to this coming :)

**Comment by RickGlimmer** [comment]
:+1: Great!. I will concentrate on my backend first. :)

**Comment by andersevenrud** [comment]
Hm. I've been working on the VFS today, and now I'm not sure what you're talking about.

My `Handler::onVFSRequest()` is triggering on all modules. It's the main wrapper for all VFS calls

https://github.com/os-js/OS.js/blob/f24f5aa8bd3ac7aadc71d259c55469130c980e98/src/client/javascript/vfs.js#L200

**Comment by RickGlimmer** [comment]
it is this part:
```javascript
  _NullModule.read = function(item, callback, options) {
    options = options || {};
    options.onprogress = options.onprogress || function() {};
    if ( API.getConfig('Connection.Type') === 'nw' ) {
      OSjs.Core.getHandler().nw.request('fs', {
        'method': 'read',
        'arguments': [
          item.path,
          {raw: true}
        ]
      }, function(err, res) {
        callback(err, res);
      });
      return;
    }
    this.url(item, function(error, url) {
      if ( error ) {
        return callback(error);
      }
      Utils.ajax({
        url: url,
        method: 'GET',
        responseType: 'arraybuffer',
        onprogress: function(ev) {
          if ( ev.lengthComputable ) {
            options.onprogress(ev, ev.loaded / ev.total);
          } else {
            options.onprogress(ev, -1);
          }
        },
        onsuccess: function(response, xhr) {
          if ( !xhr || xhr.status === 404 || xhr.status === 500 ) {
            callback(xhr.statusText || response);
            return;
          }
          callback(false, response);
        },
        onerror: function(error) {
          callback(error);
        }
      });
    });
  };
```

**Comment by RickGlimmer** [comment]
I see you moved some files. It is now in internal.js on line 93
internalTransport.read = function(item, callback, options) {

**Comment by andersevenrud** [comment]
> I see you moved some files. It is now in internal.js

I just made some changed to properly name and split some sections. Functionality has not changed :)

> it is the following part. All others ('write','exists' etc) use OSjs.VFS.internalCall and use the loaded handler. This one has its own Ajax part that it uses.

That's because I use a XHR request that returns `ArrayBuffer`. This is best done with the browser API and not channel through the backend.

I can make it possible to customize this as well. Just have to think it out first.

**Comment by RickGlimmer** [comment]
If the 'write' goes through the handler i think the read should do the same. The handler could return an ArrayBuffer as well.
It will keep everything together which is more convenient. It took me some time to find this exception to the 'rule' and that makes maintaining/porting a bit more difficult.

**Comment by andersevenrud** [comment]
This was added to the branch https://github.com/os-js/OS.js/tree/new-api-uris.

https://github.com/os-js/OS.js/blob/new-api-uris/src/client/javascript/handler.js#L341

You can now hook into them all:

- `_callNW()` for NW builds
- `_callAPI()` normal API and VFS calls
- `_callXHR()` this is the function you want to modify

**Comment by andersevenrud** [comment]
I might change the name from `XHR` to `GET` or something like that instead

**Comment by andersevenrud** [comment]
Ok. So now the handler has these:

- `_callNW()` For NW.js builds
- `_callAPI()` For API and VFS calls
- `_callGET()` For VFS file reads/downloads
- `_callPOST()` For VFS [browser] file uploads

That should cover everything :)

**Comment by RickGlimmer** [comment]
Maybe even split _callAPI into _callAPI and _callVFS. Then everything has its own.

**Comment by andersevenrud** [comment]
- `__callXHR()` Setup for all general browser API/VFS calls
- `__callGET()` Setup for reads/downloads
- `__callPOST()` Setup for browser file uploads
- `_callAPI()` Wrapper API calls
- `_callVFS()` Wrapper VFS calls

**Comment by andersevenrud** [comment]
Superseeded by #304
