### ISSUE TITLE
slice bug

### ISSUE THREAD

**Issue by maekawatoshiki** [os-js/OS.js#318]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://osjsv2.0o.no/packages/extras/AceEditor/vendor/ace/build/src/worker-javascript.js
Line: 9584:0
Message: TypeError: _.slice is not a function
```

**Comment by andersevenrud** [comment]
This seems to be a bug with Ace editor (which is a third-party editor).

Probably fixed in a later version. The demo server is running an outdated version :)
