### ISSUE TITLE
An error occured while trying to launch: CoreWM

### ISSUE THREAD

**Issue by lordloh** [os-js/OS.js#320]
I get the an error in a dialog box while I try to launch the application in my browser. The console does not give any indication of error. 

> Failed to launch Application
> 
> An error occured while trying to launch: CoreWM
> 
> Application resources missing for 'CoreWM' or it failed to load!

then 

> Failed to initialize OS.js
> 
> An error occured while initializing OS.js
> 
> Cannot launch OS.js: Failed to launch Window Manager: Application resources missing for 'CoreWM' or it failed to load!

How do I fix these?

**Comment by joaofraga** [comment]
:+1: same here

**Comment by andersevenrud** [comment]
Did you build OS.js correctly ?

**Comment by junland** [comment]
@lordloh Was it the dist version or the dist-dev version?

**Comment by joaofraga** [comment]
@andersevenrud I have builded using auto install. Should I try build it?

**Comment by andersevenrud** [comment]
@joaofraga Do you know how to use the Network Monitor and Console in the browser ? I'm very interested in finding out why this happens

**Comment by joaofraga** [comment]
@andersevenrud Yes, I'll try to debug it. Do you want some specific information?

**Comment by andersevenrud** [comment]
I am aware of this and know the reason. I will fix this today

**Comment by andersevenrud** [comment]
Should be resolved now. Thanks for reporting in!

**Comment by lordloh** [comment]
:-) Wow. The issue got fixed while I was sleeping through the night :-)
