### ISSUE TITLE
"Launching..." window remains pendant after 'Test' app launch

### ISSUE THREAD

**Issue by artf** [os-js/OS.js#326]
Firefox 43.0.4 on OSX Yosemite 10.10

![ss-test-app](https://cloud.githubusercontent.com/assets/11614725/12799137/8f78b89c-cacd-11e5-9f62-3f59d8da024d.png)

OT: Thanks for doing such amazing software

**Comment by andersevenrud** [comment]
This application has not been updated to use the latest APIs, hence why the loading stays.

Will be fixed in another repo: https://github.com/os-js/OS.js-store/tree/master/packages

**Comment by andersevenrud** [comment]
This should be resolved now
