### ISSUE TITLE
[Applications] Calculator % does not work as expected

### ISSUE THREAD

**Issue by 00cpxxx** [os-js/OS.js#334]
It looks like the % does not work, if you type "100 - 10 % = " you should get 90 at least in a real calculator and in OSX calculator. The js calculator returns 99.9 as a result.

It looks like when I insert the second operand and press % it will convert the number to a decimal representing the value, so 10% becames 0.1. But when I press = it should do <first operand> - <first operand * second operand> but it is doing something else.

As another example typing "100 - 50% =" results in 99.5 as result.

**Comment by andersevenrud** [comment]
The Calculator is going to be reworked. It's kind of crap at the moment :)

**Comment by 00cpxxx** [comment]
It is actually very beautiful IMO, it does what calculators are supposed to do =)

**Comment by andersevenrud** [comment]
This should now be fixed! :)

NB: Demo server has not been updated, so don't expect it to work there

**Comment by 00cpxxx** [comment]
Thank you very much for the quick fix.
