### ISSUE TITLE
ssh terminal bug ?

### ISSUE THREAD

**Issue by keikyoku** [os-js/OS.js#336]
i just wanted to launch ssh terminal and a pop-up with this message appeared
```
TypeError: OSjs.Helpers.PTYTerminal is not a function
    at ApplicationTerminalWindow (https://osjsv2.0o.no/FS/get/home:///.packages/Terminal/main.js:47:21)
    at https://osjsv2.0o.no/FS/get/home:///.packages/Terminal/main.js:189:23
    at Object.Utils.ajax.onsuccess (https://osjsv2.0o.no/osjs.js:5320:9)
    at XMLHttpRequest.onReadyStateChange (https://osjsv2.0o.no/osjs.js:1199:16)
```

**Comment by andersevenrud** [comment]
You cannot install these applications into your home directory. The "extras" repository is for system installation.

https://github.com/os-js/OS.js-extras/blob/master/Terminal/README.md


http://os.js.org/doc/manuals/man-package-manager.html

**Comment by andersevenrud** [comment]
Oh. This is the demo site!

Sorry -- I will fix this. These packages do not belong there. Someone tried to install it -- but that will not work on that server :)
