### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by junland** [os-js/OS.js#344]
## Expected behavior
Should not display an error?

## Actual behavior
Really shouldn't display an error... 

I don't think anyone has tried using a 3rd party css file within a regular GUI application so that's why I submitted this issue. :)

Error that was displayed:

```
ReferenceError: $ is not defined
    at http://localhost:8000/packages/default/SampleApp/combined.js:107:97
```

## Steps to reproduce the error
Build a sample app and place a button using `Materialize` front-end CSS.
* `materialize.min.css` in `resources` folder within the SampleApp package folder
* `materialize.min.js` in `resources` folder within the SampleApp package folder

`scheme.html` should look like something like this:
```
<application-window data-id="SampleAppWindow">
  <link rel="stylesheet" href="./resources/materialize.min.css">
  <script src="./resources/materialize.min.js"></script>
  <a class="waves-effect waves-light btn">Stuff</a> 
</application-window>
```

gist for `combined.js`: https://gist.github.com/junland/897399898f0e5cd9dad1

`metadata.json` should look like this:
```
{
  "className":  "ApplicationSampleApp",
  "name":       "SampleApp",
  "mime":       null,
  "icon":       "categories/applications-system.png",
  "preload":    [
    {"src": "main.js", "type": "javascript"},
    {"src": "main.css", "type": "stylesheet"},
    {"src": "./resources/materialize.min.css", "type": "stylesheet"},
    {"src": "./resources/materialize.min.js", "type": "javascript"}
  ]
}
```
## (Optinal) Browser and OS information
N/a

**Comment by andersevenrud** [comment]
> ReferenceError: $ is not defined

Are you trying to use jQuery ? :)

**Comment by andersevenrud** [comment]
```
<application-window data-id="SampleAppWindow">
  <link rel="stylesheet" href="./resources/materialize.min.css">
  <script src="./resources/materialize.min.js"></script>
  <a class="waves-effect waves-light btn">Stuff</a> 
</application-window>
```

This is a bit redundant. You already load them from metadata.json file :)

**Comment by junland** [comment]
> Are you trying to use jQuery ? :)
I guess so, I think jQuery is embedded into `.js` file

> This is a bit redundant. You already load them from metadata.json file :)

Yea, I wasn't sure if there was any difference. I loaded it from the `scheme` then tested it out. Come to find out that it doesn't work. So I loaded it into the  `metadata.json` file and just forget to to remove the `scheme.html` is there a conflict with having jquery like that or is there a conflict with how I loaded the materialize files?

**Comment by andersevenrud** [comment]
> I guess so, I think jQuery is embedded into .js file

Just took a peek in the docs, and it says: "One last thing to note is that you have to import jQuery before importing materialize.js!", so you have to add that too to your meta :)


>  is there a conflict with having jquery like that or is there a conflict with how I loaded the materialize files?

You won't get any conflicts here. OS.js has no dependencies to begin with in the client, so you can mix and mash however you want.

**Comment by junland** [comment]
>Just took a peek in the docs, and it says: "One last thing to note is that you have to import jQuery before importing materialize.js!", so you have to add that too to your meta :)

Whoops, guess well I did do this before going to be and I was really tired. :/

>You won't get any conflicts here. OS.js has no dependencies to begin with in the client, so you can mix and mash however you want.

Ah okay! Good to know!

**Comment by andersevenrud** [comment]
Derp!

I just now realized that you cannot include third-party stuff via manifest in iframe applications. They are completely isolated, and anything you "preload" is loaded into the OS.js "side"....


I've updated the tutorials now... so it mentiones this briefly: http://os.js.org/doc/tutorials/iframe-application.html

**Comment by junland** [comment]
I'm not using a iframe par say, I just used the regulars OS.js and stripped the OS.js GUI out and just added custom CSS / HTML

**Comment by junland** [comment]
Yea, I placed Jquery into the metadata file and it worked :)

**Comment by andersevenrud** [comment]
:+1:
