### ISSUE TITLE
Unable to logon because of activation of encryption with MYSQL authentication 

### ISSUE THREAD

**Issue by webmst** [os-js/OS.js#345]
Hi Anders,
After a `git pull` I realize you've just introduced encryption in mysql logon (I agree), resulting in me being unable to logon using already preset clear-text password.

To be able to logon again, **I had to manually set the default hash for all the users** in the mysql table as you showed in the updated mysql instructions.

Now, this is the question: as I cannot easily customize the password because of encryption, is there a way to perform a user password change via the GUI (security issue)?

Thanks in advance.

**Comment by andersevenrud** [comment]
I'm making a CLI tool to set/modify the mysql handler users. It will be added today when I get back from work :)

**Comment by andersevenrud** [comment]
Also, GUI utilities for stuff like this is something in the works as well. (Not only user management, but lots of system tools)

**Comment by webmst** [comment]
Congratulations for your outstanding commitment... I'm looking forward to test!

**Comment by andersevenrud** [comment]
You can now do:

```

node bin/mysql-user.js pwd <username>

```

**Comment by webmst** [comment]
`node bin/mysql-user.js pwd admin` gives:

module.js:340
    throw err;
          ^
    Error: Cannot find module 'mysql'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/usr/local/OS.js/bin/mysql-user.js:160:25)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Function.Module.runMain (module.js:497:10)

(I've just executed `grunt config` and `grunt core`)

**Comment by andersevenrud** [comment]
> Error: Cannot find module 'mysql'

Seems like you don't have the required modules installed ;)

https://github.com/os-js/OS.js/blob/master/doc/mysql-handler.md

**Comment by webmst** [comment]
Can they have been lost?
I was already using mysql til you activated encryption

**Comment by andersevenrud** [comment]
Are you using the PHP server ?

**Comment by webmst** [comment]
No, apache 2.4, as in your demo server

**Comment by andersevenrud** [comment]
Then you-re using the PHP server. That explains why you get "cannot find module" -- you never installed them, as they are not required for the PHP server to run, but is for Node (and the CLI tool)

**Comment by webmst** [comment]
I don't understand what you mean.
My mysql setup was perfectly working til you activated encryption (that I get via `git pull),` I haven't started another container, I'm still using apache.

**Comment by webmst** [comment]
I had already installed mysql and bcryptjs modules

**Comment by andersevenrud** [comment]
> I don't understand what you mean.

You're using Apache, which means you are using the PHP OS.js Server.

> I had already installed mysql and bcryptjs modules

Maybe you installed them in the wrong directory ? You would not have noticed, because the PHP server does not care about these at all.

---

Install them in the root directory of OS.js installation: `npm install mysql bcryptjs` and try using the utility again

**Comment by andersevenrud** [comment]
`bin/mysql-user.js` is a utility written in node, so it requires the npm modules to run. So my guess is that you did not install them correctly the first time around :)

**Comment by webmst** [comment]
> You're using Apache, which means you are using the PHP OS.js Server.

Now I understand what you meant, please note that for me it meant I had started OS.js using a separate service PHP instance (container), as you documented, e.g.:
`cd dist; php -S 0.0.0.0:8000 ../src/server/php/server.php`

`Install them in the root directory of OS.js installation:  npm install mysql bcryptjs  and try using the utility again`

Tried again the installation , but same results.

**Comment by andersevenrud** [comment]
> Tried again the installation , but same results.

And the module is not here `/path/to/osjs/node_modules/mysql` ?

**Comment by webmst** [comment]
Well, there is a `node-mysql`, not a `mysql`

**Comment by andersevenrud** [comment]
Aha! Remove the  `node-mysql` one and try install again.  I think the package has changed name over time and it is a "collision" or something.

**Comment by andersevenrud** [comment]
> I think the package has changed name over time and it is a "collision" or something.

Either that, or the dependency was changed.

You're absolutely sure youre installing from `/path/to/osjs` right, and not some subfolder ?

**Comment by webmst** [comment]
Yup, it works deleting node-sql and performing `npm install mysql` again.
Eventually I was able to change all the user password as I needed.

**Comment by andersevenrud** [comment]
Good to hear! :)
