### ISSUE TITLE
Touch Menu Touch Up's

### ISSUE THREAD

**Issue by junland** [os-js/OS.js#346]
Need to fix some of the scaling with the touch menu.
![screenshot from 2016-02-24 21-24-25](https://cloud.githubusercontent.com/assets/9792545/13308892/1bc06140-db3d-11e5-8c55-b76abd220afb.png)

**Comment by andersevenrud** [comment]
This whole thing is going to be reworked. Not sure about the design though ... gotta give it a think,

**Comment by andersevenrud** [comment]
Any changes will be noted in #329 :)

**Comment by junland** [comment]
Will do :) You could just exclude the text and just have the icons.

**Comment by andersevenrud** [comment]
![embiggen](https://cloud.githubusercontent.com/assets/161548/13328696/63536940-dbf0-11e5-98df-5e76bd3aaf5c.png)

I've embiggened the size of the entries... so at least that helps; a bit :)

**Comment by junland** [comment]
This my be out of the scope of how OS.js is themed, but maybe for the touch menu could be something like this below? (Click the button in the center.)

http://swart.in/LaunchPad/#

Just a thought, thinking in terms of phones / tablets. It's cool because it has a search feature for apps.

**Comment by andersevenrud** [comment]
Something like that is the plan for this :)

**Comment by junland** [comment]
Ahhhhhhhhhhhhh. :)

**Comment by andersevenrud** [comment]
On devices <=800px the menu now goes "full screen" and has scroll when all entries does not fit :)

Also, on these devices Windows are always fullscreen and the panel has a "minimized" version applied to it.

I've started making the Scaled UI stuff, so this was the first step :)
