### ISSUE TITLE
Probleme lors de l'import d'un fichier

### ISSUE THREAD

**Issue by cartozamis** [os-js/OS.js#350]
Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
TypeError: cbError is not a function
    at Object.OSjs.Utils.ajax.onerror (http://213.111.30.84:8000/client/javascript/handler.js:459:9)
    at XMLHttpRequest.onReadyStateChange (http://213.111.30.84:8000/client/javascript/utils/xhr.js:109:16)
```

**Comment by andersevenrud** [comment]
I can't solve this without any information on how to reprodue it

**Comment by andersevenrud** [comment]
Could you provide reproduction description ? :)

**Comment by andersevenrud** [comment]
I'm closing this now because I have no way to replicate this.

Feel free to re-open this again if you have some more feedback about this issue
