### ISSUE TITLE
Extending the Settings panel

### ISSUE THREAD

**Issue by muka** [os-js/OS.js#352]
Hi,
I've started working with OS.js from a while and I'm really happy about it. Great work!

Back to the issue, I would like to start working on a network manager by integrating it to the DBus system.
For now, I've started working on a standalone application with its own UI.

I would like to suggest (as feature request) to extend the current Settings application in order to allow pluggable components (eg network, bluetooth, printers) a-la control panel

I'm available to work on this but would like to hear your opinion on this first

Thanks
Luca

**Comment by andersevenrud** [comment]
Hi muka,

Thanks for the kind words!

You might be interested in https://github.com/os-js/OS.js-system

I'm also working on integrations like this (only not DBUS at the moment).

>  would like to suggest (as feature request) to extend the current Settings application in order to allow pluggable components (eg network, bluetooth, printers) a-la control panel

Yes. This is basically the plan for the future Settings application. It should behave more like a control-panel as you said.

If you want to take a stab at it, then I don't mind at all :)

**Comment by muka** [comment]
Ok great :+1:  better for me to jump on os-js/OS.js-system and try hack there :)

**Comment by andersevenrud** [comment]
To use the system packjages you need to install the `wireless-tools` npm package.. I think I have not noted that anywhere. Just FYI install it in the os.js folder with  `npm install wireless-tools`
