### ISSUE TITLE
Apache container no more supported?

### ISSUE THREAD

**Issue by webmst** [os-js/OS.js#353]
Hi folks,
after the last `git pull`, my working OS.js installation - _running in a apache2.4 container already configured as per instructions_ - is not working anymore.

When trying to access, I get the following message:

`You don't have permission to access / on this server.`

I suppose it is something introduced in the last week.

Any suggestions?

**Comment by andersevenrud** [comment]
Hey!

Try running `grunt dist-files apache-htaccess` to see if that fixes it.

Some files were removed from the dist/ dirs by default, and needs to be generated.

**Comment by webmst** [comment]
Hi Anders,
thank you very much.

`grunt dist-files apache-htaccess` fixed the issue.

You'd better update the documentation accordingly.

**Comment by andersevenrud** [comment]
I just updated https://github.com/os-js/OS.js/blob/master/doc/server-php.md#apache . Thanks!

The `dist-files` task is a part of the default build process, so new users will not suffer from this problem. And just running `grunt` after updating your source is something you should do :)

I'm in the process of making a FAQ on http://community.os.js.org/ , where I will also announce any changes and updated in the coming future. I will also set up mailing lists there, so if you want to get a message when stuff like this happends, make sure to register! :)
