### ISSUE TITLE
https://osjsv2.0o.no/

### ISSUE THREAD

**Issue by AntonDmitrievich** [os-js/OS.js#358]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Strophe.Bosh.prototype._processRequest/sendFunc@https://osjsv2.0o.no/packages/extras/Chat/combined.js:4771:17

```

**Comment by andersevenrud** [comment]
This comes from the Strophe library which is maintained by someone else. I'm pretty sure that it has been fixed it's just that I'm running an old version. Will update!
