### ISSUE TITLE
ApplicationGmail problem to load

### ISSUE THREAD

**Issue by sarsanaee** [os-js/OS.js#359]
An error occurred while trying to launch: ApplicationGmail

> Application 'ApplicationGmail' preloading failed:  /packages/extras/GoogleMail/combined.js

It happened just one time and unfortunately, I couldn't repeat it again.

**Comment by andersevenrud** [comment]
The webserver probably had some problems serving you the file in that instance -- seems to happen once in a while. It could simply have been a connection issue. Thanks for reporting though! :)
