### ISSUE TITLE
[Application/IDE] An unexpected error occured on  application launch

### ISSUE THREAD

**Issue by rodrigoselau** [os-js/OS.js#361]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.10.60:8000/packages/IDE/IDE/window-designer.js
Line: 52:32
Message: TypeError: undefined is not a function (evaluating 'GUI.Helpers.createDroppable')
```

![screenshot from 2016-03-26 11 24 40](https://cloud.githubusercontent.com/assets/5107680/14060509/79fb8256-f345-11e5-81e5-21eead5e1b29.png)

**Comment by andersevenrud** [comment]
It seems that you have an outdated codebase. Do a `git pull` in both the OS.js install and the "developer" packages repo (or download latest zips), then run `grunt`

Ref: in https://github.com/os-js/OS.js/commit/bb71a3bd372a0d1ca654a0f65fd871e0dd5cb05a 

Also, is that Firefox ? Because it does not work there, just FYI.

**Comment by rodrigoselau** [comment]
I do not use firefox, I midori or chrome use downloaded the code yesterday and finished installing today I will try to reinstall

**Comment by rodrigoselau** [comment]
thanks

**Comment by andersevenrud** [comment]
Mindori should work fine since it uses Webkit :)

This change occured *March 23*, so it's kind of weird that you should have this problem if it was downloaded yesterday. You downloaded from Github, right ?

**Comment by rodrigoselau** [comment]
yes

**Comment by rodrigoselau** [comment]
manually install not occur this outdated code problem, very strange happens

**Comment by andersevenrud** [comment]
There is no technical differences between the linux automated installer and when you do it manually, actually. So that is very strange.

But you don't have the problem anymore, right ?

**Comment by rodrigoselau** [comment]
not, the principle is so with this application which I thought was very strange not to the declared function error as shown in the picture

**Comment by andersevenrud** [comment]
Sorry, but I do not understand what you wrote there.

Was it a "no" ?

**Comment by rodrigoselau** [comment]
sorry i'm from brazil and don't write inglish very well, but my only problem with this application is that

**Comment by andersevenrud** [comment]
If you still have this error, then your codebase is simply not up-to-date. This change was made earlier this week and the IDE was updated at the same time.

I am not able to replicate this on my own computer(s), so the problem must be on your end. I actually just tried to set up a clean VM, run the installer (and manually) to test this -- and dit not have any problems at all.

**Comment by rodrigoselau** [comment]
ok, thanks this is now it works, but now mysql handler this with the following error "Uncaught RangeError: Maximum call stack size exceeded", have any idea what it is?

**Comment by andersevenrud** [comment]
If you update your codebase again this issue should be resolved :)

**Comment by rodrigoselau** [comment]
ok, thanks ;)
