### ISSUE TITLE
[Applications] Applications created with the IDE can not be opened twice

### ISSUE THREAD

**Issue by pringles49** [os-js/OS.js#366]
Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
Error: No VFS Module matches FS/get/home:///.packages/MyProject/main.js. Wrong path or format ?
    at request (http://localhost:8000/osjs.js:9802:13)
    at Object.OSjs.VFS.url (http://localhost:8000/osjs.js:10328:5)
    at http://localhost:8000/osjs.js:1876:22
    at Array.map (native)
    at getPreloads (http://localhost:8000/osjs.js:1874:27)
    at launch http://localhost:8000/osjs.js:2003:21)
    at Object.doLaunchProcess [as launch] (http://localhost:8000/osjs.js:2020:12)
    at HTMLElement.<anonymous> (http://localhost:8000/packages/default/CoreWM/combined.js:134:13)
    at HTMLElement.cbNormal (http://localhost:8000/osjs.js:1197:20)
```
> I closed the app  and when trying to open the app  this message appeared ^^ 
> info : the application is completely blank "Default"
> Solution : I have to refresh the page to Reopen the applications 
>  Sorry for my english

`closing app`
![sans_ti_34_tre](https://cloud.githubusercontent.com/assets/18288140/14410433/bd095474-ff2f-11e5-89b5-8412ecfeeed2.jpg)
`opening app`
![sans_titre](https://cloud.githubusercontent.com/assets/18288140/14410500/49c85990-ff31-11e5-89a5-27412743367e.jpg)

`the message appear`
![4](https://cloud.githubusercontent.com/assets/18288140/14410466/beb9bd08-ff30-11e5-8ec5-e308fdf2a551.jpeg)

**Comment by andersevenrud** [comment]
Thanks!

Confirmed -- looking into it :)

**Comment by andersevenrud** [comment]
Allright mr. @pringles49. This issue has been resolved :)
