### ISSUE TITLE
Cannot save a text file to the VFS

### ISSUE THREAD

**Issue by davidpaulrosser** [os-js/OS.js#367]
## Expected behaviour

1. Open textpad
2. Enter some text
3. Save file to /User
4. File saved

## Actual behaviour

1. Open textpad
2. Enter some text
3. Save file to /User
4. File Dialog error: You need to select a file or enter new filename!

## Steps to reproduce the error

1. Open textpad
2. Enter some text
3. Save file to /User
4. File Dialog error: You need to select a file or enter new filename!

## (Optinal) Browser and OS information

Chrome 49, OS X El Capitan

**Comment by andersevenrud** [comment]
This was an uncaught bug (false-positive error) after a refactor I did recently. Oops!

Thanks! :)
