### ISSUE TITLE
[VFS] Add localStorage for files

### ISSUE THREAD

**Issue by davidpaulrosser** [os-js/OS.js#368]
It would be great to have the option to save basic file types such as .txt, base64 encoded images to localStorage without the need for a server.

---

- [x] `scandir()` - Scanning FS directory
- [x] `read()` - Reading FS file
- [x] `write()` - Writing FS file
- [x] `unlink()` - Removing FS file
- [x] `url()` - Reading files via browser
- [x] `upload()` - Upload browser files
- [x] `move()` - Move VFS items
- [x] `move()` - Rename VFS items
- [x] `copy()` - Copy VFS items
- [x] `mkdir()` - Create VFS directory
- [x] `freeSpace()` - Check free space
- [ ] QA

**Comment by andersevenrud** [comment]
I've made some progress on this today. Made a filesystem model that fits into `localStorage` and started wirting a mountpoint (transport module) for VFS.

I can probably look into compression for this to be able to maximize sotrage space. Chrome only supports 5M per domain. For text this is no problem, but once you start adding images it will fill up quickly.

This gave me a chance to implement a "free space checker" as well to mountpoints (if they have that functionality enabled), to prevent writing to a full disk/location.

**Comment by davidpaulrosser** [comment]
This is great news Anders, keep me updated on the progress!

**Comment by andersevenrud** [comment]
Didn't get much time to continue on this, but I've successfully implemented `scandir` and `read` and `write`, so not long until this is done :)

**Comment by andersevenrud** [comment]
@davidpaulrosser I took some time to go over this again today and made some improvements. While doing this I nailed a couple of things in place as well. I've added a TODO in the description of this issue :)

**Comment by andersevenrud** [comment]
@davidpaulrosser I had some more time to look into this, and it is pretty much complete. I just have to do some extensive testing, finishing a last few minor things  :)

**Comment by davidpaulrosser** [comment]
Hey Anders, great to hear your making progress on this. We will be sending you an email later today with more information on how to integrate this into our repository. How can I find you on slack?

**Comment by andersevenrud** [comment]
Looks like I am only 2 bugs away from completion on this one :)

**Comment by andersevenrud** [comment]
I will close this issue now since it has been implemented. @davidpaulrosser Feel free to comment here still; if you have any issues.

**For anyone else reading this:** if you want to use this yourself, contact me and I will put it up on gist or github.
