### ISSUE TITLE
[Applications] Experimental Webtorrent

### ISSUE THREAD

**Issue by rbarros** [os-js/OS.js#374]
Hi! I love this project!
I am creating an experimental application using the API webtorrent and based on Transmission.

![screenshot_2016-04-21_22-43-57](https://cloud.githubusercontent.com/assets/940328/14729826/87492bd4-0817-11e6-9f42-eb90f43f998c.png)

**Comment by junland** [comment]
Nice!

**Comment by andersevenrud** [comment]
Really cool! This is something I actually wanted to do, but never found any time :)

You can use the ListView here to list all your active downloads.


Keep me updated on this!

**Comment by rbarros** [comment]
Thanks for the feedback, I will proceed with the project.

**Comment by vlotho** [comment]
the code is available?

**Comment by rbarros** [comment]
[instant.io](https://github.com/feross/instant.io)
[webtorrent](https://github.com/feross/webtorrent)

**Comment by andersevenrud** [comment]
Since this is not a project relating to this repository; I'm going to close this issue.

You can of course resume conversations here, but it will remain closed. I'd suggest opening a thread on http://community.os.js.org/ so we can have an open discussion about it on a forum suited for it :)
