### ISSUE TITLE
Failed preloading

### ISSUE THREAD

**Issue by BartManX** [os-js/OS.js#376]
An error occured while trying to launch: ApplicationMusicPlayer

> Application 'ApplicationMusicPlayer' preloading failed:  /packages/default/MusicPlayer/locales.js

**Comment by andersevenrud** [comment]
Either:

1. You are running in production mode and have not built packages
2. There was a problem in transfering the file, which is normal. Just retry
3. The file is physically missing

**Comment by andersevenrud** [comment]
I'm closing this issue, because there are no problems with this currently.

Feel free to reopen if you're still having issues
