### ISSUE TITLE
sandstorm.io for installing?

### ISSUE THREAD

**Issue by davelab6** [os-js/OS.js#379]
## Expected behaviour

It is easy to upload and install new web apps to os.js

## Actual behaviour

https://os.js.org/#install says, 

> Easily add new applications by simply downloading a repository online and copy it into your installation (some samples include a XMPP chat client, PDF Viewer, ZIP Archiver and Games).

But this assumes the user has access to the web server file system.

https://sandstorm.io might be a way to meet my expectation :)

**Comment by andersevenrud** [comment]
@davelab6 There is also user-installable applications (via zip files). It is not very visible in the client yet, because I am currently working on (with some other people) the "store" features. When this is done you can simply drag-and-drop or search for apps to install!

**Comment by andersevenrud** [comment]
To me, most of these sandstorm apps looks like kind of Iframe stuff. But I am on my way to bed... have to investegate more tomorrow! Thanks!

**Comment by davelab6** [comment]
sandstorm is super secure, in way I (kindly :) expect your ZIP files will
not be :)

**Comment by andersevenrud** [comment]
Well, everything will be stored securely on my server, and any submission will go through a validation and approval process. At least if they are submitted into the official repositories.

**Comment by andersevenrud** [comment]
Also, zip-files is only one of the methods to install applications.I just used it as an example -- anything would work,

**Comment by davelab6** [comment]
Sure but isn't the idea that small groups (eg, families) can run their own
personal cloud with OS.js as their UI? And then some daft uncle gets a
malware app... ay ay ay :)

**Comment by andersevenrud** [comment]
Well, this is the whole purpose behind the "store" and the validation/approval process though -- if you manually install something with malware on it, then it's not much I can do about it -- right ?

**Comment by andersevenrud** [comment]
I will have to get back to you tomorrow. It's pretty late here and I have not had any time to really look into what you're suggesting

**Comment by andersevenrud** [comment]
@davelab6 I've been looking a bit more into this and starting to understand how it all works. It's very interesting, for sure!

But at this time I sadly do not have any time to look more into it. I am completely swamped with work.

I will look into it later though. Thanks for bringing it to my attention :)

Closing the issue, but made a note in my [private] issue tracker.

**Comment by andersevenrud** [comment]
I'll reopen the issue when I have some time. I'll probably have a few questions ;)

**Comment by davelab6** [comment]
Glad to help :) I am watching the project, its very exciting!! :) I encourage you to think about how you can offer a user subscription to fund development (similar to patreon) such that you can quit your employee job and focus on making free software full time :) 

https://modelviewculture.com/pieces/funding-in-depth-our-subscription-model has some good stuff on this.

**Comment by andersevenrud** [comment]
@davelab6 Yeah, it'd be great to be able to spend all my time working on free software. I actually have a couple of things going in my spare-time related to OS.js that pays off, and if it continues at a steady rate, I will seriously consider doing something like that :) The thing is; I do this alone, and PR is not exactly my thing... I should probaby look for someone to help me with these kinds of things.

Thanks!

**Comment by davelab6** [comment]
PR is easy, just advertise your patreon in the README, homepage, and app :)

**Comment by andersevenrud** [comment]
@davelab6 I already have that, but only as a badge. I should make up some text :)

**Comment by davelab6** [comment]
BTW jsbin.com is a nice example of the same - 100% free software on github, paid subscription service :)
