### ISSUE TITLE
[CoreWM] Window resizing issue

### ISSUE THREAD

**Issue by VRspace4** [os-js/OS.js#380]
## Expected behaviour

When resizing a window to the smallest size, the opposite edge or corner should anchor and stay fixed. This issue only occurs when resizing from either the left or top edges but not the right or bottom edges.

## Actual behaviour
As soon as the window is sized to the smallest constrained size, the entire window starts to move.

## Steps to reproduce the error
1. Hover mouse over either the left or top edge of the window
2. Click and drag to resize the window to the smallest size.

## (Optinal) Browser and OS information
Chrome, Windows 10

**Comment by andersevenrud** [comment]
I thought I fixed this some time ago.... maybe it's on my work laptop that I use when commuting, and it never got commited. Will have to check! Thanks :)

**Comment by andersevenrud** [comment]
This should no longer be a problem :)

**Comment by andersevenrud** [comment]
I've also made some general improvements to the resize handler :)
