### ISSUE TITLE
[Core] Search Engine

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#385]
You could there be a search field, which would find files or applications locally in the file system ?
developed in ajax, which would display the results list when the user completed the search field.

---

- [x] PanelItem implementation
- [x] Core SearchEngine class
- [x] Make a module spec
- [x] Application search
- [x] Filesystem search
- [x] Keyboard handling for search results
- [x] Keyboard shortcut for opening search
- [x] The search dialog should handle like a overlay (toggleable)
- [x] Theme support
- [x] Configurable VFS searches
- [x] SearchEngine entry in Settings app
- [x] PanelItem configuration dialog
- [ ] Implement into FileManager
- [x] Option for setting max number of results
- [x] Add 'searchable' attributes to VFS modules
- [x] PHP Method
- [x] Prevent adding conflicting directories
- [x] Add 'recursive' option to VFS method

**Comment by andersevenrud** [comment]
Yeah, this is a good idea. I'll look into it :)

**Comment by andersevenrud** [comment]
All progress on this will be commited into https://github.com/os-js/OS.js/compare/search-engine

**Comment by andersevenrud** [comment]
@vlotho Thanks for initiating this :)

I am closing this issue now and any maintainance or unfinished stuff will be in #304.
