### ISSUE TITLE
Storage Manager with RAID function

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#386]
add the ability to manage system disks (partitioning, formatting, type raid, disk synchronization, alarms, manufacturer information, ...) as an application or a tab in the settings.
https://translate.google.fr/translate?sl=fr&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=https%3A%2F%2Fdoc.ubuntu-fr.org%2Fraid_logiciel&edit-text=&act=url
https://github.com/nicolargo/pymdstat

**Comment by andersevenrud** [comment]
This should be posted in https://github.com/os-js/OS.js-system.

But mdadm is de-facto standard for managing volumes in Linux, so this is what would have to be used in some form.

It's just a matter of making shellscripts that wraps the commands and execute it via the node server. 

But yeah, this is probably something that comes down the line.
