### ISSUE TITLE
No ace??

### ISSUE THREAD

**Issue by XtremePlayzCODE** [os-js/OS.js#388]
When you install osjs, theres no ace, any explination?

**Comment by andersevenrud** [comment]
You have to install it via another repository. You can find it under the
organization page for OS.js on github, or the documentation.

Den fredag 6. mai 2016 skrev XtremePlayzCODE <notifications@github.com>
følgende:

> When you install osjs, theres no ace, any explination?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/os-js/OS.js/issues/388>
>


-- 

Anders F. Evenrud
Software Developer

Blog: http://tinyurl.com/cjfrfx8

**Comment by XtremePlayzCODE** [comment]
Ok, but if I put them in, would it just detect them and have those be displayed or do I have to edit something?

**Comment by andersevenrud** [comment]
Instructions are linked from all repositories. Just see link in README

https://github.com/os-js/OS.js-extras
