### ISSUE TITLE
When Connecting To Chat, I get this:

### ISSUE THREAD

**Issue by ashtell** [os-js/OS.js#389]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Error: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.
    at Error (native)
    at sendFunc (https://osjsv2.0o.no/packages/extras/Chat/combined.js:4771:25)
```

**Comment by andersevenrud** [comment]
This is not a problem with OS.js itself, but with the chat server it is running on.

I will look more into this, but i guess it is just because of my demo server. It might be outdated or have some problems now and then because of heavy traffic.
