### ISSUE TITLE
Suggestion:  OS.js Native Desktop Environment

### ISSUE THREAD

**Issue by Technohacker** [os-js/OS.js#390]
Hey team,
First of all, love this project! I actually had this kind of idea before but now that I've found this, I guess I'll try to help :)

Now, as for my suggestion, I was thinking of making a Desktop Environment out of this project (as per my initial idea). AFAIK, I think a web browser running full-screen and light on resources might do the job well :)

Keep me posted!

**Comment by andersevenrud** [comment]
Hello. 

>  I was thinking of making a Desktop Environment out of this project 

Well, that is what OS.js is :) To quote the tagline:

> OS.js is a JavaScript web desktop implementation for your browser with a fully-fledged window manager, Application APIs, GUI toolkits and filesystem abstraction.

Or am I musunderstanding something here ?

**Comment by Technohacker** [comment]
Damn..... that's a fast reply! :D
Sorry, I think I worded my suggestion a bit wrongly.... basically I meant making a fullscreen web browser shell so that the OS.js UI can be started natively.
Thanks!

**Comment by andersevenrud** [comment]
You can already do that using NW.js, which is supported :)

You can get test builds from https://builds.os.js.org/nw/ , but these are a bit outdated.

**Comment by andersevenrud** [comment]
You can make it run natively by basically using any form of libwebkit solution (or a `<webview>`).

I hope this answers your question; and that I understood you correctly

**Comment by Technohacker** [comment]
Hmm....... I really am outdated I guess...... thanks again :D
