### ISSUE TITLE
[Arduino] Package Manager error messages (TypeError)

### ISSUE THREAD

**Issue by rei-vilo** [os-js/OS.js#391]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://mytian.local/packages/target/ArduinoPackageManager/combined.js?38273
Line: 282:28
Message: TypeError: undefined is not an object (evaluating 'stdout.replace')
```

**Comment by andersevenrud** [comment]
Can you see what version you are running ?

`OSjs.API.getConfig('Version')`  in the javascript console

**Comment by rei-vilo** [comment]
I've installed `node.js` to get the version but it doesn't seem to work.

>
**root@myTian:~#** node
> OSjs.API.getConfig('Version')
ReferenceError: OSjs is not defined
    at repl:1:2
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
> 

Is there a text file to `cat`?

Otherwise, 

<img width="372" alt="capture 2016-05-11 a 13 01 21" src="https://cloud.githubusercontent.com/assets/951776/15179580/09d0df38-177d-11e6-81e2-8572ef809c24.png">

**Comment by andersevenrud** [comment]
I was thinking in your browser console, but I see the version number in the screenshot. Thanks

**Comment by rei-vilo** [comment]
You're welcome!

On Chrome console, 

     > OSjs.API.getConfig('Version') 
     < "2.0.1-arduino-os"

**Comment by sergiotomasello** [comment]
@rei-vilo which version of Linino OS?: please run this command in your tian console:
```shell
uname -a
```

**Comment by rei-vilo** [comment]
Here's the answer:

># uname -a
> Linux myTian 3.18.11 #4 Wed Jan 20 16:54:22 CET 2016 mips GNU/Linux

**Comment by andersevenrud** [comment]
Relevant: #392

**Comment by andersevenrud** [comment]
This seems to be an asynchronous issue when window has become detached. I have a solution for this which I will make this weekend

**Comment by rei-vilo** [comment]
Thank you!

**Comment by andersevenrud** [comment]
I've made a fix for this issue, and it will be submitted to the Arduino Team ASAP

**Comment by rei-vilo** [comment]
Thank you very much!
