### ISSUE TITLE
Arduino.ORG Tian  — opkg install node 

### ISSUE THREAD

**Issue by rei-vilo** [os-js/OS.js#392]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.1.28/packages/target/ArduinoPackageManager/combined.js?51053
Line: 143:35
Message: TypeError: null is not an object (evaluating 'this._scheme.find')
```

**Comment by rei-vilo** [comment]
Versions

* OSjs.API.getConfig('Version') = "2.0.1-arduino-os"
* uname -a = Linux myTian 3.18.11 #4 Wed Jan 20 16:54:22 CET 2016 mips GNU/Linux

**Comment by andersevenrud** [comment]
This is related to #391
