### ISSUE TITLE
error opening settings

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#398]
Une erreur est survenue lors du lancement de : ApplicationSettings

> Application 'ApplicationSettings' preloading failed:  /packages/default/Settings/main.js,/packages/default/Settings/locale.js

**Comment by vlotho** [comment]
I could not reproduce the error, how's that?

**Comment by andersevenrud** [comment]
Can happen for many reasons. Most likely:

- You changed the code files or configuration and did not restart server
- Transportation error (network failure)
- Browser failed to load resource (network failure or corrupt/invalid cache)
