### ISSUE TITLE
error opening settings

### ISSUE THREAD

**Issue by vlotho** [os-js/OS.js#399]
apparently there is an error every time I do a search, and then I try to open the settings.

Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.  Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

```
TypeError: Cannot read property 'querySelector' of null
    at UIScheme.getFragment (http://localhost:8000/client/javascript/gui/_scheme.js:275:30)
    at UIScheme.parse (http://localhost:8000/client/javascript/gui/_scheme.js:296:24)
    at UIScheme.render (http://localhost:8000/client/javascript/gui/_scheme.js:359:24)
    at ApplicationSettingsWindow.init (http://localhost:8000/packages/default/Settings/main.js:135:12)
    at Process.WindowManager.addWindow (http://localhost:8000/client/javascript/windowmanager.js:536:7)
    at Process.Application._addWindow (http://localhost:8000/client/javascript/application.js:232:12)
    at http://localhost:8000/packages/default/Settings/main.js:737:12
    at Object.Utils.ajax.onerror (http://localhost:8000/client/javascript/gui/_scheme.js:255:9)
    at XMLHttpRequest.onReadyStateChange (http://localhost:8000/client/javascript/utils/xhr.js:109:16)
```

**Comment by andersevenrud** [comment]
Check your network log. Seems like it failed to load the scheme file

> at Object.Utils.ajax.onerror

**Comment by vlotho** [comment]
2016-05-15T13:11:08.499Z <<< /packages/default/Settings/scheme.html
2016-05-15T13:11:08.500Z >>> 500 text/plain string

**Comment by andersevenrud** [comment]
See browser network log for more info

**Comment by vlotho** [comment]
I have an "anti adblock killer" that can be a problem?

**Comment by vlotho** [comment]
ERR_VFSMODULE_FIND_FMT

**Comment by andersevenrud** [comment]
I'd advice against using any ad-related extensions together with OS.js.

> ERR_VFSMODULE_FIND_FMT

I just added a locale for this.


Did you look at the browser network log ? It should give you an error message

**Comment by vlotho** [comment]
where can I find the log exactly?

**Comment by andersevenrud** [comment]
![untitled](https://cloud.githubusercontent.com/assets/161548/15274499/9071b90c-1ab3-11e6-947d-fa514fc1dbaf.png)

in the browser developer tools

**Comment by vlotho** [comment]
there is nothing special in the network tab

**Comment by andersevenrud** [comment]
The server reported a 500 error, so it should be in there. Find the scheme.html file that was loaded for Settings and look at the response

**Comment by vlotho** [comment]
scheme.html	500	xhr	xhr.js:197	259 B	64 ms

**Comment by andersevenrud** [comment]
Click on it and inspect the response

**Comment by vlotho** [comment]
You have no OS.js Session, please log in!

**Comment by andersevenrud** [comment]
That means you restarted the server and not your client. You lost your session because of this

**Comment by vlotho** [comment]
no, I do it all the time. if I disconnect with the customer, I reboot my page, I open my settings, all goes well. if I search and I open immediately after the settings, it crashes.

**Comment by andersevenrud** [comment]
I am unable to reproduce this.

The server crashes ?

**Comment by vlotho** [comment]
no, not a crash, it just shows me the bug. but it appears to me all the time. Search is on a bogus word, kind toto

**Comment by andersevenrud** [comment]
See the network log on what happes when it does the `find` (XHR) request

**Comment by vlotho** [comment]
just before there is a "find" with "{" error ": {" code ":" MODULE_NOT_FOUND "}}"

**Comment by andersevenrud** [comment]
I think you might be missing the library used by find function. `npm install`

**Comment by vlotho** [comment]
I installed find, but I have another error now.

[localhost-1463322062714.txt](https://github.com/os-js/OS.js/files/265024/localhost-1463322062714.txt)

**Comment by andersevenrud** [comment]
Looks like the same error to me.

> UIScheme::load() packages/default/Settings/scheme.html
> Utils::ajax() Object
> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by vlotho** [comment]
I always have the same answer on the "bottom" but I have an error with "main.js" but nothing in "response"

**Comment by andersevenrud** [comment]
I am unable to reproduce this error, even with the mysql handler.

Make sure to:
- Use the correct branch `search-engine`
- Do a `git pull` to ensure you have latest code
- Run `npm install` to update dependencies
- Run `grunt` to rebuild OS.js and all configuration files
- Restart your server
- Restart your client

**Comment by vlotho** [comment]
it's good, it's solved. there were "updates" on git remote as well as on the npm. earlier I'm just a "npm install find".
