### ISSUE TITLE
TextPad mimetypes

### ISSUE THREAD

**Issue by muldy** [os-js/OS.js#401]
I'm trying to make TextPad open more mime types...

Tried adding to dist/packages/default/Textpad/metadata.json
application/x-shellscript (.sh files)
and 
application/octet-stream (.ini files?)

to "mime": [
    "^text",
    "inode\\/x\\-empty",
    "application\\/x\\-empty",
    "application\\/x\\-lua",
    "application\\/x\\-python",
    "application\\/javascript",
    "application\\/json",
    "application\\/octet\\-stream",
   "application\\/x\-shellscript"
  ], 

But with no success, is there something I'm missing?

Thanks.

**Comment by andersevenrud** [comment]
You also need to add the mimes to the base system config (see `src/conf/130-mime.json`) to to make OS.js regognize them :)

(Run `grunt config` afterwards)
