### ISSUE TITLE
Launching CodeMirror from Arduino Tian on Arduino OS 2.0.1 

### ISSUE THREAD

**Issue by rei-vilo** [os-js/OS.js#408]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://mytian.local/osjs.js
Line: 11011:17
Message: TypeError: onLoaded is not a function. (In 'onLoaded(scheme, file)', 'onLoaded' is undefined)
```

**Comment by andersevenrud** [comment]
I am unable to replicate this.

FYI: Latest version is 2.0.3. You should do an `opkg update` and `opkg upgrade arduinoos`

**Comment by andersevenrud** [comment]
Please update and see if that helps out. If not re-open this issue

**Comment by andersevenrud** [comment]
OK :) No problem
