### ISSUE TITLE
Error with Chat on my own server

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/OS.js#413]
An error occured while trying to launch: ApplicationChat

> Application 'ApplicationChat' construct failed: ReferenceError: Strophe is not defined

```
StropheConnection@http://localhost:8000/packages/extras/Chat/combined.js:76:5
ApplicationChat@http://localhost:8000/packages/extras/Chat/combined.js:841:23
_createProcess@http://localhost:8000/osjs.js:2163:20
doLaunchProcess/</<@http://localhost:8000/osjs.js:2210:15
_preload/</<@http://localhost:8000/osjs.js:2133:13

```

**Comment by andersevenrud** [comment]
You did not follow instructions completetely. You're missing a dependency named 'Strophe'

**Comment by SpaceboyRoss01** [comment]
How do I install it?

**Comment by andersevenrud** [comment]
Make sure to follow: https://os.js.org/doc/manuals/man-package-manager.html

Then look at https://github.com/os-js/OS.js-extras/blob/master/Chat/README.md
