### ISSUE TITLE
The calendar was just installed!

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/OS.js#415]
An error occured while trying to launch: ApplicationCalendar

> Application 'ApplicationCalendar' preloading failed:  /packages/submissions/Calendar/combined.js

**Comment by andersevenrud** [comment]
Duplicate of #417

**Comment by SpaceboyRoss01** [comment]
This only happens on Firefox.

**Comment by andersevenrud** [comment]
Unable to reproduce :/

Maybe you have some plugins/extensions that prevents the files from loading properly
