### ISSUE TITLE
An unexpected bug

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/OS.js#418]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Strophe.serialize@https://family-os-js-spaceboyross.c9users.io/packages/extras/Chat/combined.js:1540:13
Strophe.Request.prototype.getResponse@https://family-os-js-spaceboyross.c9users.io/packages/extras/Chat/combined.js:4112:1
Strophe.Bosh.prototype._reqToData@https://family-os-js-spaceboyross.c9users.io/packages/extras/Chat/combined.js:4860:20
Strophe.Connection.prototype._connect_cb@https://family-os-js-spaceboyross.c9users.io/packages/extras/Chat/combined.js:3074:24
Strophe.Bosh.prototype._onRequestStateChange@https://family-os-js-spaceboyross.c9users.io/packages/extras/Chat/combined.js:4657:17

```
This was properly installed

**Comment by andersevenrud** [comment]
Seems to be an issue with the Strophe library. I'll investegate

**Comment by andersevenrud** [comment]
I can't seem to replicate this error :/ There's been some updates to the dependencies recently, so it might have fixed the issue.

If you still have this issue or can show me how to trigger this behaviour, please re-open this issue.
