### ISSUE TITLE
App doesn't stay maximized when browser size is changed

### ISSUE THREAD

**Issue by VRspace4** [os-js/OS.js#421]
## Expected behaviour
When the browser's window size is changed, the maximized app should stay maximized.

## Actual behaviour
Upon browser resize, the app restores its state.

**Comment by andersevenrud** [comment]
You can disable this behaviour by setting `moveOnResize` to `false` (CoreWM setting) :)

**Comment by andersevenrud** [comment]
Oh, but they do not follow the size of the browser. Is that something you'd want ?
