### ISSUE TITLE
[VFS] Weird behaviour moving/renaming a file to a directory that doesn't exist yet (LS)

### ISSUE THREAD

**Issue by mcky** [os-js/OS.js#424]
## Expected behaviour
When moving a folder via `VFS.{rename,move}` to a folder that doesn't exist, I would expect either:
* The operation to throw an error
* The directory to be created via mkdir etc

## Actual behaviour
The file is moved but the folder doesn't appear. Navigating to the folder via the address bar works. Refreshing the FS via `view -> refresh` doesn't show it.

## Steps to reproduce the error
* Move the file to a folder that _does not_ exist (`OSjs.VFS.move('documents:///file.jpg', 'documents:///mydir/file.jpg', function() {})`)
* See the folder doesn't appear in filemanager or `VFS.scandir` for `documents:///`
* See the file does appear if you call scandir on or navigate to `documents:///mydir`

**Comment by mcky** [comment]
Also creating a directory with the same name as the invisible one overwrites the contents without warning.
Eg:
* scandir(mydir), see it contains file
* make folder in FileManager
* scandir(mydir), see it's now empty (apart from `...`)

**Comment by andersevenrud** [comment]
Woh. Another bug in the LS module :) I'll fix this asap

**Comment by andersevenrud** [comment]
https://gist.github.com/andersevenrud/09f198b9f55cbf8e434341f4388844dd

* Now throws error when you try to move/copy to a destination that does not exist
* mkdir() no longer overwrites existing directories if found
