### ISSUE TITLE
Error from OS-js demo

### ISSUE THREAD

**Issue by XtremePlayzCODE** [os-js/OS.js#426]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Error: Failed to execute 'send' on 'XMLHttpRequest': The object's state must be OPENED.
    at Error (native)
    at sendFunc (https://osjsv2.0o.no/packages/extras/Chat/combined.js:4771:25)
```

**Comment by andersevenrud** [comment]
Duplicate of #418
