### ISSUE TITLE
i think i've closed too fast the archive app - file: /OS.js-v2-minimal-nightly.zip

### ISSUE THREAD

**Issue by antcolag** [os-js/OS.js#430]
Si è verificato un errore inaspettato, forse un bug.

> Per piacere, fai un report se pensi che questo sia un bug.  Includi una breve descrizione di come l'errore si è verificato, se possibile come replicarlo.

```
TypeError: Cannot read property 'find' of null
    at ApplicationArchiverWindow.renderArchive (https://osjsv2.0o.no/packages/extras/Archiver/combined.js:165:28)
    at https://osjsv2.0o.no/packages/extras/Archiver/combined.js:325:17
    at https://osjsv2.0o.no/osjs.js:14355:9
    at https://osjsv2.0o.no/osjs.js:14244:9
    at https://osjsv2.0o.no/vendor/zip.js/WebContent/zip.js:621:7
    at FileReader.reader.onload (https://osjsv2.0o.no/vendor/zip.js/WebContent/zip.js:173:5)
```

**Comment by andersevenrud** [comment]
This was fixed in https://github.com/os-js/OS.js-extras/commit/5ce51e9cf7a2ab1d7d378239a16b2e9b5130dab7.

Thanks for reporting :)

PS: The demo server has not been updated. It's scheduled next weekend!
