### ISSUE TITLE
could not install apps

### ISSUE THREAD

**Issue by Elmapul** [os-js/OS.js#433]
following this instructions:
https://os.js.org/doc/manuals/man-package-manager.html

Um erro ocorreu na tentativa de abrir: ApplicationAceEditor

> O aplicativo 'ApplicationAceEditor' falhou no pré-carregamento:  /packages/OS.js-extras/AceEditor/combined.js

**Comment by andersevenrud** [comment]
Run `grunt packages`

**Comment by andersevenrud** [comment]
I'm closing this issue because I assume it's not a problem anymore. The error you got is usually because of unbuilt packages, which the command I gave should resolve.

If you still have issues, feel free to re-open this thread :)
