### ISSUE TITLE
[Arduino Tian] Error parsing package manager results

### ISSUE THREAD

**Issue by graffiti4u** [os-js/OS.js#438]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'replace' of undefined
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?55940:288:28
    at http://arduino.local/packages/target/ArduinoPackageManager/combined.js?55940:260:14
    at _Handler.<anonymous> (http://arduino.local/osjs.js:1756:7)
    at Object.onerror (http://arduino.local/osjs.js:9466:17)
    at XMLHttpRequest.onReadyStateChange (http://arduino.local/osjs.js:1266:16)
```

**Comment by andersevenrud** [comment]
Pretty sure this has something to do with #436 because this error occurs where the PackageManager looks at the response from the webserver.

Will investegate deeper

**Comment by andersevenrud** [comment]
This has been solved on my side and submitted to the Arduino team so that it comes in the next official update.

Ref: https://github.com/arduino-org/Arduino-OS/pull/22

**Comment by andersevenrud** [comment]
Closing this issue in favour of the PR https://github.com/arduino-org/Arduino-OS/pull/23
