### ISSUE TITLE
Shortcut clicked event problem

### ISSUE THREAD

**Issue by ht68** [os-js/OS.js#446]
Ater fetch new update [2.0alpha78]  Shortcut clicked event not working :disappointed:

**Comment by ht68** [comment]
also demo version contain this problem https://osjsv2.0o.no/

**Comment by andersevenrud** [comment]
Seems to stem from 33c573a91173e6ab7efeca665a793f6dafc55bc2. Fixing

**Comment by andersevenrud** [comment]
Should be fixed now :)

**Comment by ht68** [comment]
thanks :rose: :blush:
