### ISSUE TITLE
[Arduino Tian] ArduinoProcessViewer throws errors in some cases

### ISSUE THREAD

**Issue by rpehlm** [os-js/OS.js#447]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'PID' of null
    at https://colette.local/packages/target/ArduinoProcessViewer/combined.js:83:23
    at Array.forEach (native)
    at https://colette.local/packages/target/ArduinoProcessViewer/combined.js:81:26
    at _Handler.<anonymous> (https://colette.local/packages/target/ArduinoProcessViewer/combined.js:64:16)
    at _Handler.<anonymous> (https://colette.local/osjs.js:1631:11)
    at Object.onsuccess (https://colette.local/osjs.js:8703:21)
    at XMLHttpRequest.onReadyStateChange (https://colette.local/osjs.js:1143:16)
```

**Comment by rpehlm** [comment]
- Received new Tian
- Configured (name, password and WiFi)
- Rebooted
- Prowled around in Arudino O/S a bit (just seeing what was there)
- Started Luci
- Looked at a few things
- Had the Kernel log page selected
- Was working on another computer when the error occurred.
That's about as much info as I can give you.
Any questions, please ask.

**Comment by andersevenrud** [comment]
Hi!

Thanks for reporting. I've fixed the issue on my side and will submit the patch to the Arduino team so the fix comes with the next update.

**Comment by andersevenrud** [comment]
Ref: https://github.com/arduino-org/Arduino-OS/pull/22

**Comment by rpehlm** [comment]
No problem.  Good to know it got fixed.
Just let me know if there is anything you want me to try.
Part-time software tester :)
Actually a retired IT Manager that always needs something extra to keep 
occupied.

Robin Lauryssen-Mitchell

**Comment by andersevenrud** [comment]
Always looking for people to help out. Having more eyes on this really makes a difference!

There's lots of stuff going on in the master branch of this project, so if you want to do some testing you probably want to start there (the arduino branch is a custom build of the master, so they are pretty much identical except it is a bit older, so any problems uncovered is probably already been solved regarding the "core" of OS.js). Basically set up an instance on your computer and go bug hunting :)

Feel free to join the community pages to start conversations about your findings or whatever else you have in mind:

- Chat: https://gitter.im/os-js/OS.js (with several channels and PM support)
- Forums: http://community.os.js.org/

**Comment by sergiotomasello** [comment]
@andersevenrud @rpehlm thank you guys! I will introduce the *bug-fixing* pull request asap

**Comment by andersevenrud** [comment]
Closing this issue in favour of the PR https://github.com/arduino-org/Arduino-OS/pull/23
