### ISSUE TITLE
Formatting buttons in writer un-focus the text input

### ISSUE THREAD

**Issue by mcky** [os-js/OS.js#454]
## Expected behaviour
When you hit a formatting button (italics, strikethrough etc) you'd expect to continue typing without having to re-focus the field

## Actual behaviour
You have to click (or tab) back into the field to continue typing

## Steps to reproduce the error
1) Type some text into the text field
2) Hit a button to format the text
3) Continue typing, notice no input is captured

## (Optinal) Browser and OS information
Tested in chrome, safari and firefox on OSX

You'd probably wanna cache the cursor position too, as just calling `focus()` on the input would probably take you to the end?

**Comment by RyanRiffle** [comment]
IIRC most browsers ignore focus if you `evt.preventDefault()` the `mousedown` event. If that doesn't work, it's been a while since I have worked on a web based application, couldn't you just `preventDefault` on the `focus` event?

**Comment by andersevenrud** [comment]
Thanks mr @RyanRiffle :) Worked like a charm!

**Comment by RyanRiffle** [comment]
No problem
