### ISSUE TITLE
The calculator app brings up the iOS/android keyboards on any button click

### ISSUE THREAD

**Issue by mcky** [os-js/OS.js#456]
## Expected behaviour
When inputting a number or symbol you would expect it to either work with the keyboard open (input `type="number"` and not obscuring) or to not open the keyboard at all

## Actual behaviour
The keyboard obscures the buttons and needs closing, only to re-appear on the next number you input and the field is focused again

## Steps to reproduce the error
Open the calculator app and use any buttons

## (Optinal) Browser and OS information
iOS, but believe QA caught this on android too

Screenshot of the keyboard covering the content:
![2016-07-27 11 32 40](https://cloud.githubusercontent.com/assets/2717635/17172751/a78ab35e-53ee-11e6-8896-72f57d1b769e.png)

**Comment by andersevenrud** [comment]
Merged this together with #455. Probably more issues to be noted
