### ISSUE TITLE
[Handler] Default groups for PAM authentication 

### ISSUE THREAD

**Issue by xy0** [os-js/OS.js#464]
In a domain environment, there could be many users capable of logging in using the PAM handler. When new users are added, instead of using a script to append the new user to **/etc/osjs/groups.json**, implement a **defaultGroups** property within the handler config. 

see: https://github.com/xy0/OS.js/commit/7b562e28c060a1a19bf4efee2f29eca0125bdeea

**Comment by andersevenrud** [comment]
:)
