### ISSUE TITLE
[Automated Bugreport] Panel Items settings JS error undefined on click if no item is selected

### ISSUE THREAD

**Issue by fanfan54** [os-js/OS.js#465]
**This bugreport was generated by OS.js:**

> Une erreur inconnue est survenue, peut-être un bug.

> Veuillez reporter cela si vous pensez que c'est un bug.
 Incluez une brève description de comment cela est arrivé et si vous le pouvez; comment le reproduire

A Javascript error occured when clicking into white space of the Items list for Panel (in settings) **BUT ONLY IF NO ITEM IS SELECTED**
Encountered on demo (https://osjsv2.0o.no/) 2.0-alpha78

## Expected behaviour
Do nothing

## Actual behaviour
JS error

## Steps to reproduce the error
Open the Settings app
Go to the Panels settings
Select the Items tab
Click anywhere in the list except on items (click anywhere in white space)
=> JS error

If you select an item first, error will no longer occur when clicking on white space

## (Opti**o**nal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36","platform":"Win32","language":"fr","appVersion":"5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"}
```

## Stack Trace 
```
TypeError: Cannot read property 'index' of undefined
    at UIElement.<anonymous> (https://osjsv2.0o.no/packages/default/Settings/combined.js:495:44)
    at HTMLElement.select (https://osjsv2.0o.no/osjs.js:7284:12)
```

**Comment by andersevenrud** [comment]
Thanks for reporting! :)

This has been resolved. Please note that the demo server is scheduled for update tonight (CEST), so this bug still persists there.
