### ISSUE TITLE
Abstract FS to API

### ISSUE THREAD

**Issue by somebody1234** [os-js/OS.js#468]
I'd like to use a different FS server for this, and I'm not sure how exactly to change how OS.js' FS API works.

**Comment by andersevenrud** [comment]
You mean you want to change the endpoint, or use another system ? If you give me some more details I'll be able to help you out :)

**Comment by somebody1234** [comment]
Details are basically I need to host OS.js with a prefix (e.g. `domain/osjs`) (IDK if OS.js supports this, I'm sorry I haven't bothered to check).
I have FS at `GET`/`POST` to `/FS/filepath`.

If you need more details (probably), tell me what else I need to include.

**Comment by andersevenrud** [comment]
OS.js will auto-detect and use the "root" it is installed on. So if you have it in "/osjs" it should use "/osjs/FS" and so on. If it is not working, let me know

**Comment by andersevenrud** [comment]
I'm closing this issue now. If you feel it is unresolved, feel free to re-open.
