### ISSUE TITLE
[Automated Bugreport]GMAIL MAIL APP

### ISSUE THREAD

**Issue by abhigabhig** [os-js/OS.js#469]
**This bugreport was generated by OS.js:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 OPR/39.0.2256.48","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 OPR/39.0.2256.48"}
```

## Stack Trace 
```
TypeError: Cannot read property 'data' of undefined
    at UIElement.<anonymous> (https://osjsv2.0o.no/packages/extras/GoogleMail/combined.js:1651:38)
    at HTMLElement.mouseEventHandler (https://osjsv2.0o.no/osjs.js:1098:27)
    at HTMLElement.select (https://osjsv2.0o.no/osjs.js:7284:12)
    at HTMLElement.mouseEventHandler (https://osjsv2.0o.no/osjs.js:1098:27)
```

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting!

There are some other issues with the GMail application as well, noted in #216. Hopefully I'll get around to fixing these soon!

I'm closing this issue in favour of #216. Any fixes or updates will be posted there
