### ISSUE TITLE
No npm package

### ISSUE THREAD

**Issue by somebody1234** [os-js/OS.js#470]
I would like to see an npm package that I can `app.use` from Express

**Comment by andersevenrud** [comment]
What kind of npm package ? Care to elaborate ?

**Comment by somebody1234** [comment]
Just one I can `require` to control when/if the server starts, a basic API is enough, compatibility with Express' `app.use` would be a bonus

**Comment by andersevenrud** [comment]
Still not sure what you mean. You want an API so you can roll your own server using Express ?

**Comment by somebody1234** [comment]
Uh, I just want a function compatible with Express' `app.use` with a configurable path so I can just do `app.use(osjs(<path>))` to start osjs on a certain path.

**Comment by andersevenrud** [comment]
OS.js runs on its own server though, so not quite sure how to achieve what you want at the moment.

You can use a `reverse-proxy` in your webserver or maybe look at https://github.com/villadora/express-http-proxy for the same thing in your Express app :)

**Comment by andersevenrud** [comment]
I'm closing this issue in favour of #304 (added as a task).

I'll do some research on this subject and if anything comes up I'll notify you there :)
