### ISSUE TITLE
 GUI.Helpers.setProperty throws an error after recent commit

### ISSUE THREAD

**Issue by hiiamfrompoland** [os-js/OS.js#471]
## Expected behaviour
Property of a GUI element should be changed without an error.

## Actual behaviour
An alert dialog appears with an error as follows:
> TypeError: i.removeAttribute is not a function
>     at _setKnownAttribute (http://localhost:8000/client/javascript/gui.js:220:11)

## Steps to reproduce the error
I have updated to the most recent version (e774619), and problem started to appear. 
Having a checkbox GUI element I am trying to change it by script to checked/unchecked:
`guiElem.set('value', true);`

## Code
As I looked into code in file src/client/javascript/gui.js, it seems that line 256 is:
`_setKnownAttribute('checked', value);`
and should be:
`_setKnownAttribute(firstChild, 'checked', value);`

**Comment by andersevenrud** [comment]
Right you are. I just commited a fix for the "Code" example you gave. Did this help ?

**Comment by hiiamfrompoland** [comment]
Yes, it's nice and neat now. :)

**Comment by andersevenrud** [comment]
Great :) Thanks for reportin!
