### ISSUE TITLE
[UIX] rtl support

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#472]
I just realized (thanks to an email), that I have yet to look into `right-to-left` text support (for ex Arabic).

This is definately something worth looking into ASAP

W3C documentation: https://www.w3.org/International/questions/qa-html-dir

**Comment by qlinkz** [comment]
@andersevenrud  am here waiting for the this feature to translate to arabic

**Comment by andersevenrud** [comment]
@mslaraba Still not quite done. Here's a preview
![rtl progress](https://cloud.githubusercontent.com/assets/161548/18324618/bd50c780-753d-11e6-846c-90aeb27d8a33.png)

**Comment by clubtic** [comment]
yep a lot of work need to be done. like context menu right align. the listview too . everything should have right aligned text

**Comment by mslaraba** [comment]
yes the text should be right aligned

**Comment by mslaraba** [comment]
even windows titlebar commands should be from the left side

**Comment by mslaraba** [comment]
![image](https://cloud.githubusercontent.com/assets/6674347/18342515/1fbea3ba-75a7-11e6-9fef-9f2d9d50159b.png)

You can just add the dir="rtl" to the html tag and you will get the correct flow directions

**Comment by andersevenrud** [comment]
@mslaraba Yeah, I've been studing this a bit, and I thought this method was wrong, because to me, it looked completely wrong.

So, basically, everything should be mirrored ?

**Comment by mslaraba** [comment]
![arabic](https://cloud.githubusercontent.com/assets/6674347/18346654/5cb0be22-75b9-11e6-9a0c-acdd79a564f2.jpg)
![640x366xsshot651 png pagespeed gp jp jw pj js rj rp rw ri cp md ic no-h-ik_pl](https://cloud.githubusercontent.com/assets/6674347/18346655/5cd445b8-75b9-11e6-986c-d2bde3170cd6.jpg)


things should be like this and this

**Comment by mslaraba** [comment]
@andersevenrud  if you want I can take care of the coding on this branch

**Comment by andersevenrud** [comment]
@mslaraba @clubtic RTL support has been added (with autodetect based on name of locale) :)

@mslaraba Sorry, did not see your last message. There's probably more work to do.

![rtl2](https://cloud.githubusercontent.com/assets/161548/18358532/c5286f22-75f5-11e6-80ae-8aee0e277111.png)

**Comment by andersevenrud** [comment]
Run grunt after updating codebase!

**Comment by mslaraba** [comment]
@andersevenrud  we should add arabic for example to test it

**Comment by andersevenrud** [comment]
@mslaraba Yes

**Comment by mslaraba** [comment]
may I add ar_DZ locale

**Comment by andersevenrud** [comment]
@mslaraba Yes, please. No need to ask :) Just send me a pull-request.

Make sure to read https://github.com/os-js/OS.js/blob/master/CONTRIBUTING.md

**Comment by andersevenrud** [comment]
@mslaraba More spesifically: https://os.js.org/doc/manuals/man-development.html

**Comment by mslaraba** [comment]
@andersevenrud persian too must be RTL

**Comment by andersevenrud** [comment]
@mslaraba Fixed. Thank you :)

**Comment by mslaraba** [comment]
@andersevenrud 
file src/conf/200-compile.json doesn't exists you should update the documentation (500-build.json)

https://github.com/os-js/OS.js/wiki/Join-the-translation-team

**Comment by mslaraba** [comment]
@andersevenrud  its working perfectly you can close the issue 

![image](https://cloud.githubusercontent.com/assets/6674347/18359695/fae7d114-75f2-11e6-8469-6f75a53d392a.png)

**Comment by andersevenrud** [comment]
Great :)
