### ISSUE TITLE
It lacks a browser

### ISSUE THREAD

**Issue by raul2015** [os-js/OS.js#473]
## Expected behaviour
Please it would be pretty nice it has a browser

**Comment by andersevenrud** [comment]
See https://github.com/os-js/OS.js-experimental

**Comment by andersevenrud** [comment]
Please note that using a browser on OS.js deployed in a browser environment is simply not possible without setting up a HTTP Proxy server.

https://en.wikipedia.org/wiki/Same-origin_policy
