### ISSUE TITLE
Sub Application

### ISSUE THREAD

**Issue by msaqibansari** [os-js/OS.js#474]
Hi @andersevenrud,

I need to show our one application under sub tab of 2nd application. Is it possible?

Thanks

**Comment by andersevenrud** [comment]
I don't understand what you mean by this

**Comment by msaqibansari** [comment]
2 different applications treat as separate entity and open in different window (virtual window) on OSjs.

Let's say I have 2 applications app1 and app2. If I open app1 and click button existed on app1 which opens app2 in separate window. But I need to open app2 inside app1 container like embed application.

**Comment by andersevenrud** [comment]
A window inside another window ?

**Comment by msaqibansari** [comment]
yes application inside another application

**Comment by andersevenrud** [comment]
There's a difference between a `Window` and an `Application`. You want a window from **B** to appear inside a Window from **A** ?

**Comment by msaqibansari** [comment]
yes you can say this.

I'll have 2 tabs in A. In first tab of A, I'll show some information and on 2nd tab I need to show window from B.

**Comment by andersevenrud** [comment]
I don't know what you mean by a `tab` though. And now you say "show some information", which implies that you just want to do some sort of messaging between your applications. This is all very confusing ? Can you make an illustration or something ?

**Comment by andersevenrud** [comment]
@msaqibansari Could you try to reformulate your question or try to give me an illustration of what you're thinking ? I really like to answer you :)

**Comment by khoaakt** [comment]
It's mean MDI Window 😄 
Right? @msaqibansari

**Comment by andersevenrud** [comment]
@khoaakt That was my first thought as well, but not quite sure after the last message when he says "show some information from another window" :)

**Comment by khoaakt** [comment]
@andersevenrud I think he mean something like MDI. But is it a multi-thread application?
For example: Google Chrome 😄.

**Comment by andersevenrud** [comment]
I'm closing this issue due to lack of response. Feel free to re-open
