### ISSUE TITLE
[GUI] Creating Nested Submenus

### ISSUE THREAD

**Issue by Rxswyers** [os-js/OS.js#483]
## Expected behaviour

Nested submenus show when using GUI.createMenu()
## Actual behaviour

The initial submenu shows. A nested one will only have the > like it should, but the menu is not displayed when hovered over
## Steps to reproduce the error
```js
OSjs.API.createMenu([{
  title: 'Item 1',
  menu:[{
    title: 'Subitem 1.1'
  }, {
   title: 'Subitem 1.2',
   menu: [{
     title: 'Subitem 1.2.1'
   }]
  }]
}], {x:100, y:100})
```

**Comment by andersevenrud** [comment]
Seems to be purely a CSS problem :)

**Comment by andersevenrud** [comment]
Fixed now :)
