### ISSUE TITLE
[Core] Package Management and Store

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#488]
Recently I started some work on the Package Management again.
- [x] Update client PackageManager
- [x] Make use of API call on boot to enum installed packages
- [x] Fallback to pre-built 'packages.js' file for standalone builds
- [x] PHP Backend (API method: `packages`)
- [x] Node Backend (API method: `packages`)
- [x] Support for multiple package locations
- [x] **Action**: `list`
- [x] **Action**: `install`
- [x] **Action**: `uninstall`
- [ ] **Action**: `update`
- [x] PackageManager Application: Multiple repo lists
- [ ] Update IDE application
- [x] Update unit tests
- [ ] Package validation ?
- [ ] System packages ?
- [x] Implement into settings

~~**Branch:** https://github.com/os-js/OS.js/tree/issue-488~~

**Branch:** https://github.com/os-js/OS.js/tree/development

**Comment by SpaceboyRoss01** [comment]
Take a look at this https://github.com/SpaceboyRoss01/OS.js-universe

**Comment by andersevenrud** [comment]
Closing this issue because it will all have to be re-done for v3. But, that's a good thing :)
