### ISSUE TITLE
[Arduino Yun] WIFI settings error

### ISSUE THREAD

**Issue by nayola** [os-js/OS.js#495]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot convert undefined or null to object
    at http://192.168.240.1/packages/target/ArduinoService/combined.js?61161:98:16
    at http://192.168.240.1/packages/target/ArduinoService/combined.js?61161:193:7
    at _Handler.<anonymous> (http://192.168.240.1/packages/target/ArduinoService/combined.js?61161:269:7)
    at _Handler.<anonymous> (http://192.168.240.1/osjs.js:1692:14)
    at Object.onerror (http://192.168.240.1/osjs.js:8870:17)
    at XMLHttpRequest.onReadyStateChange (http://192.168.240.1/osjs.js:1202:16)
```

**Comment by nayola** [comment]
My brand new arduino Yun cannot connect to my home AP wifi.
it constantly fails while configuration stage.

**Comment by andersevenrud** [comment]
@nayola Thanks for reporting.

I've resolved the issue you pasted into the issue description. I will submit this to the Arduino team so it gets included into the next official update of Arduino-OS.

**Comment by nayola** [comment]
Is this bug related to AJAX/XHR error?

**Comment by andersevenrud** [comment]
It could be. I am currently investegating problems that produces "AJAX/XHR" errors. It seems to be related to the webserver running on the TIAN and Yun boards.

**Comment by andersevenrud** [comment]
#436 now superseeds this issue.
