### ISSUE TITLE
[Applications] Settings - Bug in sound module

### ISSUE THREAD

**Issue by iBicha** [os-js/OS.js#497]
**This bugreport was generated by OS.js:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it
Goes to settings -> Sound, click on gears icon

## Expected behaviour
Show more settings

## Actual behaviour
Throws an error

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}
```

## Stack Trace 
```
TypeError: Cannot read property 'data' of undefined
    at UIElement.<anonymous> (http://localhost:8000/packages/default/Settings/module-sound.js:101:44)
    at HTMLButtonElement.mouseEventHandler (http://localhost:8000/client/javascript/utils/events.js:476:27)
```

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting. I see now that the new settings app has some bugs -- as was expected :)

I'll fix this ASAP

**Comment by andersevenrud** [comment]
This should now be resolved :)
