### ISSUE TITLE
[Applications] Settings - Bug in initialization

### ISSUE THREAD

**Issue by duracellrabbid** [os-js/OS.js#498]
**This bugreport was generated by OS.js:**

> An error occured while trying to launch: ApplicationSettings

> Application 'ApplicationSettings' construct failed: TypeError: m.watch.forEach is not a function

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows)"}
```

## Stack Trace 
```
ApplicationSettings/<@http://t.dynu.com:8000/packages/default/Settings/combined.js:647:9
ApplicationSettings@http://t.dynu.com:8000/packages/default/Settings/combined.js:643:5
__onschemesloaded@http://t.dynu.com:8000/osjs.js:2533:24
_createProcess@http://t.dynu.com:8000/osjs.js:2568:12
_apiLaunch/</<@http://t.dynu.com:8000/osjs.js:2605:15
_preload/</<@http://t.dynu.com:8000/osjs.js:2498:13

```

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting. I see now that the new settings app has some bugs -- as was expected :)

I'll fix this ASAP

**Comment by andersevenrud** [comment]
Not quite sure why this error was raised -- but added something to prevent it. If you have further problems, feel free to re-open this issue.
