### ISSUE TITLE
error installing mysql from pakage manager

### ISSUE THREAD

**Issue by lolodyn** [os-js/OS.js#499]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationArduinoPackageManager.prototype.callOpkg/<@http://192.168.0.69/packages/target/ArduinoPackageManager/combined.js?23224:288:13
ApplicationArduinoPackageManager.prototype.callAPI/<@http://192.168.0.69/packages/target/ArduinoPackageManager/combined.js?23224:260:14
doAPICall/<@http://192.168.0.69/osjs.js:1756:7
_Handler.prototype.__callXHR/data.onerror@http://192.168.0.69/osjs.js:9466:9
onReadyStateChange@http://192.168.0.69/osjs.js:1266:11

```

**Comment by andersevenrud** [comment]
Hi.

Thanks for reporting. This issue has (already) been fixed and is pending an official update from Arduino. If you want to, I can notify you when the pull-request has been merged and goes into production :)

Ref: #461
