### ISSUE TITLE
[Automated Bugreport] Cannot read property 'fontFamily' of undefined

### ISSUE THREAD

**Issue by iBicha** [os-js/OS.js#500]
**This bugreport was generated by OS.js:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## Expected behaviour
Should show window to select font

## Actual behaviour
Throws Error

## Steps to reproduce the error
Select Settings -> Theme -> Font browse button

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}
```

## Stack Trace 
```
TypeError: Cannot read property 'fontFamily' of undefined
    at UIElement.<anonymous> (http://localhost:8000/packages/default/Settings/module-theme.js:104:33)
    at HTMLElement.mouseEventHandler (http://localhost:8000/client/javascript/utils/events.js:476:27)
```

**Comment by andersevenrud** [comment]
Thanks!

Should be fixed now :)
