### ISSUE TITLE
[GUI] Resizing window cursor

### ISSUE THREAD

**Issue by iBicha** [os-js/OS.js#503]
I noticed that around the edges of the window, the cursor is always set to `'move'`.

I suggest using other attributes for the cursor, depending on its position.
(for example `'ew-resize'` for the left and right, `'ns-resize'` for the top and buttom, `'nwse-resize'` for the top-left and bottom-right corners, and `'nesw-resize'` for the top-right and bottom-left corners)

Would serve as a better indication to the user about what he can do while placing the cursor by the edge (the move cursor would suggest that you can move the window, not actually resize it).

**Comment by andersevenrud** [comment]
This is on my (long list) if TODOs actually :)

**Comment by iBicha** [comment]
Oh. Is this list public somewhere?

**Comment by andersevenrud** [comment]
No, not this one. It's just a bunch of ideas and stuff horribly written down in a text file, hehe :)

**Comment by andersevenrud** [comment]
It is now added :)
