### ISSUE TITLE
[Automated Bugreport] Launching a deleted app

### ISSUE THREAD

**Issue by iBicha** [os-js/OS.js#504]
**This bugreport was generated by OS.js:**

> An error occured while trying to launch: ApplicationTheCubes

> Application 'ApplicationTheCubes' preloading failed: 
/packages/default/TheCubes/main.js,/packages/default/TheCubes/scheme.html

## Expected behaviour
"App not found. delete shortcut?"

## Actual behaviour
Throws error

## Steps to reproduce the error
Install a new app, delete it, and launch it.

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}
```

**Comment by andersevenrud** [comment]
So, you deleted an app, but did not update the manifest ?

**Comment by iBicha** [comment]
Actually, i did not delete it from within OSjs, but from the packages folder (so yea the manifest did not update). My bad, i didn't mention that.

**Comment by andersevenrud** [comment]
If you remove packages from `src/packages` you have to manually update the manifest file.

**Comment by andersevenrud** [comment]
`grunt build:manifest`

**Comment by iBicha** [comment]
i figured. well, maybe a small check if the app exists before launching it? or else, there is no need for this, close it if you see fit.

**Comment by andersevenrud** [comment]
If the package exists in the manifest, it will try to load it. The error you see is the result of failure at that point -- so this is more or less equivalent to a "check". But I could improve on the error messages I guess -- make it clear that the application might have been uninstalled or something :) I'll put it down in my queue, I have some more error message stuff coming
