### ISSUE TITLE
error message when deleting a file in file manager

### ISSUE THREAD

**Issue by sophana** [os-js/OS.js#509]
## Expected behaviour
no error message

## Actual behaviour
error message popup:

Error: File expects at least one argument
    at new FileMetadata (https://osjs.xx.net/osjs.js:12285:13)
    at https://osjs.xx.net/osjs.js:12048:22
    at Array.some (native)
    at _checkPath (https://osjs.xx.net/osjs.js:12047:26)
    at https://osjs.xx.net/osjs.js:12059:9
    at _finished (https://osjs.xx.net/osjs.js:11622:20)
    at https://osjs.xx.net/osjs.js:11605:15
    at _Handler.onVFSRequestCompleted (https://osjs.xx.net/osjs.js:11257:5)
    at https://osjs.xx.net/osjs.js:11599:13
    at https://osjs.xx.net/osjs.js:12406:7

Actualy, the file is deleted on disk, but the file manager isn't refreshed.

## Steps to reproduce the error
delete a file in file manager

## (Optinal) Browser and OS information
chrome linux 64.

**Comment by andersevenrud** [comment]
Thanks, mate! Fixed

Looks like a few bugs came up during latest update. I really need more testers! :D

**Comment by sophana** [comment]
Works now.

Thanks!
