### ISSUE TITLE
win-start-dev not working

### ISSUE THREAD

**Issue by iBicha** [os-js/OS.js#510]
I cloned the repo again, grunt it, and when i launch with `win-start-dist`, it works fine, but with `win-start-dev`, most resources are not found, and i get to a login screen (with no styling)
![alt text](https://s22.postimg.org/qtzg49m3l/error.png "osjs error")

**Comment by andersevenrud** [comment]
On Windows you need to manually create the symlinks to run the developer dist. This is sadly something that requires manual interaction.

Run `bin/create-windows-symlinks.cmd` as administrator.
