### ISSUE TITLE
Settings Content Header Title doesn't get translated

### ISSUE THREAD

**Issue by mslaraba** [os-js/OS.js#511]
![image](https://cloud.githubusercontent.com/assets/6674347/19318466/c41234d6-90a0-11e6-8ba1-3699823b5c9b.png)

**Comment by andersevenrud** [comment]
If you update your codebase there's an entirely new settings application available ;)

**Comment by andersevenrud** [comment]
http://community.os.js.org/t/update-version-bump-alpha80/101/1

**Comment by mslaraba** [comment]
![image](https://cloud.githubusercontent.com/assets/6674347/19320431/2d1a350c-90a9-11e6-806a-251b44ae54b4.png)

**Comment by andersevenrud** [comment]
Should be fixed now :)
