### ISSUE TITLE
[Automated Bugreport] Archiver is possibly broken

### ISSUE THREAD

**Issue by Sprinting** [os-js/OS.js#516]
**This bugreport was generated by OS.js:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## Expected behaviour
Expected an archived file

## Actual behaviour
A JS Error Report was generated

## Steps to reproduce the error
Try to archive a file

## (Optinal) Browser and OS information
```
Google Chrome	53.0.2785.143 (Official Build) m (32-bit)
Revision	f33d44362232c20d1ce2111c53ea8730698f3c88-refs/branch-heads/2785@{#925}
OS	Windows 
Blink	537.36 (@f33d44362232c20d1ce2111c53ea8730698f3c88)
JavaScript	V8 5.3.332.47
```
```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"}
```

## Stack Trace 
```
Error: Cannot download a path without a path
    at Object.download (https://osjsv2.0o.no/osjs.js:11882:15)
    at openFile (https://osjsv2.0o.no/osjs.js:15792:9)
    at ZipArchiver.add (https://osjsv2.0o.no/osjs.js:15968:5)
    at https://osjsv2.0o.no/packages/extras/Archiver/combined.js:277:18
    at https://osjsv2.0o.no/packages/extras/Archiver/combined.js:393:7
    at cb (https://osjsv2.0o.no/osjs.js:2719:16)
    at DialogWindow.closeCallback (https://osjsv2.0o.no/osjs.js:4546:16)
    at FileDialog.checkSelection (https://osjsv2.0o.no/osjs.js:10261:12)
    at UIElement.<anonymous> (https://osjsv2.0o.no/osjs.js:10073:16)
    at HTMLElement.mouseEventHandler (https://osjsv2.0o.no/osjs.js:1115:27)
```

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting!

This seems like a problem with the demo-server, and not the application itself. http://osjsv2.0o.no demo is quite a bit outdated, and an update will most likely solve this problem since I was unable to reproduce this error in my test deployment environment :)

I'll look into updating tomorrow (or tonight if I find the time).
