### ISSUE TITLE
its showing this

### ISSUE THREAD

**Issue by BhavyaGupta07** [os-js/OS.js#525]
An error occured while trying to launch: ApplicationSettings

> Application 'ApplicationSettings' preloading failed:  /packages/target/Settings/combined.js?77769

**Comment by BhavyaGupta07** [comment]
what should i do

**Comment by andersevenrud** [comment]
Arduino?

**Comment by BhavyaGupta07** [comment]
yes

**Comment by andersevenrud** [comment]
I already have an issue on this here: #436

Does rebooting the device help ?
