### ISSUE TITLE
[Feature Request] Add OS.js Version to automatic bug reports

### ISSUE THREAD

**Issue by marktopper** [os-js/OS.js#526]
When triggering an error in OS.js, then an option apears to report the bug as a Github Issue.

However, why not adding the OS.js version to that bug report for easier assistance?

**Comment by andersevenrud** [comment]
Good idea! Added :)

**Comment by marktopper** [comment]
In what version does this appear?

**Comment by andersevenrud** [comment]
It's in current master, so not any "version" per se, but we can call it alpha80.5 :P
