### ISSUE TITLE
Better requirement documentation for MySQL authentication

### ISSUE THREAD

**Issue by hexblot** [os-js/OS.js#532]
## Expected behaviour

Having the listed dependencies ( as per https://github.com/os-js/OS.js/blob/master/INSTALL.md and linked pages and https://os.js.org/manual/auth/modules/ ) should allow installation and usage without issues

## Actual behaviour

"**Invalid login credentials**" when trying to login, no other error messages.

## Steps to reproduce the error

- On a minimal CentOS 7.2 Linux, install a normal LAMP/LEMP stack and create the appropriate vhost configuration. _Demo_ mode works fine.
- Configure MySQL auth as per https://os.js.org/manual/auth/modules/#mysql
- Attempt to login

## Browser and OS information

Browser is irrelevant, any OS having PHP lower than 5.5.0 will exhibit this behavior.

## Possible resolution

- State that PHP>5.5.0 is required for MySQL authentication. This is a simple yet not very good approach.
- Use the excellent https://github.com/ircmaxell/password_compat library, which implements the password_* functions in pure PHP with no external dependencies (similar to bcryptjs vs bcrypt), and is only actually used when the functions are missing.

**Comment by andersevenrud** [comment]
Hi!

Thanks for reporting :)

I've now included `password_compat` via *Composer* and have updated the documentation accordingly:

- https://os.js.org/manual/server/php/
- https://os.js.org/manual/auth/modules/#mysql

**Comment by andersevenrud** [comment]
Hi,

Just a notice about the database modules: http://community.os.js.org/t/notice-rename-of-mysql-and-sqlite-modules/106

I'm also closing this issue now as I feel it is resolved. If you don't agree, feel free to re-open :)
