### ISSUE TITLE
Saving Arduino Tian set up configuration

### ISSUE THREAD

**Issue by rpehlm** [os-js/OS.js#535]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.240.1/packages/target/ArduinoWizardSettings/combined.js?31640
Line: 482:29
Message: Unspecified error.
```

**Comment by rpehlm** [comment]
Using MS Edge 38.14393.0.0

**Comment by andersevenrud** [comment]
Hi,

Thanks for reporting.

I looked it up and it seems like maybe Edge prevented a redirect and produced an error message (It should have taken the hostname you filled in and sent you there, but instead this). Too bad you only got a `Unspesified error` and not something more detailed... but I'll look into it and see if I can reproduce this properly.

**Comment by andersevenrud** [comment]
#436 now superseeds this issue.
