### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by garouz** [os-js/OS.js#537]
**This bugreport was generated by OS.js:**

> An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug.
Include a brief description on how the error occured, and if you can; how to replicate it

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36","platform":"Win32","language":"ja","appVersion":"5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"}
```

## Stack Trace 
```
ReferenceError: importScripts is not defined
    at https://osjsv2.0o.no/packages/extras/PDFjs/vendor/pdf.js/src/worker_loader.js:26:4
```

**Comment by andersevenrud** [comment]
Hi,

This is a problem with a third-party library. I'm pretty sure this will be resolved by itself when I get to updating the demo :)
