### ISSUE TITLE
Attempted to edit a conf file

### ISSUE THREAD

**Issue by rpehlm** [os-js/OS.js#539]
The file was /usr/lib/python2.7/ciao/conf/rest.ciao.json.conf

An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.2.133/osjs.js
Line: 1762:26
Message: Cannot doLaunchFile() without a mime type
```

**Comment by andersevenrud** [comment]
Hi,

Sorry for a late reply. Busy holiday!

This is a bug that has been fixed and is pending an official update. If you want I can notify you when this is ready
