### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by HusseinYounis** [os-js/OS.js#540]
**This bugreport was generated by OS.js 2.0-alpha81:**

> An error occured while trying to launch: ApplicationFileManager

> Application 'ApplicationFileManager' preloading failed: 
/packages/default/FileManager/main.js,/packages/default/FileManager/locales.js,/packages/default/FileManager/scheme.html

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36","platform":"Win32","language":"en-US","appVersion":"5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"}
```

**Comment by andersevenrud** [comment]
Hi,

Since you have not provided any details about this error I cannot resolve it.

Please fill in the "title", "expected behaviour" and "actual behaviour" (or just make a comment on how this occured and what you did to make it so), and I will re-open the issue :)
