### ISSUE TITLE
arduino-yun

### ISSUE THREAD

**Issue by andrego7** [os-js/OS.js#543]
An error occured while trying to launch: ApplicationFileManager

> Application 'ApplicationFileManager' preloading failed:  /packages/target/FileManager/combined.js?202

**Comment by andersevenrud** [comment]
Hi,

This is a known issue and seems to be a problem with the webserver on the Arduino, not OS.js itself. It's just a symptom.

Please see this comment on resolution: https://github.com/os-js/OS.js/issues/436#issuecomment-271078038
