### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by mistergibson** [os-js/OS.js#544]
## Actual behaviour
node osjs build

/home/mistergibson/Documents/Development/OS.js/osjs:5
  const ver = process.version.substr(1).split(/\./g);
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

## Steps to reproduce the error
node osjs build

## (Optinal) Browser and OS information
Linux Mint (Rebecca)

**Comment by andersevenrud** [comment]
I'm pretty sure you're running an old Node version.

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by mistergibson** [comment]
v0.10.25

**Comment by andersevenrud** [comment]
Install v4 or newer. O.x is pretty old.

Look into using "nvm" or see the link i pasted.
søn. 8. jan. 2017 kl. 23.49 skrev mistergibson <notifications@github.com>:

**Comment by mistergibson** [comment]
Got it now - thanks for the link :)  OS.js rocks btw ;)

**Comment by andersevenrud** [comment]
No problem :)
