### ISSUE TITLE
zh_CN Language cause wrong display

### ISSUE THREAD

**Issue by mai1015** [os-js/OS.js#545]
## Expected behaviour
Layout display normal with different language

## Actual behaviour
There are multiple display error in Chinese

## Steps to reproduce the error
Change Language to Chinese when startup

## (Optinal) Browser and OS information
Windows 10 Chrome 54.0.2840.99 m

**Comment by andersevenrud** [comment]
Could you please explain what "multiple display errors" mean? Or maybe a screenshot? :)

**Comment by mai1015** [comment]
Sorry, i forget to upload the picture.
![Error Display](https://cloud.githubusercontent.com/assets/5039212/21882386/33b762b0-d878-11e6-973a-86dc9ee3631b.png)

**Comment by andersevenrud** [comment]
You have to refresh the browser to make all changes take effect.

There's a lot of missing translations, so there is still a lot of stuff in English still. But it works just fine (at least from my testing) :)

**Comment by mai1015** [comment]
Actually, I refresh the brower. It still display like this with Chinese language.

**Comment by andersevenrud** [comment]
@mai1015 What exactly is the problem. I think I need it pointed out to me in this case :)

1. That everything goes left-to-right
2. Missing translations

**Comment by mai1015** [comment]
That everything goes left-to-right

**Comment by andersevenrud** [comment]
I was actually told by someone in the community that left-to-right text was correct for this language.

I have no idea... because I'm European :) So I guess this is not correct?

**Comment by mai1015** [comment]
Yes... It is definitely not the case... Can u please change it? Thank u very much.

**Comment by andersevenrud** [comment]
I've changed it out now.


But I will not update the demo server until this weekend since that 
takes some time.

**Comment by mai1015** [comment]
Thank u very much!!
