### ISSUE TITLE
Failed Static IP setup on ETH1

### ISSUE THREAD

**Issue by nairn62** [os-js/OS.js#546]
An error occured while trying to launch: ApplicationArduinoLuci

> Application 'ApplicationArduinoLuci' preloading failed:  /packages/target/ArduinoLuci/combined.js?78076

**Comment by andersevenrud** [comment]
Duplicate of #542

> Aha, I see. Yes, there seems to be an issue with the webserver on that board -- which is being investegated.

**Comment by andersevenrud** [comment]
Btw, You can still use Luci (which is also installed on the board) to configure stuff.
