### ISSUE TITLE
Updating Arduino Oss in to Arduino Yun

### ISSUE THREAD

**Issue by Jossua116** [os-js/OS.js#548]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
http://arduinoyun.local/packages/target/ArduinoPackageManager/combined.js?11334:282:28
http://arduinoyun.local/osjs.js:1692:19
onerror@http://arduinoyun.local/osjs.js:8870:22
onReadyStateChange@http://arduinoyun.local/osjs.js:1202:23
```

**Comment by andersevenrud** [comment]
Hi! This bug has been fixed and is pending an official update.

You can still update your system with Luci (that is also available over your browser), or:

1. Log in via a shell to your Arduino
2. Run `opkg update`
3. Run `opkg list-upgradable | xargs opkg upgrade`
