### ISSUE TITLE
Events not working when creating gui items via javascript

### ISSUE THREAD

**Issue by p3root** [os-js/OS.js#549]
## Expected behaviour
When I create an element via Javascript events should work as same as when the element is created by the html.

## Actual behaviour
No events are coming ie no click.

## Steps to reproduce the error
 var sub = GUI.Element.create('gui-menu-entry', {
            "id": "CreateItem"e,
            "label": "Create ",
          });
          sub = submenu.append(sub);
          sub.on("click",  function(e, v) {
              alert("CLIIICKKKEEDD");
          });

**Comment by andersevenrud** [comment]
The event name is `select` and not `click`.

**Comment by p3root** [comment]
ah :)

ok thanks, but isn't that a little bit confusing? Shouldn't click also be routed?

**Comment by andersevenrud** [comment]
You are correct. I'll make sure to do that :)

**Comment by andersevenrud** [comment]
You can now use `click` as well as `select`. They both behave the same
