### ISSUE TITLE
[GUI] Duplicate events triggered in gui-menu

### ISSUE THREAD

**Issue by p3root** [os-js/OS.js#550]
## What I need
I have a menu depending on a selection, therefore the menu changes

## Expected behaviour
When I clear the menu <gui-menu> all event bindings should be cleared automatically.

## Actual behaviour
The event binding is still here (memory leak)

## Steps to reproduce the error
`<gui-menu` `data-id="MENU"/>`

`function doe() {
MENU.clear();
var sub = GUI.Element.create('gui-menu-entry', {});
MENU.append(sub);
sub.on("select", function(e) {
alert("CLICKED");
});

}`

**Comment by andersevenrud** [comment]
I don't understand the reproduction though. You assign a new event handler every time you run this function ? `.clear()` only removes the children of the element, it does not unbind the handlers assigned to it.

**Comment by p3root** [comment]
I create the menu everytime (when I run through the function) new. And clear() should also clear the bindings.

Outlook <https://aka.ms/ghei36> for<https://aka.ms/ghei36> Android<https://aka.ms/ghei36> herunterladen

Von: Anders Evenrud
Gesendet: Sonntag, 15. J?nner, 21:08
Betreff: Re: [os-js/OS.js] Menu Empty doesn't unbind events (#550)
An: os-js/OS.js
Cc: Patrik Pfaffenbauer, Author

I don't understand the reproduction though. You assign a new event handler every time you run this function ? .clear() only removes the children of the element, it does not unbind the handlers assigned to it.

-

**Comment by p3root** [comment]
Anyway, I don't understand why the select callback will be called twice on the second time. I create a new menu item, therefore the select binding should be on the new created item??

**Comment by andersevenrud** [comment]
Hm. Actually, there is no `clear()` method on `gui-menu`. Theres `empty()`.... so now I'm a bit confused.

**Comment by p3root** [comment]
Oh sorry, but I use `empty()`.

**Comment by andersevenrud** [comment]
Allright. I've added so that all children gets their events destructed on `empty()` now.

**Comment by p3root** [comment]
Ok, thank you :)
Will try that tomorrow.

**Comment by p3root** [comment]
Hey anders!

The changes didn't changed my behaviour. I still get the callback x times.

**Comment by andersevenrud** [comment]
OK. Let me set up an app to test myself

**Comment by andersevenrud** [comment]
Can you give me an example code please ? I tried implementing the code above, but not sure of the full usage.

**Comment by p3root** [comment]
Ok.
I have already found "working" solution. I will add both to the code.

**Comment by andersevenrud** [comment]
FYI: You can bind the event to the `gui-menu` element. Where you can use `ev.detail` to figure out which element was clicked inside.

**Comment by p3root** [comment]
Here is a working example:
https://github.com/p3root/OS.js/tree/master/src/packages/custom/menutest

**Comment by p3root** [comment]
Could work as a workaround. But it should also work the way I do it, or am I wrong?

**Comment by andersevenrud** [comment]
I figured it out.

```
// This always returns submenu!
sub = submenu.append(sub); 
sub.on('select', function(e) {});

// Correct would be:
submenu.append(sub); 
sub.on('select', function(e) {});
```

**Comment by andersevenrud** [comment]
I'd suggest you use the Window class for all your GUI stuff. Ex:

```
  ApplicationmenutestWindow.prototype.init = function(wmRef, app, scheme) {
    var root = Window.prototype.init.apply(this, arguments);

    // Load and render `scheme.html` file
    scheme.render(this, 'menutestWindow', root);

    // Put your GUI code here (or make a new prototype function and call it):
    function SelectionChanged(obj, submenu) {
      console.error('xxx', submenu.$element.querySelector('*'));
      submenu.empty();

      var sub = GUI.Element.create('gui-menu-entry', {
        'id': 'CreateItem',
        'label': 'Create'
      })

      sub = submenu.append(sub);
      sub.on('select', function(e) {
        alert('click');
      });
    }

    var treeView = this._find('s1tree');
    var submenucreate = this._find('SubmenuCreate');
    this._find('Save').on('click', function(e) {
      alert('save');
    });

    treeView.add([{
      'label': 'Test',
      'icon': '',
      'value': {
        'name' : 'TEst', 'type': 1, 'properties': [{'name': 'asdf', 'group': 'Main', 'type': 'string', 'readonly': 0, 'value': 'bla'}]
      },
      'entries': [
        {
          'label': 'TEst',
          'value': {
            'name' : 'TEst', 'type': 1, 'properties': [{'name': 'asdf', 'group': 'Main', 'type': 'string', 'readonly': 0, 'value': 'bla'}]
          },
          'icon': ''
        }
      ]
    }]);

    treeView.on('select', function(ev) {
      if (ev && ev.detail && ev.detail.entries && ev.detail.entries.length > 0 && ev.detail.entries[0].data) {
        var item = treeView.get('entry', ev.detail.entries[0].data);
        SelectionChanged(item, submenucreate);
      }
    });

    return root;
  };


```

You might also I use the `win._find()`  shortcuts etc instead of using the scheme reference.

**Comment by andersevenrud** [comment]
This probably means that my commits with the unbinding is not needed... so I'll change that a bit.

**Comment by p3root** [comment]
Works :) thank you

**Comment by andersevenrud** [comment]
Nice! :)
