### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by kounelios13** [os-js/OS.js#551]
## Expected behaviour
The expected behavior is to be able to create a new user by going to `Settings > Users ` and provide the user details

## Actual behaviour
When I try to create a new user after filling the fields with the details needed and press save 
I get an error box saying "Error while managing users" and there is no summary

## Steps to reproduce the error
Go to ```Settings > Users ``` fill in all the details and press ```Save```

**Comment by andersevenrud** [comment]
This only works with a backend that provides this functionality, i.e. the `database` authenticator module.

Are you using this one?

**Comment by andersevenrud** [comment]
I've made it so it does not show up if it's not available.
