### ISSUE TITLE
Error, can not find module osjs

### ISSUE THREAD

**Issue by petrk94** [os-js/OS.js#555]
## Expected behaviour
Server start

## Actual behaviour
Error, can not find module osjs

## Steps to reproduce the error
node osjs run

## (Optinal) Browser and OS information
using managed shared server host uberspace.

Error message: 

$ node osjs run

module.js:340
    throw err;
          ^
Error: Cannot find module '/var/www/virtual/xxx/vos.xxx.de/osjs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

Please help me, thanks

**Comment by andersevenrud** [comment]
You have to run the command from within OS:js directory

**Comment by petrk94** [comment]
@andersevenrud 
I have tried it in the subdomain subdirectory os.xxx.de/osjs/
and got this error message:

[xxx@uberspace osjs]$ node osjs run
/var/www/virtual/xxx/os.xxx.de/osjs/osjs:53
  const actions = args._.map(function(iter) {
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3

What did I wrong?

**Comment by andersevenrud** [comment]
You're running a very old version of node most likely.

nodejs officially stopped supporting these versions as of end of 2016. You have to upgrade, or use `nvm`.

**Comment by petrk94** [comment]
@andersevenrud 
I have chose the version nodejs v7.0.0. This is the latest available version which I can use on the hosting server.
But while trying it again, I get this error:

$ node osjs run
{ Error: ENOENT: no such file or directory, open '/var/www/virtual/xxx/os.xxx.de/osjs/src/server/settings.json'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/virtual/xxx/vos.xxx.de/osjs/src/server/settings.json' }

I could not find the error in the os.js.org manual.
What this could mean?

**Comment by andersevenrud** [comment]
You most likely have forgotten something in the installation procedure: https://os.js.org/manual/installation/nix/

**Comment by petrk94** [comment]
ok, I have used the automatic installer and now its starting, unfortunately I still get a error in the browser, while the shell is not showing any error:
![jserror](https://cloud.githubusercontent.com/assets/19719052/22259995/c656916a-e267-11e6-9c43-096c00b3b2f2.PNG)
![cli](https://cloud.githubusercontent.com/assets/19719052/22259998/c9d812aa-e267-11e6-84ec-f0d5b24eb4c3.PNG)

**Comment by andersevenrud** [comment]
You did not have to use the automated installer. I just pointed to the steps. But, OK.

I see that you get a 404 error. Can you run `node osjs run --loglevel=15` or see the network monitor in your browser for which file that failed ?

**Comment by petrk94** [comment]
I have made it in google chrome developer tools, I guess the shared hosting server is too slow or I dont know why the files didnt get loaded.

**Comment by andersevenrud** [comment]
Which files was it ? Should be working, even on slow connections.

**Comment by petrk94** [comment]
I have made it in google chrome developer tools, I guess the shared hosting server is too slow or I don't know why the files did not get loaded.

![monitor](https://cloud.githubusercontent.com/assets/19719052/22260421/782ac1ee-e269-11e6-813c-fe268190d6fe.PNG)

**Comment by andersevenrud** [comment]
And if you run with `node osjs run --target=dist` ?

**Comment by petrk94** [comment]
I have tried it, but didnt changed anything :(
![networkmonitor](https://cloud.githubusercontent.com/assets/19719052/22260886/20a774c4-e26b-11e6-8303-9c35da449873.PNG)

**Comment by andersevenrud** [comment]
It should not display any of those files if you run with `--target=dist`.

It should say this when server has started:


> 2017-01-24T18:28:52.316Z Using http on port 8000 in dist

**Comment by petrk94** [comment]
ah sorry, I have loaded still the /dist-dev/ site.
I have reloaded it again os.xxx.de/dist/
and got this as result:

![networkmonitor_dist](https://cloud.githubusercontent.com/assets/19719052/22261192/47d38082-e26c-11e6-965e-bd0907d5eaed.PNG)

**Comment by andersevenrud** [comment]
Is there any way for me to view this site, or is it on your local machine?

**Comment by petrk94** [comment]
@andersevenrud  I have send you an email to your gmail

**Comment by andersevenrud** [comment]
Ok, I've looked at it. How exactly is your webserver configured ? If you use the node server you need a reverse-proxy or connect to port 8000 where it is running, not serve the `/dist` directory.

**Comment by petrk94** [comment]
Do you mean ports? The hoster is uberspace, if its about firewall, I need request a open port for my account. nodejs I have not configured in any way. How to make a reverse-proxy on the server O.o ?
I have tried os.xxx.de:8000 but get the ERR_CONNECTION_TIMED_OUT displayed.

**Comment by andersevenrud** [comment]
Do you have a VPS or just a normal "webhotel" ?

**Comment by petrk94** [comment]
Its more a "webhotel", I have my account and share the resources with other guys on ther server. Have not root or similar

**Comment by andersevenrud** [comment]
Ok. If your provider does not support native nodejs apps for hosting, reverse-proxies, Docker containers, or you have no root (access to modify webserver), then I'm afraid you cannot use the node server. (Using port 8000 is probably something you cannot do as your host has firewalls only allowing "normal web" traffic).

However, you can use the PHP server, but it has some caveats:

https://os.js.org/manual/server/php/#webhosts

**Comment by andersevenrud** [comment]
OS.js is really intended to run self-hosted, but it is possible to run it on your setup, it only requires a few extra steps.

**Comment by petrk94** [comment]
I have tried it on my windows computer, the npm install worked fine, but the start I get a error message:
bin>win-start-dev.cmd
This script will launch OS.js in node using: `node src\server\node\server.js dist-dev`
To stop node server, press CTRL+C
supervisor not installed, the server will not be live reloaded
{ Error: ENOENT: no such file or directory, open 'C:\Users\xxx\Downloads\OSjs-master\OS.js-master\src\server\settings.json'
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\xxx\\Downloads\\OSjs-master\\OS.js-master\\src\\server\\settings.json' }

what that means?

**Comment by andersevenrud** [comment]
It means you have not set up symlinks. See https://os.js.org/manual/installation/windows/

Or run in production mode `node osjs run --target=dist`.

**Comment by petrk94** [comment]
ok, now its running on localhost:8000 on my windows 10 computer. But how I can move it to the server and let it run there?

**Comment by andersevenrud** [comment]
Well, it does not matter much if it runs on your computer. The goal is 
to make it run on your server ;)

You have to move the entire OS.js installation over to your server... 
just like how you would transfer any other file. I can't tell you how to 
do it... I don't own the server. So you'll have to figure this out yourself.

**Comment by petrk94** [comment]
Hello,
I have tried it to upload into the public/html/ directory and now its available on my server domain *.de/osjs/dist/ and /dist-dev/, but both are not working and show me the same error message.
Do I need to start something on the server too?
![osjs](https://cloud.githubusercontent.com/assets/19719052/22299325/ecf9ec42-e323-11e6-9ae6-1afdeabee596.PNG)

**Comment by andersevenrud** [comment]
You probably did not generate the apache htaccess file (if that is what your host uses), or your server does not support it.  That's just my guess since I don't see where the 404 occured.

More info: https://os.js.org/manual/server/php/#apache

**Comment by andersevenrud** [comment]
You can just generate the file and copy that by itself (dist/.htaccess). You don't have to rebuild anything.
