### ISSUE TITLE
Setting up Arduino yun

### ISSUE THREAD

**Issue by donnmphone** [os-js/OS.js#562]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.240.1/packages/target/ArduinoService/combined.js?35743
Line: 98:9
Message: Object expected
```

**Comment by andersevenrud** [comment]
Hi,

There seems to be an issue with some boards and the underlying webserver. There's an issue open on this here: #436

**Comment by andersevenrud** [comment]
See the latest comment in #436 on how to set up your board in an alternate way.
