### ISSUE TITLE
on Linux

### ISSUE THREAD

**Issue by donnmphone** [os-js/OS.js#563]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
showWIFIContextMenu/<@http://192.168.240.1/packages/target/ArduinoService/combined.js?61624:98:9
ArduinoService.prototype.pollWireless/<@http://192.168.240.1/packages/target/ArduinoService/combined.js?61624:193:7
ArduinoService.prototype.externalCall/<@http://192.168.240.1/packages/target/ArduinoService/combined.js?61624:269:7
doAPICall/<@http://192.168.240.1/osjs.js:1692:7
_Handler.prototype.__callXHR/data.onerror@http://192.168.240.1/osjs.js:8870:9
onReadyStateChange@http://192.168.240.1/osjs.js:1202:11

```

**Comment by andersevenrud** [comment]
Hi,

There seems to be an issue with some boards and the underlying webserver. There's an issue open on this here: #436

**Comment by andersevenrud** [comment]
See the latest comment in #436 on how to set up your board in an alternate way.
