### ISSUE TITLE
On setting up Arduino Yun

### ISSUE THREAD

**Issue by donnmphone** [os-js/OS.js#565]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
window::onerror()
Filename: http://192.168.240.1/packages/target/ArduinoService/combined.js?57011
Line: 98:9
Message: Object expected
```

**Comment by andersevenrud** [comment]
Hi,

There's an open issue on this here: #436
