### ISSUE TITLE
[VFS] Recycle Bin/Trash Can

### ISSUE THREAD

**Issue by taigrr** [os-js/OS.js#570]
## Expected behaviour
Can you add a Recycle bin to the UI context shell?

## Actual behaviour

Right now there's only a delete option.

edit: question clarification in response to first comment

**Comment by andersevenrud** [comment]
This is supported by the virtual filesystem, but has not been implemented in any of the provided server modules. So "yes" depending on what you mean by "adding" :P

**Comment by andersevenrud** [comment]
Before it can be added to the context, it needs to be implemented in the server modules. This is on the TODO, but not of any priority.

**Comment by andersevenrud** [comment]
I'm closing this as of now, because this will be an included feature in v3.
