### ISSUE TITLE
very bad trip yun os 

### ISSUE THREAD

**Issue by audiovizu** [os-js/OS.js#574]
Hello, I have just acquired a new  yun with a web interface 'os.js' I have full problems for  configuration or updating .Several times I rst the yun and I still have trouble and errors  Is there a simple procedure to find the original linux or arduino interface?

problem ajax/xhr error 0 ?

some  firewall port opened must be opened  before ?
http://192.168.10.204/osjs.js:8870:9 ??

/**---
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationArduinoPackageManager.prototype.callOpkg/<@http://192.168.10.204/packages/target/ArduinoPackageManager/combined.js?8420:282:13
ApplicationArduinoPackageManager.prototype.callAPI/<@http://192.168.10.204/packages/target/ArduinoPackageManager/combined.js?8420:254:16
doAPICall/<@http://192.168.10.204/osjs.js:1692:7
_Handler.prototype.__callXHR/data.onerror@http://192.168.10.204/osjs.js:8870:9
onReadyStateChange@http://192.168.10.204/osjs.js:1202:11

```

**Comment by andersevenrud** [comment]
Please read #436 for more information on this.
