### ISSUE TITLE
Incorrect URL is provided

### ISSUE THREAD

**Issue by taigrr** [os-js/OS.js#576]
## Expected behaviour

When you run the script referenced in 

#575 

You get a header at the beginning which says the following:
```
# Simply run this command and you're ready to go
#   curl -sS http://os-js.github.io/OS.js/installer | sh
```
## Actual behaviour

However, the URL provided doesn't work, it spits out HTML. 

Please update the URL to the one I provided in #575 ,

`
curl -sS https://www.os-js.org/installer | sh
`

**Comment by andersevenrud** [comment]
I've fixed this URL on the webpage. Thanks!
