### ISSUE TITLE
Ace

### ISSUE THREAD

**Issue by misha-marinenko** [os-js/OS.js#578]
'ApplicationAceEditor' (init()): ReferenceError: ace is not defined

**Comment by andersevenrud** [comment]
I can't help you if you don't provide any more information... so I'm going to assume you're trying to set OS.js up yourself -- then either of these can be the issue:

1. You did not clone the repository with the --decursive flag and the third party Ace module is missing.
2. Something went wrong while building.
3. It simply failed to load somehow.

You can use the browser developer tools to see if any errors was thrown

**Comment by andersevenrud** [comment]
Feel free to reopen if the problem persists, but then please add a bit of text explaining what you did and how this error occured.
