### ISSUE TITLE
Package api.js is not secure

### ISSUE THREAD

**Issue by msaqibansari** [os-js/OS.js#580]
## Expected behaviour
api.js in packages should be restricted from client.

## Actual behaviour
Anyone can view api.js of packages

## Steps to reproduce the error
Navigate following url in browser
https://demo.os-js.org/packages/default/CoreWM/api.js

## (Optinal) Browser and OS information
Any Browser

**Comment by msaqibansari** [comment]
I wrote database connection string and other business logic in api.js of my package that is being accessible by client that shouldn't be.
How do i restrict this file from user?

**Comment by andersevenrud** [comment]
This is only an issue with the demo-server.

The latest version of OS.js removes these files, and the upcoming version will have a dedicated area for the server files which are totally ignored by the build system.

**Comment by andersevenrud** [comment]
FYI I just released the latest version with the changes I mentioned.

http://community.os.js.org/t/update-version-bump-alpha93/128
