### ISSUE TITLE
OS.js ACE does not switch to specified file syntax highlighting, low amount of syntaxes available

### ISSUE THREAD

**Issue by XtremePlayzCODE** [os-js/OS.js#582]
## Expected behaviour
When saving to HTML, Python, or any language, the syntax highlighting should change to suit the language.

## Actual behaviour
When saving to any language other than JS, syntax does not change.

## Steps to reproduce the error
1. Open OS.js in the browser
2. Open ACE in the development tab
3. File -> Save as Python file
4. Type Python code, syntax is stuck on JS

## P.S.
Is there any way to add another syntax to OS.js's ACE package?

**Comment by andersevenrud** [comment]
Hi,

I think by default it builds Ace with support for all languages.

The issue here is that the editor does not update the Syntax Highlighting whenever a file is saved.

**Comment by XtremePlayzCODE** [comment]
Would this be an Ace issue or an OS.js issue? I believe more OS.js than Ace

**Comment by XtremePlayzCODE** [comment]
https://github.com/os-js/OS.js-extras/blob/master/AceEditor/main.js#L75 sets the syntax to JS automatically. Maybe if this can be changed to detect the extension and set it to the correct syntax? I'll try some stuff and open a pull if I get anything successful.

**Comment by andersevenrud** [comment]
I've made it so it runs this function whenever a file is loaded or saved: https://github.com/os-js/OS.js-extras/blob/master/AceEditor/main.js#L111

I'll see if I can't make it fully dynamic so it supports all languages at some point.

**Comment by XtremePlayzCODE** [comment]
Thanks for that, I was getting some errors with my version. I'll try and see if I can add more languages, thanks for the help!

**Comment by andersevenrud** [comment]
Yeah, it was not working for me at first as well. But I found some good information on Stackoverflow, and what you see there is the result of that :)

**Comment by XtremePlayzCODE** [comment]
Yep, SO is good!
