### ISSUE TITLE
[Automated Bugreport] YOUR TITLE HERE

### ISSUE THREAD

**Issue by Luisa12345** [os-js/OS.js#585]
**This bugreport was generated by OS.js:**

> An error occured while trying to launch: ApplicationNodeRed

> Application 'ApplicationNodeRed' preloading failed: 
/packages/default/NodeRed/main.js

## (Optinal) Browser and OS information

```
{"userAgent":"Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0","platform":"Win32","language":"en-GB","appVersion":"5.0 (Windows)"}
```

**Comment by andersevenrud** [comment]
You did not leave any information that is helpful in resolving this issue, so I'm going to close it. Feel free to re-open, but make sure to update the issue with ex:

* What application is this ?
* What did you do, and what did you expect ?
* Have you looked up the documentation ?

**Comment by Luisa12345** [comment]
right, I will


*Luisa Fabrizi*
Interactive art and design

Atelier Honigfabrik
Industriestraße 125
21107 Hamburg

0049-(0)17657926680
luisa-fabrizi.com

2017-04-20 12:24 GMT+01:00 Anders Evenrud <notifications@github.com>:
