### ISSUE TITLE
Google maps launch

### ISSUE THREAD

**Issue by neutrino2211** [os-js/OS.js#600]
Application 'ApplicationMap' preloading failed: 
/FS/read?path=home%3A%2F%2F%2F.packages%2FGoogleMaps%2Fmain.js

**Comment by andersevenrud** [comment]
Are you running latest version ? PHP or Node server ?

Running on a private server, or was this on the Demo ?

**Comment by neutrino2211** [comment]
This is a version i downloaded a month ago and running with node

On another note, i really like your project and i think it needs two things.

1. A browser

2. A willing community of developers making packages

Hopefully i have been helpful

Thank You

**Comment by andersevenrud** [comment]
@neutrino2211 

> 1. A browser

There's one available (experimental), but I have not gotten around to making an article on how to set up a proxy (which is *required* if you don't use Electron or NW)

> 2. A willing community of developers making packages

I hope so as well :)

**Comment by andersevenrud** [comment]
I'm going to close this, as this should be resolved in latest release (and most definitely is in the upcoming release).
