### ISSUE TITLE
Error uploading a large file

### ISSUE THREAD

**Issue by astronomer80** [os-js/OS.js#602]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: cbError is not a function
    at Object.onerror (http://192.168.1.145/osjs.js:8907:9)
    at XMLHttpRequest.onReadyStateChange (http://192.168.1.145/osjs.js:1202:16)
```

**Comment by andersevenrud** [comment]
Hi,

Can you rebuild with 'node osjs build:core --debug' and then reproduce the
error? It should give a bit more information.

29. mai 2017 09:04 skrev "Angelo Ferrante" <notifications@github.com>:

**Comment by andersevenrud** [comment]
Since there's been no response in almost two weeks I'm going to close this.

---

However, I'm not sure if this is a build you've set up or if you are on an Arduino. If you are on an Arduino please look at this issue: https://github.com/os-js/OS.js/issues/436#issuecomment-281183921
