### ISSUE TITLE
Nodejs 8.x compatibility

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [os-js/OS.js#608]
## Expected behaviour
No errors with Nodejs 8

## Actual behaviour
A lot of errors telling us that some headers are undefined in the `http` responses.

`UNCAUGHT EXCEPTION Error: Header "%s" value must not be undefined`

## Steps to reproduce the error

Install the latest version of Nodejs

## Warning

I found what was going on and I'm about to make a pull request. I just created this issue so that I can attach the pull Request to it so don't waste your time.

**Comment by andersevenrud** [comment]
Great! I've yet to upgrade my node and didn't even think that would be an issue :)

**Comment by andersevenrud** [comment]
I don't experience any problems, so I'm very interested in seeing what you've changed and get an idea of what the issue was :)

```
anders@andersarch:~/Projects/OS.js (master)*$ node --version
v8.1.0
```

**Comment by GuillaumeLeclerc** [comment]
It seems forbidden in version 8 to have undefined headers.

`.woff` files are not part of `300-mimes.json` config file. The result is an undefined `Content-Type` header that yields this error. I added `woff` mime type to the config and it works fine for me.

Did I miss anything ?

**Comment by andersevenrud** [comment]
> I found what was going on and I'm about to make a pull request.

> Did I miss anything ?

I don't know... you tell me :D
