### ISSUE TITLE
Arduino YUN - Configuration Wizard

### ISSUE THREAD

**Issue by mrcsalomao** [os-js/OS.js#613]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
Error
   at Anonymous function (http://192.168.23.109/packages/target/ArduinoWizardSettings/combined.js?49370:482:29)
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436 (#436 (comment) )
