### ISSUE TITLE
Upgraded arduinoos on Yun with some error messages

### ISSUE THREAD

**Issue by johnchen16** [os-js/OS.js#614]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
http://waterworks2.local/packages/target/ArduinoPackageManager/combined.js?62805:282:28
http://waterworks2.local/osjs.js:1692:19
onerror@http://waterworks2.local/osjs.js:8870:22
onReadyStateChange@http://waterworks2.local/osjs.js:1202:23
```

**Comment by andersevenrud** [comment]
For errors on Arduino, please look at this issue: #436 (#436 (comment) )
