### ISSUE TITLE
Calculator input problems on mobile

### ISSUE THREAD

**Issue by jbourdale** [os-js/OS.js#637]
## Expected behaviour

I'm trying to do use the calculator on my mobile, just a simple operation.

## Actual behaviour

But when i tap on a key, multiple key hit are recorded.

## Steps to reproduce the error

1. Reach an OS-js installation on mobile
2. Launch the default installed calculator
3. Try to tap something

**Comment by andersevenrud** [comment]
I can confirm that there is some issue there. Not sure why multiple events are fired, but I'm guessing it has something to do with how the browser handles `<button>` element and that I'll need to add a preventDefault or something. Thanks!

**Comment by andersevenrud** [comment]
Sorry...I totally forgot about this. I've scheduled to look at this on Friday.

**Comment by andersevenrud** [comment]
This should be fixed now.... finally. This was not easy to track down!

Even worse, behaviour in Chrome has changed somewhat, so I had to solve some issues with other devices as well as the device emulator. Gah.

It's going into master as soon as I have this merge ready.

**Comment by andersevenrud** [comment]
:shipit:
