### ISSUE TITLE
A part of submenu disappears

### ISSUE THREAD

**Issue by perfectstrong** [os-js/OS.js#638]
1. Change the position of dock to the bottom.
2. The submenu will not appear all (hidden after the taskbar of outer window)
![issue](https://user-images.githubusercontent.com/23375518/31671686-d4d46040-b35a-11e7-97d7-d6f1ea37957f.png)

**Comment by andersevenrud** [comment]
This looks like a regression from a change I've made at some point. I have a function that clamps the position, but obviously it's not working correctly.

I'll look into it. Thanks!

**Comment by andersevenrud** [comment]
I've added a patch for this in the `development` branch. Feel free to test it out.

**Comment by perfectstrong** [comment]
The patch work like a charm.

**Comment by andersevenrud** [comment]
Now in master :)
