### ISSUE TITLE
Wrong context menu

### ISSUE THREAD

**Issue by perfectstrong** [os-js/OS.js#639]
## Opening proper context menu of an icon in task bar

Right click on an icon inside taskbar.

## Wrong context menu

The context menu of taskbar will open instead of the icon's. For example with user icon:

![issue-wrongcontextmenu](https://user-images.githubusercontent.com/23375518/31762105-7bbef496-b4ba-11e7-8ed7-3a859145ed88.png)

It should be a menu of "Disconnect".

**Comment by andersevenrud** [comment]
This is a strange one. For some ungodly reason the contextmenu event does not trigger inside of a panel element. I'll have to do a bit of digging here...

**Comment by andersevenrud** [comment]
Oh, nevermind. It seems that the event somehow propagates and creates two overlapping menus! :)

**Comment by andersevenrud** [comment]
Should be fixed in `development` branch now.

**Comment by perfectstrong** [comment]
The problem is still there.

**Comment by perfectstrong** [comment]
It's fixed now.

**Comment by andersevenrud** [comment]
Now in master :)
