### ISSUE TITLE
howto install this on heroku

### ISSUE THREAD

**Issue by misha-marinenko** [os-js/OS.js#647]
## Expected behaviour

I'm trying to install OS.js on heroku.

## Actual behaviour

All installs OK npm: OK, runs: OK but when im tying to access os.js from `node osjs run --port $PORT` returns error...

# HELP...

**Comment by andersevenrud** [comment]
What "error" does it return ?

**Comment by andersevenrud** [comment]
I'm closing this due to lack of response.

Feel free to re-open if you get back to this.
