### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by comgram** [os-js/OS.js#648]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
http://192.168.0.100/packages/target/ArduinoPackageManager/combined.js?24935:282:28
http://192.168.0.100/osjs.js:1692:19
onerror@http://192.168.0.100/osjs.js:8870:22
onReadyStateChange@http://192.168.0.100/osjs.js:1202:23
```

**Comment by andersevenrud** [comment]
Try using Luci instead: http://arduino-ip/cgi-bin/luci

Ref: #436
