### ISSUE TITLE
Package Target Preview Error

### ISSUE THREAD

**Issue by Mantraxyz** [os-js/OS.js#663]
An error occured while trying to launch: ApplicationPreview

> Application 'ApplicationPreview' preloading failed:  /packages/target/Preview/combined.js?3487

**Comment by andersevenrud** [comment]
Hi,

All of the issues you are reporting comes from the same problem. Some boards have some issues with networking (connection dropout).

Try using Luci instead: http://arduino-ip/cgi-bin/luci if you want to configure the board if the problem perists (even after upgrade).

Reference issue: #436
