### ISSUE TITLE
Menu items run below the screen when menu bar is at the bottom

### ISSUE THREAD

**Issue by johndevor** [os-js/OS.js#666]
And the menu is also covering the bottom bar.

![screen shot on 2018-01-15 at 10 3a03 3a19](https://user-images.githubusercontent.com/75827/34948527-6d607030-f9db-11e7-9316-a9664e22e96d.png)

**Comment by andersevenrud** [comment]
Hi. Sorry for late reply, I forgot to make a notification for this. Could you try the `development` branch and see if this has not been already solved ?

**Comment by johndevor** [comment]
Yes, I can confirm this is fixed in development branch.

**Comment by andersevenrud** [comment]
Thanks for letting me know :+1:
