### ISSUE TITLE
Maximize callback not fired / animation doesn't run

### ISSUE THREAD

**Issue by alalonde** [os-js/OS.js#667]
## Expected behaviour

When maximizing a window (default settings), it is animated, and when complete, any associated callbacks are fired.

## Actual behaviour

There is no animation, and the callback isn't called

## Steps to reproduce the error

1.  bind to the 'maximize' event e.g. `this._on('maximize', this.resizeHandler);`
2. maximize the window
3. notice that when restoring the window, the animation runs and callback *is* fired.

**Comment by andersevenrud** [comment]
Not exactly sure why this happened, but apparently using 'mouseup' causes this problem, delaying the callback (with a setTimeout) to the next tick solved it magically. The animation now plays and callback is called.

I'll have to dig a bit deeper in this, but you can use the `development` branch. I'll merge this into master this weekend.

**Comment by alalonde** [comment]
Tested, works, thanks!
