### ISSUE TITLE
Applications and mutable global state

### ISSUE THREAD

**Issue by alalonde** [os-js/OS.js#668]
I did a bit of searching around for conversations covering this, but didn't find much, so here goes:

An elephant in the room with this sort of project is that applications are running in the same `window`, and thus technically have access to any other application's data and state.  For most apps I don't see this being a problem, but there are some pretty common use cases that would cause problems. For example, what happens when Application A uses React version 15, and Application B uses React version 16?  Based on the order of loading, it is unclear which would take preference, and having two versions (or more!) would create havoc.  

The only way around this that I see would be for each application to run in its own `<iframe>` (like [this project](https://ozoneplatform.github.io/ozone-website/ozp.html)), but that would certainly cause other problems and possibly limit the ability of applications to talk to one another and the parent window.

I'm sure you've put some thought into this, but IMO this issue alone would keep OS.js from having a really useful pluggable architecture.

**Comment by andersevenrud** [comment]
> An elephant in the room with this sort of project is that applications are running in the same window, and thus technically have access to any other application's data and state.

Yes. But this depends on how the application is made. You don't have to expose everything to the application class instances.

>  For example, what happens when Application A uses React version 15, and Application B uses React version 16?

OS.js uses Webpack for building its apps. So if you bundle all your dependencies, this is not an issue, unless the libraries used share something in the global namespace.

> this issue alone would keep OS.js from having a really useful pluggable architecture.

v3 will have a very different architecture. Based on modern concepts. I built most of this stuff over ten years ago (as a hobby project), so there's lots of areas that needs improvements, for sure, hence v3.

**Comment by andersevenrud** [comment]
... sorry if the response was a bit lackluster. I was just about to get ready for bed and thought I'd answer it quickly. I'll try again tomorrow :P

**Comment by alalonde** [comment]
Yes, some good app dev practices around closures can mitigate the whole data exposure issue.  I mentioned React because I thought it didn't support multiple versions on the same page, but looks like that [is not the case](https://stackoverflow.com/questions/38783430/is-it-possible-to-run-two-different-versions-of-reactjs-on-the-same-page) if e.g. each app indeed provided their own version.

I would be very interested to hear your thoughts about a new architecture, if you're far enough along to share, of course :D

**Comment by andersevenrud** [comment]
Yes, bundling solves this issue as long as the libraries (or frameworks) do not use the `window` namespace or has some shared root namespace or something like that. For older libraries this can cause a mess, for sure!

Looks like you've pretty much gotten an answer, so I don't have to rewrite an answer. Yay :)

I'll write a post about v3 when I got something to share. It's mostly been going on in the backround in silence, heh. But I might have something really soon. I'll make sure to let you know about it when it's up ;)

**Comment by jcrben** [comment]
What do you think about using or allowing typescript for v3?

Also, is there a display manager (something like https://github.com/sddm/sddm) in in this project?

**Comment by andersevenrud** [comment]
@jcrben 

> What do you think about using or allowing typescript for v3?

I'm sure that could be worked out.

> Also, is there a display manager (something like https://github.com/sddm/sddm) in in this project?

I have a somewhat working Debian image that runs OS.js, but there's no DM in there.

This is something I really want to look into for v3.

**Comment by andersevenrud** [comment]
I'm closing this issue now because of https://github.com/os-js/OS.js/issues/671 .

As for the TypeScript stuff, this will get attention there :)
