### ISSUE TITLE
JUST The Desktop and Window Design -- Not the NodeJS backend.

### ISSUE THREAD

**Issue by Seanld** [os-js/OS.js#669]
This isn't necessarily an on-topic/contribution question, so sorry. I just couldn't find any resources that helped me with this problem, so I figured I'd go straight to Issues since y'all know the most.

OS.js is the first of its kind, as far as I can tell. I really like it, and I think it's awesome that someone had the exact same idea as me. The only problem is that I want to write my own backend in Python. I only had a need for a framework that handled the designs of the windows and the desktop (kind of like a Bootstrap for making desktops in web technologies). But OS.js comes with the NodeJS backend/server, which I don't want.

Is there something equivalent to OS.js that would just allow me to _design_ the desktop & windows, but not with a backend included? Can I do that with OS.js somehow?

I know this isn't very well explained, but it's hard to get my point across when I'm typing it. If you have questions with what I mean, then I'm totally fine to elaborate.

Thank you!

**Comment by andersevenrud** [comment]
Hi,

You can do a `node osjs build --standalone` to make a standalone build (which basically just changes a few configuration entries at build time). This means you can use the `dist/` directory without having any server attached.

I think that should solve your issue.

**Comment by andersevenrud** [comment]
You can also re-configure it to always build as standalone:

```
# See defaults in src/conf/000-base.json
node osjs config:set --name=connection --value=standalone
node osjs config:set --name=authenticator --value=standalone
node osjs config:set --name=storage --value=standalone
node osjs build:config
```

**Comment by Seanld** [comment]
@andersevenrud I will try this out. Thank you for your quick reply!

**Comment by andersevenrud** [comment]
I think that you got your answer, so I'm closing this issue. Feel free to re-open :)

You might be interested in this issue btw: https://github.com/os-js/OS.js/issues/671
