### ISSUE TITLE
[v3] Upcoming Release

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#671]
**See the [manual](https://manual.os-js.org/v3/) for lots of more information**.

This is the master issue for OS.js :tada: v3 :tada: , which is a work-in-progress rewrite. **This issue will be updated at random**.

[Community announcement](https://community.os-js.org/t/os-js-v3-announcement/210)

---

My main goal of this release is to significantly reduce complexity, completely modularize, decrease build times, easier customization and application development.

---

*Please note that the code is not public at the moment. See the TODO list below. All repositories will be transferred to the os-js Org and automatically made public once Stage I is done*

## Changes

All rewritten. Now uses modern ES features wherever possible (even on server-side).

Visually, not much has changed, but behind the scenes it's all brand new.

No backward compability is planned. Also **semantic versioning** will now take place as of this release.

### Simplified

Overall design is now much simpler, much easier to customize and many orders of magnitude faster to build (and faster overall performance). The design now also embraces functional programming.

I'll write more about this later.

### Modularized

Instead of having a monolithic repository, all the different components are now separated into their own (npm) pacakges. The base repository now only consists of a basic scaffold project that allows you to pick-and-choose (and replace) all modules.

* `@osjs/osjs` - The base project
* `@osjs/cli` - The CLI utilities and build scripts etc
* `@osjs/common` - Things used throughout everything
* `@osjs/client` - The Client core
* `@osjs/server` - The Server core
* `@osjs/gui` - GUI Components
* `@osjs/dialogs` - Dialogs
* `@osjs/panels` - Panels
* `@osjs/standard-theme` - The default GUI theme

All packages comes in the form of `@scope/osjs-{name}-{type}`.

### Compability

Bumped Node to version 8.

### Service Providers

All features are now bootstrapped via *Service Providers*. You can use a number of default provided ones or write your own using a simple interface.

### Event Bus-es

Bus-es for everyone! Pretty much all components of OS.js now uses a standard event interface.

### Applications and UI

By default OS.js now uses [Hyperapp](https://github.com/hyperapp/hyperapp) (see #628).

> Hyperapp is a JavaScript library for building web applications.
>
>Minimal — Hyperapp was born out of the attempt to do more with less. We have aggressively minimized the concepts you need to understand while remaining on par with what other frameworks can do.
>
> Functional — Hyperapp's design is inspired by The Elm Architecture. Create scalable browser-based applications using a functional paradigm. The twist is you don't have to learn a new language.
>
> Batteries-included — Out of the box, Hyperapp combines state management with a Virtual DOM engine that supports keyed updates & lifecycle events — all with no dependencies.

The overall design of the applications now have changed. You no longer need to extend base classes; just one function to bootstrap your application. 

GUI Components are also provided via Hyperapp.

Your application state no longer lives "inside" the Application Class instance, so your data won't leak.

**Please note that Hyperapp is completely optional... you can still use your own favorite framework. And I would love it if people ported the components**

### Server

You can now much easier tap into the server.

PHP Support has been dropped. WebSocket is now default.

### Configuration

Now done with regular JavaScript instead of `.json` files.

### CLI / Building

Still very similar, but the tasks have changed.

The `watch` task now watches *everything* so you don't need to run separate processes for everything.

`NODE_ENV` is now also respected, which in previous versions was controlled with command arguments.

*More about this later*.

### Misc

- The `WindowManager` has been removed as the service providers now covers all the functionality.
- Window behavior can now be overridden per-instance or globally.
- `Scheme` has been completely abandoned.
- You can now also customize the "root DOM element" of which OS.js lives inside. This allows for easy embedding or customized viewports.

**Comment by andersevenrud** [comment]
Oh, another thing that is a big change is the application/window states and mutability. Since you now write applications in its own scope, there's no chance of states leaking between applications. If you want to share states, you can use event bus-es.

This is an (early -- **not final**) example of an application, which should give you an idea of how it now works:

```javascript
import metadata from './metadata.json';

import {
  h,
  app
} from 'hyperapp';

import {
  Box,
  BoxContainer,
  Button,
  Progressbar
} from '@osjs/gui';
const view = (core, proc, win) =>
  (state, actions) => h(Box(h), {}, [
      h(BoxContainer(h), {}, [
        h(Button(h), {
          label: 'Create Notification',
          onclick: () => actions.createNotification()
        }),
        h(Button(h), {
          label: 'Create Window',
          onclick: () => actions.createWindow()
        })
      ]),
      h(BoxContainer(h), {}, [
        h(Progressbar(h), {value: state.progress})
      ])
    ]);

const actions = (core, proc, win) => {
  return {
    createNotification: () => state => {
      core.make('notification', {
        title: 'Hello World!',
        message: 'This is a notification'
      });
    },
    createWindow: () => state => {
      proc.createWindow({
        title: 'New Window'
      }).render();
    },
    increment: () => state => {
      const progress = (state.progress + 1) % 100;
      return {progress};
    }
  };
};

OSjs.make('packages').register(metadata, (core, args, options) => {
  const proc = core.make('application', {
    args,
    options,
    metadata
  });

  const state = {
    progress: 50
  };

  proc.createWindow({
    id: 'TestWindow',
    title: 'Hello World!',
    state: {
      dimension: {width: 400, height: 400},
      position: {left: 200, top: 200}
    }
  })
    .on('destroy', () => proc.destroy())
    .on('render', (win) => win.focus())
    .render(($content, win) => {
      const a = app(state,
          actions(core, proc, win),
          view(core, proc, win),
          $content);
      let interval = setInterval(() => a.increment(), 100);
      win.on('destroy', () => clearInterval(interval));
    })
  return proc;
});
```

Results in:

![screenshot_2018-02-17_21-38-54](https://user-images.githubusercontent.com/161548/36345467-5e6cab60-142b-11e8-912c-52c2f209d73f.png)

@alalonde You might be interested in this :)

**Comment by junland** [comment]
Will v3 still have options to build standalone (E.g Nginx, Apache, etc.)? Also is there anything changing with the build system?

**Comment by andersevenrud** [comment]
@junland Yes, you can still build it standalone :)

The build system will work pretty much the same, just improved. There's a small paragraph in the issue description about this.

**Comment by junland** [comment]
Ahhh okay, guess I missed it. Sounds good!

**Comment by andersevenrud** [comment]
@junland I might put up a demo and all the sources this weekend. I can let you know if it's of any interest :)

**Comment by junland** [comment]
@andersevenrud sounds good! I'd be happy to try it out.

**Comment by mds325** [comment]
We could change the source code to typescript to have a Hard Typing system and that could give us a better development experience. @andersevenrud

**Comment by andersevenrud** [comment]
@junland Sorry, but I totally forgot. The sources are now up on this org. account :)

**Comment by andersevenrud** [comment]
@mds325 I don't think I'll make any of the base packages in TS as they are very small, but I will however provide typing [definitions] (`.d.ts`) for anyone that wants to develop using TS .

Also, if things get to a complex point, then TS or Flex will be looked into :)

**Comment by andersevenrud** [comment]
Everything is now up on Github, though not published to npm. So if anyone wants to test this out you'll have to **manually** override `package.json` files and use `npm link` to set things up.

*I will update this thread when things are published on npmjs.org* :)

Modules:

* https://github.com/os-js/osjs-core
* https://github.com/os-js/osjs-gui
* https://github.com/os-js/osjs-dialogs
* https://github.com/os-js/osjs-server
* https://github.com/os-js/osjs-cli
* https://github.com/os-js/osjs-panels
* https://github.com/os-js/osjs-standard-theme

Packages:

* https://github.com/os-js/osjs-example-package
* https://github.com/os-js/osjs-xterm-package
* https://github.com/os-js/osjs-textpad-package
* https://github.com/os-js/osjs-filemanager-package

**Comment by andersevenrud** [comment]
All core modules now up on npmjs.org: https://www.npmjs.com/org/osjs

I'll leave the packages for later... they're not hard to set up anyway.

Not sure what schedule I'm going to set for publishing yet, but since I started on this day... I'll make it every saturday.

**Comment by andersevenrud** [comment]
A community member was asking about how to easily prototype applications, and it brought up something interesting.

I put together these bundles so you can do this in whatever platform you want, a basic example being: https://jsfiddle.net/andersevenrud/m94jt9ct/5/

If you want to test this out yourself, just use these resources:

* https://www.os-js.org/testing/osjs.js
* https://www.os-js.org/testing/osjs.css

At some point I'll probably set up proper CDN for this with automatic building. These links are made from my local machine using Webpack and these files:


```js
// index.js
import * as gui from '@osjs/gui';
window.OSjs = window.OSjs || {};
window.OSjs.GUI = gui;
```

```css
// index.scss
@import "@osjs/gui/index.scss";
@import "@osjs/standard-theme/index.scss";
```

**Comment by andersevenrud** [comment]
I've started a draft of the basic manual here: https://github.com/os-js/OS.js/wiki/v3-documentation

I also released proper tagged versions of everything today (and updated dependency definitions), so things should be smooth sailing.

Please note that I have not polyfilled anything yet, so iOS/Android, Opera and IE will probably not init properly.

**Comment by andersevenrud** [comment]
Thought I'd share the progress with you guys. Here's a list of currently available features as of today's release:

* Extensions via configuration
* Window media queries
* Theme support (w/icons)
* Dialog support (w/default set of dialogs)
* Panels support (w/default set of panel items)
* Notifications, Tray icons, 
* GUI Components for Hyperapp (note: these are not finished)
* Authentication support (note: no modules yet published)
* VFS Transports and Mountpoints (note: only system module provided at the moment)
* Session saving and loading
* WebSockets and HTTP requests for applications
* Custom distribution (customization, embedding, etc)
* Basic touch input support
* ... and more

There's been some more work in the manual as well, so it should be fairly easy to play around with these features.

Next up, I'll probably be focusing on finishing the GUI components and add add some authentication modules.

*Note* The `@osjs/core` module was renamed to `@osjs/client`.

**Comment by andersevenrud** [comment]
Another quick update:

* Now works on Safari (and iOS) and some other browser quirk fixes
* Fixed the default theme not compiling
* Support custom `Auth` adapters
* Support custom `Settings` adapters
* Login customization support
* Add default client+server adapters for settings and auth
* Standalone mode
* And your usual suspects as dependency updates and general improvements
* Started on implementation of applying settings (so I'll have a settings app ready soon)
* Created `@osjs/common` and moved code shared between client/server there

I've also added two auth adapters:

* https://github.com/os-js/osjs-sqlite-auth
* https://github.com/os-js/osjs-pam-auth

Manual has been updated with relevant documentation.

**Comment by andersevenrud** [comment]
@filips123 

> What about some web browser. (I don't know if this is possible and this is just an idea

It's somewhat possible. I'll look into the project you linked.

> Also, add some mail client and MS Office like programs.

That's something I'd like to do, if I can find some time.

> In the top bar, show icon instead of text "Menu", like in v2.

Icon will be applied down the line.

> Some apps, like Calculator, don't have icons in the menu. Intend, they have OS.js icon.

Yes, I'm aware. None of the apps are finished for v3.

> Tab key don't work in text editors.

Noted.

> Right click doesn't work. It doesn't do anything.

It's not supposed to (at least yet).

> When I move window around, the title text of window is selected. Also, mouse cursor is changed to moving cursor.

I thought I had disabled `user-select` when a window is moved. I'll look into that. The cursor is supposed to change.

> Window names in top bar are cropped.
> The icons in the window are too close together and they are overlapping.

Yes, and several other minor UI glitches. It's not done yet.

> Resizing window doesn't work.

It does, just only from south-east at the moment.

> File manager doesn't work. It opens alert with text "TypeError: HEAD or GET Request cannot have a body.".

I'll look into that.

> Maybe there are also some other bugs. Also, some features and functionalities from v2 don't work in v3.

Most likely yes. It's a work in progress.

**Comment by andersevenrud** [comment]
@filips123 I've fixed the following (and will release new version this weekend):

* Icon added to the menu in panel
* The text selection problem while moving should be fixed
* Fixed overlapping/cut-off window controls
* Issues with tab on certain inputs

If you discover something else, please create an issue in https://github.com/os-js/osjs-client :)

**Comment by andersevenrud** [comment]
@filips123 The issue with `HEAD or GET Requests cannot have a body` should also be fixed. So stay tuned for that :)

**Comment by andersevenrud** [comment]
@filips123 I just published the updates.

**Comment by andersevenrud** [comment]
Been a while since I've published an update here. A lot has happened, so I thought I'd note down a list of completed features as of now:

* Server w/Websocket, authentication, etc.
* Server authentication and group support
* CLI w/building and plugin support
* Build system over Webpack w/simplified API
* Panels w/library and custom integration support
* Dialogs w/library and custom integration support
* VFS w/mountpoints and custom integration support
* Localization support (No translations yet)
* Login w/customization support
* Session w/save and restore
* Settings incl. applications etc.
* Notifications and Tray Icons
* Application socket/http support
* Application worker support
* Windows w/all the things you'd expect
* Basic touch suport and support for screen-size based optimizations
* Themes
* Provide modules for authentication
* Provide examples for packages and service providers
* Manual (with pretty good coverage atm)
* Support all platforms for building and development

I probably forgot something...

Some features currently under development/planned:

* Put i18n strings in translation file(s)
* Re-sizable windows from all corners
* Finishing up GUI library
* Widget support
* Animations
* More apps. Including one for managing user settings (finally)
* More themes

Thanks to everyone that has reported bugs and requested features. Most of the features in v2 is now in v3! So... I guess it's not that far off from going into a beta :)

**Comment by andersevenrud** [comment]
Time for another update :slightly_smiling_face: 

I've added the following since last post:

* Translation file support
* Support custom Login (adapter)
* GUI Library basic components now stable
* GUI Library general improvements
* Compability (should now render correctly on Safari and iOS)
* Updated all applications to use latest updates
* CLI improvements
* CLI can now generate packages via `package:create`
* Extensive manual updates, now also in master
* More work on Widgets
* A [PM2 stats provider](https://github.com/andersevenrud/osjs-pm2-provider) now available

**Comment by andersevenrud** [comment]
Another quick one for 'ya :)

Updates:

* Service Providers can now have dependencies and resolves upon boot
* VFS abstraction updated to cover non-standard filesystems (i.e. not a traditional folder structure)
* VFS now supports watching (client can reload things based on filesystem changes, disabled by default)
* Added the 'visibility' attribute on Windows (controls if can be showed in ex window list in panel)
* GUI improvements
* CLI improvements
* Logging improvements
* Manual updates
* All relevant dependencies updated
* All relevant packages updated

New applications:

* https://github.com/os-js/osjs-draw-application
* https://github.com/os-js/osjs-ace-application
* https://github.com/os-js/osjs-strophejs-application

New providers:

* https://github.com/os-js/osjs-gapi-provider

VFS adapters:

* https://github.com/os-js/osjs-gdrive-adapter

**Comment by filips123** [comment]
What about Docker image? There was Dockerfile in v2.

**Comment by andersevenrud** [comment]
@filips123 

>What about Docker image and CI integration? 

I can provide a docker setup, sure. The procedure is basically the steps mentioned in the installation documentation, but having a set of `docker-compose`  configurations might be handy (to pick if you want auth by default for example). What would you want to see ?

CI will be set up once I commit all tests and have my org account properly set up in third parties.

> Also, what about other cloud storage adapters like OneDrive, Dropbox, Box...

I just added basic Google Drive support. Others will come when I get to it (or someone else steps up).

> Will there be build with all applications, providers and adapters included?

I could possibly provide a CLI command to make a "default setup" with a selection of packages, etc. What do you think ?

> Also, could you make online v3 demo?

Yeah. I've set up a new server that I'll migrate the web-page to, as well as set up a v3 demo. This will probably involve Docker :)

**Comment by filips123** [comment]
> I can provide a docker setup, sure. The procedure is basically the steps mentioned in the installation documentation, but having a set of `docker-compose` configurations might be handy (to pick if you want auth by default for example). What would you want to see ?

There should be something like in v2. And there should be support to install and set up other themes, adapters and providers.
You should also include support for Vagrant.

> I could possibly provide a CLI command to make a "default setup" with a selection of packages, etc. What do you think ?

Yes, you should create command to build and install default packages. Maybe something like `npm install && npm run build:default`?
Will standalone builds builds and webhosts (https://manual.os-js.org/installation/) be supported in v3?

**Comment by filips123** [comment]
I just want to remind you that some of my bugs are still not resolved. Some of those bugs were already resolved, but there is still a problem. I also include some new suggestions and bugs.

### Suggestions:

> * What about some web browser.
> * Also, add some mail client and MS Office like programs.
> * Windows name could be at center of the window, like in v2.

* Add settings application.
* Add support for creating files and folders on desktop.
* You should add eraser to Draw application.
* What about search bar and process manager?
* There could be user switcher and support to use different login adapters at same time.
* What about some command line?
* What about games?
* Add button for full screen mode.

### Bugs:

> * Some apps, like Calculator, don't have icons in the menu. Intend, they have OS.js icon.
> * Right click doesn't work. It doesn't do anything.
> * When I move window around, the title text of window is selected. Also, some of text labels in applications are also selected.
> * Window names in top bar are cropped. They should be cropped only if there is no enough space.
> * Resizing window doesn't work. It should in all directions.

* Calculator application incorrectly displays that `3 + 3 * 3 = 18`. It is `3 + 3 * 3 = 3 + (3 * 3) = 12`.
* Application titles and labels are sometimes selected.
* Canvas in Draw application should be also resized with dragging it.
* When opening the OS.js, login page is shown for about 0.25 seconds even if there is no custom login adapter installed.
* Also, there is an error while installing themes and applications. See #688.

### Questions:

* Where are files from File Manager stored? Can they be accessed by hosting OS?

### Screenshots:

**Selected title text while moving:**
![](https://user-images.githubusercontent.com/16626308/40488678-a053700e-5f67-11e8-919f-49ea62e286cc.png)

**Cropped window names:**
![](https://user-images.githubusercontent.com/16626308/40488941-2c43d5ae-5f68-11e8-9b94-06d55687a038.png)

**Selected text labels:**
![](https://user-images.githubusercontent.com/16626308/42723883-4a1372c4-8768-11e8-9d9b-73cd2beefb38.png)

**Comment by andersevenrud** [comment]
@filips123 As to your questions about adding all of these applications. Yes, I want to have it all. But I can't possibly do all of that myself.

Also, please don't use this thread for bug-reporting. Place issues in their respective repositories. Here's a complete list: https://manual.os-js.org/v3/resource/official/

> Add settings application.

I've mentioned in this thread that it is coming.

> support to use different login adapters at same time.

That's a good suggestion!

> Some apps, like Calculator, don't have icons in the menu. Intend, they have OS.js icon.

Yes, I just haven't added the icons in the metadata yet.

> Right click doesn't work. It doesn't do anything.

I don't know what exactly you expect it to do....

> When I move window around, the title text of window is selected. Also, some of text labels in applications are also selected.

> When I move window around, the title text of window is selected. Also, some of text labels in applications are also selected.
> Application titles and labels are sometimes selected.

I actually can't reproduce this on my machines. I'll maybe have a look at some other setups. Are you sure your theme and dependencies are up to date ? Also, maybe there are just spesific spots this triggers ? If so, some more info would be appreciated.

> Canvas in Draw application should be also resized with dragging it.

> When opening the OS.js, login page is shown for about 0.25 seconds even if there is no custom login adapter installed.

This is because the login always shows (there's a difference between the adapter and UI module), but by default is set up to autofill with demo user. So depending on the connection etc. it might show for longer.

Maybe setting it to be hidden if autologin is enabled is better - then just display it if an error occured.

> Also, there is an error while installing themes and applications. See #688.

This has been solved.


> Where are files from File Manager stored? Can they be accessed by hosting OS?

All files and filesystem operations goes via the virtual filesystem. The `OSjs` mountpoint is the `dist` directory, and `Home` is `vfs/{username}`. Technically you can host your files anywhere.

**Comment by andersevenrud** [comment]
@filips123 

> Cropped window names:

I actually improved this yesterday. Comes out in the next update :)

https://github.com/os-js/osjs-panels/commit/230788ad8ebb194bdbba8bcc7f5a98b5e7b843c4

**Comment by filips123** [comment]
> > Right click doesn't work. It doesn't do anything.
> 
> I don't know what exactly you expect it to do....

It should open context menu depending on content that was clicked. Like in real OS and Os.js v2.

![Context Menu 1](https://user-images.githubusercontent.com/16626308/42724134-f4748718-876c-11e8-9d78-f76b60878fa5.png)

![Context Menu 2](https://user-images.githubusercontent.com/16626308/42724151-46c2af4a-876d-11e8-9631-3eb4687e4d92.png)

---

> > When I move window around, the title text of window is selected. Also, some of text labels in applications are also selected.
> > Application titles and labels are sometimes selected.
>
> I actually can't reproduce this on my machines. I'll maybe have a look at some other setups. Are you sure your theme and dependencies are up to date ? Also, maybe there are just spesific spots this triggers ? If so, some more info would be appreciated.

I currently can't test this on my local machine, so I am using [Codenvy.io](https://codenvy.io/) workspace using Node.js stack. I have Git v2.1.4, Node.js v8.11.1 and NPM v6.2.0 installed.
I've made completely fresh installation of OS.js v3. I've also installed standard theme and example application.

I've tested this with different browsers on Windows 10. On Chrome, it works normally (no text is selected). On Firefox and Edge, text is selected. On OS.js v2, this worked in all browsers.

I think the problem is `user-select`. On Edge and Firefox, it requires prefix. See https://developer.mozilla.org/en-US/docs/Web/CSS/user-select.

---

Also, will there be support for choosing application to open file, like in v2?
![Choose Application](https://user-images.githubusercontent.com/16626308/42724142-26bcf408-876d-11e8-9423-599150ff5603.png)

**Comment by andersevenrud** [comment]
> It should open context menu depending on content that was clicked.

There's a contextmenu on the desktop (albeit a simple one) and the file views, but on the panel it has not been added yet (some panel functionality also not done).

> On Firefox and Edge, text is selected.'

Okay, thanks. I have should have autoprefix set up in Sass, but I'll look into it.

> Also, will there be support for choosing application to open file, like in v2?

This is supported as of latest release (if you try to open a file that has multiple apps supported), but not added to the context menu. I also need to add the permanent checkbox thingy.

**Comment by andersevenrud** [comment]
@filips123 

> It should open context menu depending on content that was clicked.

There's a contextmenu on the desktop (albeit a simple one) and the file views, but on the panel it has not been added yet (some panel functionality also not done).

> On Firefox and Edge, text is selected.'

Okay, thanks. I have should have autoprefix set up in Sass, but I'll look into it.

> Also, will there be support for choosing application to open file, like in v2?

This is supported as of latest release (if you try to open a file that has multiple apps supported), but not added to the context menu. I also need to add the permanent checkbox thingy.

**Comment by andersevenrud** [comment]
@filips123 

>On Firefox and Edge, text is selected.'
>> Okay, thanks. I have should have autoprefix set up in Sass, but I'll look into it.

Seems like I was wrong :blush: https://github.com/os-js/osjs-client/commit/5db9ca447f11a98c8f4fc0f0a0e9bce206b1983e

**Comment by andersevenrud** [comment]
@filips123 I've added a basic Docker setup now https://github.com/os-js/OS.js/commit/c86fba8c680f71a2a7d2d29a15dc4c0e320dc789

**Comment by andersevenrud** [comment]
@filips123 I also published a new version of `@osjs/client` with the following:

* Fixed `user-select`
* Fixed login not blocking boot procedure
* Hide the login UI if autologin is set to prevent the "blinking"
* Better handling of window zIndex

I also published the `@osjs/panels` package with changes mentioned earlier.

**Comment by andersevenrud** [comment]
@filips123 Also a new `@osjs/standard-theme` build to center the window title ;)

**Comment by filips123** [comment]
> Also a new @osjs/standard-theme build to center the window title ;)

Maybe this could be in settings so users could configure this.

---

Also, maybe you could also support icons on the left and Windows-style icons. This should be in settings.

**Comment by andersevenrud** [comment]
@filips123 

> Maybe this could be in settings so users could configure this.

Yes, that's a given. You can also change theme with the desktop context menu.

> Also, maybe you could also support icons on the left and Windows-style icons. This should be in settings.

Not sure what you mean by "icons on the left" and "widows style icons".

**Comment by filips123** [comment]
> Not sure what you mean by "icons on the left" and "widows style icons".

With "icons on the left" I meant that the window icons would be on the left side of window. Currently, they are on the right.
![icons on the left (from ubuntu)](https://user-images.githubusercontent.com/16626308/42726016-e0b257d4-878d-11e8-98b9-8ade6f917f0b.png)

With "widows style icons" I meant icons that are on Windows. 
![widows style icons](https://user-images.githubusercontent.com/16626308/42726009-c7afe85a-878d-11e8-8100-a82b621419c5.png)

**Comment by filips123** [comment]
There could also be support for panel at the bottom or other sides.

**Comment by andersevenrud** [comment]
> There could also be support for panel at the bottom or other sides.

Yes. The idea is to match the features of v2, with some minor exceptions.

**Comment by andersevenrud** [comment]
Just tested it, and it's just a matter of flipping it in CSS :)

![os js](https://user-images.githubusercontent.com/161548/42726648-180b8e30-8798-11e8-8dda-4293c86ab7e8.png)

**Comment by andersevenrud** [comment]
I have a Debian package template for v2 that can be converted for v3. It's just sets up a init.d script and runs a custom C program when the X server launches (which is just a libwebkit implementation). I experimented a bit with it, but never got to making any ISO or something like that... I'll consider it at a later point probably. Right now I just wanna concentrate on making the beta release.

**Comment by filips123** [comment]
What about some installation program which will run on first startup, users could setup some settings like language, timezone... Developers of custom apps, providers or adapters will also be able to set up some required settings. This could be optional.

**Comment by andersevenrud** [comment]
@filips123 Some kind of installation wizard could be nice, yes :)

**Comment by andersevenrud** [comment]
@filips123 CI is now also up btw.

![os js travis ci](https://user-images.githubusercontent.com/161548/42903568-8a03905e-8ad2-11e8-90cc-2b0b80f9d276.png)

**Comment by SpaceboyRoss01** [comment]
I think a Unix like vfs design would be better than Windows's VFS design. I mean a format of `/dir/subdir/file` instead of `Drive:\\Path\`

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 

> I think a Unix like vfs design would be better than Windows's VFS design. I mean a format of /dir/subdir/file instead of Drive:\\Path\

There is no "root filesystem" in OS.js, so the VFS operates with standard URI-s, ex: `mountpoint:/path/to/file`. So it's not a UNIX, nor Windows "design"

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by SpaceboyRoss01** [comment]
Couldn't a Unix design be implemented? It's less confusing for certain people.

**Comment by andersevenrud** [comment]
> Couldn't a Unix design be implemented? It's less confusing for certain people.

If you could maybe explain how that would be confusing ?

The goal of the UI and all the abstraction is that the end-user won't even know how the underlying system works, they just go to a location and save a file like you would normally anywhere else (think modern Windows or any other Desktop Linux platform -- and how they present this to the end-user).

And in terms of the developer-side, it's all documented. And URI-s are a well known standard.

That said, since it's all virtual and the abstraction is pretty good, you can actually make an interface that presents everything as you would in for example Linux -- but, I can't look into that until I have released the beta.

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 There's actually a community user that is working on a CLI module, where this might have been taken into consideration. I haven't followed up in a while...which reminds me, I should probably do that :blush:

**Comment by SpaceboyRoss01** [comment]
I decided that I'll help with working on this version of OS.js, I can try to find bugs.

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 Bug hunting is allways much appreciated :)

**Comment by SpaceboyRoss01** [comment]
I'm trying to make some apps for OS.js and I cannot figure out how to create an about dialog, is there any way to do that?

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 You mean like the "About" application I had in v2, or are you trying to use the dialog API ?

**Comment by SpaceboyRoss01** [comment]
An about dialog for an application

**Comment by SpaceboyRoss01** [comment]
I found a bug with opening a window. When there are no focused windows and a new window is opened, it's transparent the window beneath appears visible. I think this is an actual bug because I've never seen a window manager that does this effect on windows.
![screenshot from 2018-07-19 13-09-35](https://user-images.githubusercontent.com/19699320/42967471-32e9ed9e-8b55-11e8-9844-01e23e822082.png)

**Comment by andersevenrud** [comment]
> I found a bug with opening a window. When there are no focused windows and a new window is opened, it's transparent the window beneath appears visible.

You have to call `.focus()` on your newly created window to give it focus.

>  I've never seen a window manager that does this effect on windows.

This is how I've set up my personal desktop. It's to prevent focus stealing when a popup window appear etc.


I can possibly add an option to automatically focusing the windows.

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 I've opened an issue about in the appropriate repo: https://github.com/os-js/osjs-client/issues/12

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 Btw, theres a gitter room you can join to discuss development 

https://gitter.im/os-js/OS.js/development

**Comment by filips123** [comment]
Is it possible to host client and server on different computers?

Also, is it possible to host client on GitHub Pages and server on Heroku?

**Comment by andersevenrud** [comment]
@filips123 I've added basic instructions here: https://manual.os-js.org/v3/guide/deploy/#running-separately. This only works with the release I just published.

**Comment by andersevenrud** [comment]
Since I've gotten a lot of questions about it; I've put together a list of TODOs (which is sort of a basic roadmap):

https://gist.github.com/andersevenrud/ebfc22ef75c6686cc2d9a6e1191a8405

I'm updating this list as things come to mind, but I've dedicated a section for the beta release. As you can see, it's not far off :blush:

**Comment by andersevenrud** [comment]
Things got set back a month or so due to some personal stuff, but it's all in full progress again.

I've actually ticked off pretty much all TODOs that I wanted to have done. So expect a beta/rc soon!

I also added back support for Legacy browsers (requires a couple of setup steps https://manual.os-js.org/v3/guide/deploy/#legacy-browsers) because I got some questions about this. The reason it has not worked 100% until now is because of some dependencies was not in ES5 -- but has now been resolved completely as of latest release(s).

**Comment by filips123** [comment]
It looks good, but it still lacks some features and design of v2. Some apps are still very basic and with poor design.

Will there be support for fullscreen mode and icons on desktop? What about touch menu or some mobile OS like theme?

**Comment by andersevenrud** [comment]
@filips123 

> It looks good, but it still lacks some features and design of v2. Some apps are still very basic and with poor design.

My current goal is to finish my TODO list, which involves some application improvements etc. There are actually more internal features in v3 than v2, but I suppose you mean *visually*. If you think they are poor, please go ahead and make some improvements yourself. PRs are much welcome.

> Will there be support for fullscreen mode and icons on desktop? What about touch menu or some mobile OS like theme?

Yes, this will all be implemented.

**Comment by filips123** [comment]
Yes I mean visually 😊.  Unfortunately I can not help you because I'm not expert in Node.js and related things.

**Comment by andersevenrud** [comment]
@filips123 The apps are written in regular javascript, so if you have some exeperience with that you can probably find your way around.

But anyway, things will improve down the line -- I have quite a few todos, issues and the likes on this open :)

**Comment by filips123** [comment]
How often will you update online demo? Some things are outdated and not fixed even you fixed them last week.

**Comment by IngwiePhoenix** [comment]
Maybe add a demo reset to the deploy chain?

**Comment by andersevenrud** [comment]
@filips123 Usually once a week or something like that. I actually set up the v3 server this week, so it haven't really gotten an update yet.

**Comment by andersevenrud** [comment]
@IngwiePhoenix Not sure what you mean by that.

**Comment by IngwiePhoenix** [comment]
@andersevenrud Well, whenever you do a new release, have the demo updated automatically in the deploy/release process? That is what I meant.

**Comment by andersevenrud** [comment]
@IngwiePhoenix Ah, yes :)

**Comment by SpaceboyRoss01** [comment]
@andersevenrud why can I modify files in the v3 public demo?

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 What files ?

**Comment by andersevenrud** [comment]
@SpaceboyRoss01 Yes. That intentional.

I have a cronjob that flushes the directory on an interval (can't remember exactly how often atm).

**Comment by SpaceboyRoss01** [comment]
Ok, I thought I had too much control but that's good it get's flushed.

**Comment by filips123** [comment]
I have concerns about pinned issues for static announcements (like #705) or long discussions (like #18). They are not intended to be used for that.

For static announcements, you should create file in repository (probably in `docs` directory) or GitHub Gist, and maybe link it from website or readme.

For long discussions, you should create [GitHub Teams](https://help.github.com/articles/organizing-members-into-teams/) in organization that allows organizing members and and are also good for discussions. You could create team Admins, Developers, Translators... and relevant discussion will be placed there.

**Comment by andersevenrud** [comment]
Not sure that I fully agree.

How are pinned issues not intended to be used like this? Its for drawing
attention to certain topics that are currently important or relevant,
right? "Issues" don't explicitly have to be "problems" but general
discussions. etc.

I created #705 here because it's the most obvious place to have it. I'll
probably add it to the CONTRIBUTING file or something as well.

For general announcements I usually use the community site.

Seems like github supports adding collaborators as non-org team members (
https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/)
so I'll look into that.

**Comment by andersevenrud** [comment]
@filips123 I've set up a new Team for translaters and done a round of invites (actually two). Sadly "outside collaborators" cannot be added to teams, but I think I managed to configure the Org to not give broad permissions. The standard "Read" permission actually allowed for modifying org repos which is a bit crap.... but think I've ironed stuff out!

**Comment by andersevenrud** [comment]
I set the default branch to `v3` a couple of days ago, so I guess it's now technically released :blush: 

The v3 demo was set up quite a while ago with monitoring and so far no big issues has been coming in. So I'm letting things simmer for a few more days, and then on the new year:

1. Move current `v3` into `master`
2. Move now deprecated `master` into `v2`
3. Let `v3` become the "development" branch
4. Update any website links that points to old content

Then make the "official announcement" on https://community.os-js.org/ which will be linked here when its out.

This is the list of features / packages that has not yet been converted into v3:

* Keyboard hotkeys (seems broken in v2)
* Desktop iconview (component created, looking into deployment)
* Theme: Glass
* Theme: Material UI
* Settings Application: Better UI  (*)
* Settings Application: Panel Configuration (*)
* Application: Game demos (*)

(*) I'll roll out some application settings ASAP, so most of the things in that list will be taken care of.

**A big thanks to all of the people that reported bugs, feature requests and translations!** :heart: 

Since this is no longer "upcoming", I'm going to close this issue.

**Comment by filips123** [comment]
When you update branches, you should also cleanup and delete some of them because there are some that weren't updated over 2 years.

**Comment by andersevenrud** [comment]
Yup. Will look into that. Might also rebase some of the v2 stuff because
cloning the entire repo is a bit slow.

**Comment by andersevenrud** [comment]
@filips123 I've transferred all of the old branches to the following repos:

* https://github.com/andersevenrud/OS.js-v2.1
* https://github.com/andersevenrud/OS.js-v2.0

Also removed all of the old branches from this repo. So now there's only `master` (v2) and `v3`.

I'm going to replace the `master` with `v3` this weekend.
