### ISSUE TITLE
error: arduino yun setting

### ISSUE THREAD

**Issue by marketstr** [os-js/OS.js#673]
An error occured while trying to launch: ApplicationArduinoSettings

> Application 'ApplicationArduinoSettings' preloading failed:  /packages/target/ArduinoSettings/combined.js?77925

**Comment by marktopper** [comment]
Properly a duplicate of #625

**Comment by andersevenrud** [comment]
Hi,

All of the issues you are reporting comes from the same problem. Some boards have some issues with networking (connection dropout).

Try using Luci instead: http://arduino-ip/cgi-bin/luci if you want to configure the board if the problem perists (even after upgrade).

Reference issue: #436
