### ISSUE TITLE
An error occured while trying to launch: ApplicationArduinoLuci

### ISSUE THREAD

**Issue by thechrisgeorgiev** [os-js/OS.js#676]
An error occured while trying to launch: ApplicationArduinoLuci

> Application 'ApplicationArduinoLuci' preloading failed:  /packages/target/ArduinoLuci/combined.js?75048

**Comment by andersevenrud** [comment]
Try using Luci instead: http://<your-board-ip>/cgi-bin/luci

Ref: #436
