### ISSUE TITLE
Couldn't send email

### ISSUE THREAD

**Issue by TheGreatRambler** [os-js/OS.js#677]
I tried to send an email and it didn't work. It showed an error.

**Comment by andersevenrud** [comment]
Without the actual error I am unable to look into it.

**Comment by TheGreatRambler** [comment]
The error is:
```
window::onerror()
Filename: 
Line: 0:0
Message: Script error.
```
It occurred when I tried to send a simple email with a subject and a receiver.

**Comment by andersevenrud** [comment]
I'm making a new client for the upcoming v3 release, so this issue will be resolved by then.

So, I'm closing this issue for now and making a note of it in #216, which is a general issue for this application,
