### ISSUE TITLE
Draw App is lagging

### ISSUE THREAD

**Issue by filips123** [os-js/OS.js#682]
## Expected behaviour

The line with pencil in Draw App should be the same everywhere

## Actual behaviour

If I move pencil in Draw App too fast, the line is interrupted.

## Steps to reproduce the error

1.  Open OS.js demo at https://demo.os-js.org/
2.  Open Draw app
3.  Select pencil
4. Draw something very fast

# Screenshots

![slika](https://user-images.githubusercontent.com/16626308/40366806-4f32b4c2-5dd8-11e8-818a-2f81b3d4dae2.png)

**Comment by andersevenrud** [comment]
Hi,

I've noticed this as well. This won't be an issue in the v3 release of this application (which also will have a lot of other improvements), so I'll probably backport some of the stuff to fix this.

**Comment by filips123** [comment]
When will be v3 released?

**Comment by andersevenrud** [comment]
I've pushed the first iteration of the new draw application here: https://github.com/os-js/osjs-draw-application. It does not exhibit this issue :)

Also, I'm not sure I have the time to actually do the back-porting, so I'm closing this issue (for now at least).
