### ISSUE TITLE
Notification Bug in V3

### ISSUE THREAD

**Issue by 3HMonkey** [os-js/OS.js#684]
## Actual behaviour

The Z-Index of Notifications seem to be wrong.
![2018-06-07 12_17_45-os js](https://user-images.githubusercontent.com/4610892/41093930-d9a5cc0e-6a4c-11e8-9cfc-979bdbbadbc4.png)

## Steps to reproduce the error

1. Fresh install of V3
2. Just shut down the server for example

**Comment by andersevenrud** [comment]
Thanks! I've opened an issue in the appropriate repository: https://github.com/os-js/osjs-client/issues/9

So, I'll be closing this one.
