### ISSUE TITLE
The FileManager's right-click menu does not respond.

### ISSUE THREAD

**Issue by llyer** [os-js/OS.js#685]
The file manager's right-click menu does not respond. 
I looked at the source code, it should be a problem with the follow code:

```
// packages/FileManager/main.js

var contextMenu = this._find('SubmenuContext').on('select', menuEvent);
```

 there are two nodes in the real DOM `data-id = "SubmenuContext"`:
```
<gui-menu data-id="SubmenuContext" name="SubmenuContext">
    ...
    // some code
    ...
</gui-menu>
```

Only the first node is found, but the actual menu displayed is the second node. Caused event listener not working properly.

![image](https://user-images.githubusercontent.com/16920929/41448430-1cde250c-708d-11e8-9764-e512a571f54e.png)

So I suggest you fix this problem.

**Comment by andersevenrud** [comment]
Hi,

Thanks for letting me know about this. I'll make sure to fix this when I get the time. Currently very busy on v3 :)

**Comment by llyer** [comment]
@andersevenrud ok, I understand

**Comment by andersevenrud** [comment]
I'm sad to say that I won't be able to backport this into v2 because I simply don't have the time. This is certainly not an issue in v3, which I will be releasing very soon (which basically ends support on v2).
