### ISSUE TITLE
OS JS v3 Alpha Release

### ISSUE THREAD

**Issue by ashishgupta02** [os-js/OS.js#689]
## Expected behaviour
Should have source code. But I did not find any code inside the release zip or tar.gz files.

## Steps to reproduce the error
1. Download the release artifact and find no code.

**Comment by andersevenrud** [comment]
The code is in separate npm packages. The `OS.js` base repository is now just a "base project" to make your own distributions.

You can see all the core modules and available packages here:

https://manual.os-js.org/v3/resource/official/

**Comment by andersevenrud** [comment]
Just to make sure, by "no source", you don't mean "no files", right ?

These are the sources for this setup:

```
src/cli/index.js
src/client/config.js
src/client/favicon.png
src/client/index.ejs
src/client/index.js
src/client/index.scss
src/server/config.js
src/server/index.js
webpack.config.js
```

Think of this as a web framework. The repository is a "Project" that imports and sets up all the OS.js modules and builds a distribution.

**Comment by ashishgupta02** [comment]
Thanks for the quick reply. I observed that differences between v2 and v3, in version 3 code have split into multi components. I followed the updated procedure which are in v3 branch and works as intended.

**Comment by andersevenrud** [comment]
Yep. It's all done from scratch and split up into several modules and components :)
