### ISSUE TITLE
 Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x

### ISSUE THREAD

**Issue by Slluxx** [os-js/OS.js#691]
Raspberry Pi model 3B+
Manual node installation 

dont know if it should be supported

**Comment by andersevenrud** [comment]
Are you trying OS.js v3 ?

**Comment by andersevenrud** [comment]
Thinking of it, node-sass should work on any platform as long as `node-gyp` is installed, which also would require `build-essentials` for debian/ubuntu. It can be built from source if a binary is not found.

**Comment by Slluxx** [comment]
Yes, v3.
I will check with node-gyp and essentials later

**Comment by andersevenrud** [comment]
I'm closing this issue because any issues relating to npm is out of my control. We can of couse keep the discussion going here, I just wanna keep things clean in the issue list :blush:
