### ISSUE TITLE
Application 'ApplicationArduinoPackageManager' preloading failed:  /packages/target/ArduinoPackageManager/combined.js?26137

### ISSUE THREAD

**Issue by donnmphone** [os-js/OS.js#696]
An error occured while trying to launch: ApplicationArduinoPackageManager

> Application 'ApplicationArduinoPackageManager' preloading failed:  /packages/target/ArduinoPackageManager/combined.js?26137

**Comment by andersevenrud** [comment]
Hi,

Please refer to this comment on Arduino issues: https://github.com/os-js/OS.js/issues/436#issuecomment-415601684
