### ISSUE TITLE
Add support for nodejs, guy!

### ISSUE THREAD

**Issue by OlivieBright** [os-js/OS.js#701]
OS.js is cool if add with nodejs! He will have more options, packages. This can be quick.

**Comment by OlivieBright** [comment]
What do you think of this?

**Comment by SpaceboyRoss01** [comment]
You can run node by having the xterm app installed and ssh'ing into your computer and then running node.21.12.2018, 19:12, "Olivie Bright" <notifications@github.com>:What do you think of this?

**Comment by andersevenrud** [comment]
OS.js actually runs on node, so not sure what you mean by this. Maybe you could elaborate ?

**Comment by OlivieBright** [comment]
> OS.js actually runs on node, so not sure what you mean by this. Maybe you could elaborate ?

I no understand what you said. See, I would like to have a cli with the nodejs+npm.

**Comment by OlivieBright** [comment]
> You can run node by having the xterm app installed and ssh'ing into your computer and then running node.21.12.2018, 19:12, "Olivie Bright" <notifications@github.com>:What do you think of this? —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

Thanks you for the information!

**Comment by OlivieBright** [comment]
> OS.js actually runs on node, so not sure what you mean by this. Maybe you could elaborate ?

Thanks you for the information!

**Comment by andersevenrud** [comment]
> See, I would like to have a cli with the nodejs+npm. Where is the terminal stay? 

The terminal app is not in the demo for security reasons. Check out

https://github.com/os-js/osjs-xterm-application

There's also a service that allows developers to use processes via node:

https://github.com/os-js/osjs-proc-provider
