### ISSUE TITLE
Version Os.js in VDI (VirtualBox), please!

### ISSUE THREAD

**Issue by OlivieBright** [os-js/OS.js#702]
Version in VDI would be interesting and could increase the chances of the project becoming more common
.

**Comment by OlivieBright** [comment]
What do you think about this idea?

**Comment by andersevenrud** [comment]
I only provide Docker images for OS.js. If you need a Linux image, check out @SpaceboyRoss01 project.

**Comment by OlivieBright** [comment]
About this, something with this feature similiar in this website:  https://www.osboxes.org/virtualbox-images         You can download  virtual machines and test things. Example: ubuntu.vdi

**Comment by SpaceboyRoss01** [comment]
I only provide the Live images with the installer so a bluelight.vdi is not needed.

**Comment by SpaceboyRoss01** [comment]
Fixed and please submit issues to the repository for the website
