### ISSUE TITLE
Add feature, import interfaces with Codepen.io  

### ISSUE THREAD

**Issue by OlivieBright** [os-js/OS.js#703]
It would be interesting to import Codepen.io interfaces

This would help the system to be common and would also be a new way for designers to leave the system the way they want without compiling, just importing on this site. 

Note: If the system is in the cloud, the design must be in the cloud. Something like a webdav. What do you think?

**Comment by SpaceboyRoss01** [comment]
You can just install the browser application and navigate to codepen.io

**Comment by andersevenrud** [comment]
Their APIs don't allow extracting the code it seems. Also, using their embed has no way to only return the result *or* code. Worse yet, you can't use their iframes without spoofing the `Host` from the request.

So doing this would require some kind of separate tool to extract the code, and then place this in an application. So this now falls a bit outside the scope, and seeing that I don't have any time to work on this, I'm closing this issue.

If anyone wants to pick this up that'd be great :)
