### ISSUE TITLE
[v3] FTP adapter for VFS

### ISSUE THREAD

**Issue by filips123** [os-js/OS.js#706]
Add VFS adapter for FTP, FTPS, SFTP and other similar file protocols.

**Comment by SpaceboyRoss01** [comment]
I second this.  30.12.2018, 09:27, "Filip Š" <notifications@github.com>:Add VFS adapter for FTP, FTPS, SFTP and other similar file protocols.

**Comment by andersevenrud** [comment]
Sure. That should be pretty straight forward with some sort of node library.

Probably needs some kind of UI in Settings app if users should be able to
create custom connections (i.e. not statically defined in a config).

**Comment by filips123** [comment]
There could be support for both static config and changing in config.

**Comment by andersevenrud** [comment]
Yup. They only differ in how they are added into the VFS "manager" :)

**Comment by andersevenrud** [comment]
I've made a bit of progress on this btw. Basic file listing, reading etc. Although I have implemented the methods that manipulates files I have yet to test it because I need to set up my own ftp. I was just using a random linux mirror while testing, heh.

I settled on https://github.com/realtymaps/promise-ftp because as it wraps the standard `ftp` library around Promise-s.

**Comment by andersevenrud** [comment]
I've implemented all of the available FTP methods, but for some unknown reason (at the moment), copying files does not seem to work properly (within the ftp that is, copy from/to other filesystems work, so this is a library bug).

After I've sorted this out this is ready for an initial release :slightly_smiling_face:

**Comment by andersevenrud** [comment]
I fixed the copy issue in https://github.com/os-js/osjs-ftp-adapter/commit/118a8c2d9db7e61dfba3d1cd2aceb898a60bc773

This is now released as `@osjs/ftp-adapter` on npmjs. Therefore I'm closing this issue. Any further discussion can take place in the issues for that repo :slightly_smiling_face: 

(Also added to manual which will auto deploy soon: https://github.com/os-js/manual.os-js.org/commit/70a93af09b1442f60b13860ca2ce95289ac8fe4a)
