### ISSUE TITLE
yun

### ISSUE THREAD

**Issue by vonglahn** [os-js/OS.js#709]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
ApplicationArduinoPackageManager.prototype.callOpkg/<@http://10.0.0.172/packages/target/ArduinoPackageManager/combined.js?30216:282:13
ApplicationArduinoPackageManager.prototype.callAPI/<@http://10.0.0.172/packages/target/ArduinoPackageManager/combined.js?30216:254:16
doAPICall/<@http://10.0.0.172/osjs.js:1692:7
onerror@http://10.0.0.172/osjs.js:8870:9
onReadyStateChange@http://10.0.0.172/osjs.js:1202:11

```

**Comment by SpaceboyRoss01** [comment]
Please provide more information. What are you trying to do? What have you already done?

**Comment by andersevenrud** [comment]
For issues with the Yun, please look at https://github.com/os-js/OS.js/issues/436
