### ISSUE TITLE
Provide installation scripts and Windows instructions

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#710]
I've gotten a few questions on Gitter in the recent days relating to installation scripts and executables, etc.

I should probably provide a couple of automated scripts for running installations:

* Linux: Batch script
* Windows: PowerShell script

Also, the manual could use some instructions on how to do manual installation on Windows using PowerShell manually, etc.

---

Side-nodes:

* Provide as a windows service ?
* Also provide a systemd unit ?
* Maybe also PM2 instructions ?

**Comment by SpaceboyRoss01** [comment]
I can work on the Linux script and make it so you just run curl and pipe it to bash. I’ll open a pull request once I get it working.

**Comment by andersevenrud** [comment]
Nice. The old script I had actually checked if nodejs was installed, and if not selected the appropriate package manager and installed it that way (with user confirmation). So if you also could add that it'd be sweet.

**Comment by SpaceboyRoss01** [comment]
I can add an option to enable PM2 and an option to make it interactive or not. I can do a lot with this.

**Comment by 17lwinn** [comment]
i found this:

https://github.com/eiriklv/OS.js-v2/tree/master/src/installer

someone forked the repo and made an installer script

**Comment by andersevenrud** [comment]
@17lwinn That's just a fork of a repo on my personal github account with the old installers for v2 I made way back.

I'm not even sure anymore that this is really something that's needed... all it does is to run a couple of npm commands imo should be run manually. And since there's first class docker support, this is even less relevant because that's just a single command to get running :thinking:

**Comment by 17lwinn** [comment]
fair point

**Comment by andersevenrud** [comment]
I'm basically scrapping this because the manual has all the required information.

If someone wants to pick this up I'll reopen it.

**Comment by hello-smile6** [comment]
Can you try, @andersevenrud ?

**Comment by andersevenrud** [comment]
I'm leaving this open to the public @hello-smile6 . If someone knocks one together I'll include it somewhere.

**Comment by hello-smile6** [comment]
Okay.
