### ISSUE TITLE
[v3] Add OAuth Auth Adapter

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#714]
Would be nice to have a generic implementation, or maybe some example on how to do this.

**Comment by andersevenrud** [comment]
I've started on an Auth0 example using implicit flow and API authorization. Works pretty well, except for the  auto-login (and SSO), but this may be isolated to the free environment.

https://github.com/andersevenrud/osjs-auth0-auth

**Comment by filips123** [comment]
There should also be support for OpenID and OpenID Connect.

In the future, there could also be support other authentication and authorization protocols like SAML, LDAP ... and other protocols from https://www.getkisi.com/blog/authentication-protocols-overview. They are generally more for "business auth" but it will be great if they will be supported.

**Comment by SpaceboyRoss01** [comment]
@filips123 Just follow the manual for creating an auth adapter.

**Comment by andersevenrud** [comment]
Closing this issue because I'm writing an article on how to write adapters like this -- also the Auth0 adapter should give a pretty good idea on how this all works.

**Comment by filips123** [comment]
Can you share link to that article?

**Comment by andersevenrud** [comment]
I'll link it here once it's done.

**Comment by andersevenrud** [comment]
This is the initial draft of the article https://gist.github.com/andersevenrud/1e6b51a1f643d7dd5f17c4f81230f63b

Don't mind the missing UI stuff (Like `[info]` which is usually a blue "bubble") and links as this will be plugged into the manual and resolved automatically.
