### ISSUE TITLE
[v3] Add registration support

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#715]
Currently both the login UI and the login adapter(s) does not support registration.

This is done entirely via CLI (or with database provider any other admin tool).

* [ ] Add server API
* [x] Add configuration
* [ ] Add UI support

**Comment by mikeblackstock** [comment]
Do you have any thoughts on using Google's reCaptcha for bot detection in user registration forms? The algorithm isn't published or 'open',  which makes me, personally, a little uncomfortable.

**Comment by andersevenrud** [comment]
The Login module is pretty customizable, so it is possible to add any number of verification methods.

Yeah, the *re*Captcha is not open which is not in spirit of this project, and I'm pretty sure there are no real (good) alternatives.

**Comment by filips123** [comment]
There should also be support for OpenID and OpenID Connect.

In the future, there could also be support other authentication and authorization protocols like SAML, LDAP ... and other protocols from https://www.getkisi.com/blog/authentication-protocols-overview. They are generally more for "business auth" but it will be great if they will be supported.

**Comment by SpaceboyRoss01** [comment]
Follow the custom authentication adapter in the manual (http://manual.os-js.org).

**Comment by andersevenrud** [comment]
API support for this was added in the following:

* https://github.com/os-js/osjs-client/commit/d607681b64d217dea59c6829512ba6f14b73527c
* https://github.com/os-js/osjs-server/commit/46bb6f0269e09dd6e90f90ab5a0a352beefe932b

This applies to Adapters for both Server and Client.

I'm not sure if I'm going to add this into the default UI... so I'm closing this issue. And if it comes to it, I'll make a dedicated issue in `@osjs/client` for that.
