### ISSUE TITLE
Lots of errors occuring on Microsoft Edge on iOS

### ISSUE THREAD

**Issue by dullbananas** [os-js/OS.js#716]
undefined

**Comment by SpaceboyRoss01** [comment]
Please explain more besides `undefined`. What are the errors?

**Comment by dullbananas** [comment]
im using the public demo

**Comment by SpaceboyRoss01** [comment]
More information is **STILL** needed. What errors are you getting?

**Comment by dullbananas** [comment]
When I open AceEditor, it shows an error, and it also shows error when selecting the text area on the window

**Comment by dullbananas** [comment]
It also shows a bunch of errors when using a slider in settings app
And the errors show no filename and say they are on line "0:0"

**Comment by SpaceboyRoss01** [comment]
But what is the error that AceEditor says? If AceEditor is having an error, then find the repository and open an issue there, not here.

**Comment by dullbananas** [comment]
It also shows error when opening Process Viewer

**Comment by SpaceboyRoss01** [comment]
Are you using v3 or v2? Process Viewer for v3 is my application and has no issues.

**Comment by dullbananas** [comment]
im using the public demo version at 
https://demo.os-js.org/

**Comment by dullbananas** [comment]
Clicking on the search button on the top right causes an error

**Comment by dullbananas** [comment]
Selecting the textareas on the error dialog also causes an error

**Comment by SpaceboyRoss01** [comment]
V2 is outdated, please use the [v3 demo](https://demo.os-js.org/v3/)

**Comment by dullbananas** [comment]
The problems are only happening on Edge

**Comment by SpaceboyRoss01** [comment]
Yeah because Edge doesn't support things other browsers do. Please use Chrome or Firefox.

**Comment by dullbananas** [comment]
I will continue trying Edge anyway
and none of the errors are happening on v3

**Comment by andersevenrud** [comment]
A bit late to the party, but, yeah v2 is outdated. I should probably move it to `/v2` or something to make v3 the default.

Edge should be just as capable as the other browsers and is supported in v3.

Since this seems resolved, I'll close this issue.
