### ISSUE TITLE
Bug in Ciao Configuration in Arduino OS

### ISSUE THREAD

**Issue by Nauman3S** [os-js/OS.js#717]
An unexpected error occurred, maybe a bug.

This occurs whenever a file is edited and saved in Ciao Configurator in Arduino OS.

```
ApplicationArduinoCiaoConfiguratorWindow.prototype.showConnectorConf/</<@http://arduino.local/packages/target/ArduinoCiaoConfigurator/combined.js?15625:245:27
abToBinaryString/r.onloadend@http://arduino.local/osjs.js:10030:35

```

**Comment by andersevenrud** [comment]
Please see https://github.com/os-js/OS.js/issues/436#issuecomment-415601684 for ways to work around this issue.
