### ISSUE TITLE
sending gmail doesnt work.

### ISSUE THREAD

**Issue by shgef** [os-js/OS.js#720]
**sending gmail doesnt work.**

I think this is a bug.
Include here a brief description on how the error occured:

Versuch ein gmail an unseren eigenen Mailacc. abzusenden;

![grafik](https://user-images.githubusercontent.com/52720420/60922720-a5fe9180-a29d-11e9-8666-799625d2a312.png)

______________________________________________________________________________

undefinedvalue@https://demo.os-js.org/packages/extras/GoogleMail/main.js:31:16955
value@https://demo.os-js.org/packages/extras/GoogleMail/main.js:31:23769
Send@https://demo.os-js.org/packages/extras/GoogleMail/main.js:31:34692
i@https://demo.os-js.org/packages/extras/GoogleMail/main.js:31:34217
s/<@https://demo.os-js.org/osjs.js:31:17240
d@https://cdn.ravenjs.com/3.17.0/raven.min.js:2:6415
t@https://demo.os-js.org/osjs.js:31:565866
value/<@https://demo.os-js.org/osjs.js:31:566417
s/<@https://demo.os-js.org/osjs.js:31:17240
d@https://cdn.ravenjs.com/3.17.0/raven.min.js:2:6415

**Comment by andersevenrud** [comment]
Hi.

The v2 version of this project (`demo.os-js.org/`) has been deprecated so sadly this will not get a fix.

You can find the v3 demo at https://demo.os-js.org/v3/ , however it does not come with a gmail client yet (it's in progress).

**Comment by shgef** [comment]
hi,   interesting direction   ... seems like coming with a large potencial of usability. Great!   Im also happy about the good looking new version, very nice to have a walk around it. I could not wait for evening, so I have now smily face about the new steps ... Thank you so much. :)   Let me know about forther news would be friendly ..   CU f 
Selbsthilfegruppe pflegender Angehöriger
Demenz - Pflaster
Tel.: EF 7447 460

(registriert bei KISS Erfurt Tel. 655-4204
https://www.erfurt.de/ef/de/rathaus/sv/aemter/stelle-241.htmc )

Zur anonymen Kontaktaufnahme:
https://www.afpk-erfurt.de/kontakt
(Bitte Kennwort "Demenzpflaster" verwenden.) 

Am 09-Jul-2019 23:22:02 +0200 schrieb notifications@github.com: 

Hi. 

The v2 version of this project (demo.os-js.org/) has been deprecated so sadly this will not get a fix. 

You can find the v3 demo at https://demo.os-js.org/v3/ , however it does not come with a gmail client yet (it's in progress).
