### ISSUE TITLE
Log out when refresh

### ISSUE THREAD

**Issue by refail** [os-js/OS.js#725]
Hi,
I have a fresh installation of OsJs and i made authentication using Database Auth Adapter.
Everything goes fine but when i reload the page the session destroyed and i go out and need to login again.

is this a problem of Osjs or is something i need to do?

Thank you in advance.

**Comment by andersevenrud** [comment]
Hi,

To save your session you have to explicitly select "save and log out" from the application menu (at least in v3. In v2 this is a tray icon).

I'm however complementing to add a feature that continuously saves the session whenever the user launches a new application of moves a window etc..

**Comment by refail** [comment]
Thank you for your response but i'am saying something else.
After i am login in Osjs and if i reload (or refresh) the page, it log me out and i need to login again.

I am running Osjs in ubuntu 18.04.

**Comment by andersevenrud** [comment]
Aha. This is by design, but I could possible add a way to remember the login.

**Comment by refail** [comment]
Okay. thank you.

**Comment by andersevenrud** [comment]
Moved this issue to https://github.com/os-js/osjs-client/issues/88
