### ISSUE TITLE
make a terminal app for OS.js

### ISSUE THREAD

**Issue by 17lwinn** [os-js/OS.js#726]
I have an idea!

use [terminaljs](http://erikosterberg.com/terminaljs/) to make an OSjs terminal, it should be easy to add node modules to it and you could try it using an iframe element to this page:

https://pt-exec.glitch.me

it is a simple demonstration of the terminaljs functionality, the source is available here:

https://glitch.com/edit/#!/pt-exec
----

**Comment by andersevenrud** [comment]
I actually made one not that long ago using xterm (the same as used in the OS.js Xterm SSH terminal application).

https://www.youtube.com/watch?v=CBEEoFixGts

I don't think I've uploaded this to github yet though :thinking: Doing that now.

**Comment by andersevenrud** [comment]
Here's the code as it were where I left off:

https://github.com/andersevenrud/osjs-terminal-application

It's pretty basic, but a good starting point.

**Comment by 17lwinn** [comment]
thanks! i'll test it now

**Comment by 17lwinn** [comment]
im getting error 404: Not Found Terminal@latest

**Comment by 17lwinn** [comment]
could you send a link to the NPM repo?

**Comment by andersevenrud** [comment]
I just uploaded it to github.

```
cd src/packages
git clone https://github.com/andersevenrud/osjs-terminal-application.git
cd osjs-terminal-application
npm install
npm run build
``

Then run `npm run package:discover` inside your installation and it should appear.

**Comment by 17lwinn** [comment]
right ill try that now

**Comment by andersevenrud** [comment]
I presume it worked OK since you closed this issue ?

**Comment by 17lwinn** [comment]
Yep, thanks :)
