### ISSUE TITLE
Server Failed!

### ISSUE THREAD

**Issue by 0710trananh** [os-js/OS.js#727]
This Is Server Failed! Please Fix Is!

**Comment by RossComputerGuy** [comment]
Could you explain more? What happened? What OS are you on?

**Comment by 0710trananh** [comment]
RossComputeGuy! I Open Calculator, And Server Failed!!

**Comment by RossComputerGuy** [comment]
What do you mean server failed? Was there an error message? Was this on an instance of OS.js your running?

**Comment by andersevenrud** [comment]
There's not enough information here to assist with your issue.

Please provide the actual error messages, screenshots etc. then re-open this issue.
