### ISSUE TITLE
Files offensive in demo

### ISSUE THREAD

**Issue by matheusfelipeog** [os-js/OS.js#728]
I seen it at demo, files with content
offensive, I believe that it was not the intention to leave them there.

open it for see
**Screenshots:**
<img src='https://user-images.githubusercontent.com/50463866/72853493-48a5bd00-3c90-11ea-94f8-af1cb480617c.png' width='650px'/>

and 

<img src='https://user-images.githubusercontent.com/50463866/72853524-65da8b80-3c90-11ea-858b-6a009e32f5bb.png' width='650px'/>

Obs: Sorry for my english, Google translator version ;)

**Comment by andersevenrud** [comment]
Hi.

Thanks for bringing this to my attention.

The server is configured to remove all files every Sunday, but I forgot to enable this after I upgraded the server.

I re-enabled this feature and all files should now be removed on a regular basis again. I removed all the files that was uploaded now manually just to be sure.

:+1:
