### ISSUE TITLE
can you release the demo source code?

### ISSUE THREAD

**Issue by 17lwinn** [os-js/OS.js#731]
Hi

Could you release source code so I can use it?

The demo is great and I love it, but the source code would be great so I could put it into a glitch project.

**Comment by andersevenrud** [comment]
There's nothing special about the demo source. It's this repository, only with all the applications pre-installed via npm.

**Comment by 17lwinn** [comment]
I know, but  could you at least tell me how you made the settings menu look how it does. If possible could you put it on NPM?

**Comment by andersevenrud** [comment]
If you're thinking about https://demo.os-js.org/ and not https://demo.os-js.org/ then you're looking at the old version. This is also in this repo: https://github.com/os-js/OS.js/tree/v2

**Comment by 17lwinn** [comment]
I'm just now looking for the source for the demo settings app.

**Comment by andersevenrud** [comment]
v2: https://github.com/os-js/OS.js/tree/v2/src/packages/default/Settings

v3: https://github.com/os-js/osjs-settings-application

**Comment by 17lwinn** [comment]
![Screenshot_20200216-162726](https://user-images.githubusercontent.com/50519725/74608479-4bea6800-50d9-11ea-8f2a-e31d1b5db046.png)

**Comment by 17lwinn** [comment]
Like this

**Comment by andersevenrud** [comment]
See my last comment. It has a link to the v2 source of that app.

**Comment by 17lwinn** [comment]
I'm on the repo page for the settings on V2, how do I install it?

**Comment by andersevenrud** [comment]
If you're thinking about running it in v3, that's not possible.

If you for some reason want to use v2, just see the INSTALL file on how to set it up.

**Comment by 17lwinn** [comment]
I'm trying it now, I'm closing this now

**Comment by 17lwinn** [comment]
Okay, I've spent a while. 

Could you compile the code into a separate repo or npm package so I can just install it from there?

**Comment by andersevenrud** [comment]
What's the issue ?

**Comment by 17lwinn** [comment]
I wish to just install the settings app from V2, not the entire repo as it takes up all my space.

**Comment by 17lwinn** [comment]
I just need a compilation of the folder you showed me yesterday in a separate repo or mom package

**Comment by andersevenrud** [comment]
As I mentioned in a previous answer:

> If you're thinking about running it in v3, that's not possible.

You can't install v2 apps on v3. If you want to use this settings app, you'll need to install entire v2.

**Comment by 17lwinn** [comment]
Okay, but could you rewrite the application so it runs on V3?

**Comment by andersevenrud** [comment]
Rewriting the v2 app is much more work than just to change the UI of the one in v3 to look similar. The APIs are completely different.

**Comment by 17lwinn** [comment]
I know

Do you know any other repos that has done this?

**Comment by andersevenrud** [comment]
All of the v3 apps is basically rewrites of the v2 ones. The only one that differs in style is the settings app.

https://github.com/os-js?utf8=%E2%9C%93&q=-application&type=&language=

**Comment by andersevenrud** [comment]
If you want to request changes to the settings app, just open an issue in the appropriate repo.

**Comment by 17lwinn** [comment]
Okay, thanks

**Comment by 17lwinn** [comment]
One last thing.... Sorry about the long issue

I downloaded RXOS/UI3 and it works great! Just as good as OS.JS V3. Thanks!

**Comment by andersevenrud** [comment]
Thanks for reminding me about that project. I need to do some updates there.

**Comment by andersevenrud** [comment]
Btw, I started making a quick prototype of this, and I really have to expose more settings, because it's looking pretty anemic with so few options.

![OS js](https://user-images.githubusercontent.com/161548/74689062-01044980-51da-11ea-8ac6-c0c6f80b2186.png)

**Comment by 17lwinn** [comment]
That looks great! are you planning to release when it's done?

**Comment by andersevenrud** [comment]
@17lwinn Yes.

**Comment by 17lwinn** [comment]
Okay, well i tried to make the app store. #722 i'd check.

Thanks

**Comment by 17lwinn** [comment]
is the settings application ready?

**Comment by andersevenrud** [comment]
@17lwinn I sadly haven't had time to look more into this.

**Comment by 17lwinn** [comment]
okay
