### ISSUE TITLE
Rebooting WiFi

### ISSUE THREAD

**Issue by pjockey** [os-js/OS.js#737]
An unexpected error occured, maybe a bug.

> Please report this if you think this is a bug. Include a brief description on how the error occured, and if you can; how to replicate it

```
TypeError: Cannot read property 'ssid' of undefined
    at http://arduino.local/packages/target/ArduinoWizardSettings/combined.js?49919:225:34
    at Object.ontimeout (http://arduino.local/packages/target/ArduinoWizardSettings/combined.js?49919:532:28)
    at XMLHttpRequest.request.ontimeout (http://arduino.local/osjs.js:1248:14)
```

**Comment by andersevenrud** [comment]
Please look at the following issue: https://github.com/os-js/OS.js/issues/436#issuecomment-415601684
