### ISSUE TITLE
Connection Lost on OS.js 3 - CentOS 8

### ISSUE THREAD

**Issue by jashirouprotips** [os-js/OS.js#738]
Hi,

I have this problem with OS.js on CentOS as a server.

I've setup os.js with NGINX as a reverse-proxy following the installation documentation.

_This is the alert message (this alert jump every minute)._
![image](https://user-images.githubusercontent.com/29470002/79032232-18b8d800-7b62-11ea-9ac0-1805d393fc07.png)

_This is the NGINX config file._
![image](https://user-images.githubusercontent.com/29470002/79032175-a811bb80-7b61-11ea-8df5-b254e2610ca0.png)

_This is the OS.js server_
![image](https://user-images.githubusercontent.com/29470002/79032253-36863d00-7b62-11ea-803e-4f22cdc8dd2b.png)

I have disabled the firewalld and the problem persist.

**Thanks in advance os.js team**

Atte. Jashirou

**Comment by andersevenrud** [comment]
I can confirm this is an issue on nginx across all platforms. Turns out nginx closes the connection after 60s of inactivity.

One solution for this is to increase this timeout in the nginx config, however I'm going for another solution in `@osjs/server` that pings the client every X seconds.

**Comment by andersevenrud** [comment]
If you run `npm update` and restart the OS.js server, this should now be fixed :)

**Comment by jashirouprotips** [comment]
Thanks @andersevenrud  it worked perfectly 👍. No more lost connection. 🥇

**Comment by andersevenrud** [comment]
Glad to hear it :)
