### ISSUE TITLE
Use dotenv and provide example

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#743]
Split out from https://github.com/os-js/OS.js/issues/742

It would be nice to use `dotenv` by default to allow overriding the very basic `foo/config.js` defaults, as well as a `.env.example` for reference.

This could probably also contain the docker-composer variables as well.

**Comment by andersevenrud** [comment]
I added a section about this in the manual. So I'm closing this issue.

https://github.com/os-js/manual.os-js.org/commit/3ed7080e0cbb5fdf3877dcfe32b7156e5d72c5a3

Since I'm doing some passes on the manuals at this moment this will get better documented.

**Comment by maryam4s26** [comment]
hi @andersevenrud.
I want to manually set the parameters in the server and client config files through the . env are initialized.
So I have added the .env file to the project.
I have used it in the server configuration file as follows.
```js
require('dotenv').config();
module.exports = {
  root,
  port: process.env.PORT,
  public: path.resolve(root, 'dist'),
}
```

I have also used the following in the client config file.
```js
import 'dotenv/config';
export default {
  session:{
    timeout: process.env.CLIENT_SESSION_TIMEOUT
  },
}
```
But in the client, I get the value of timeout parameter as undefined.

**Comment by andersevenrud** [comment]
Didn't you solve this here https://github.com/os-js/osjs-client/issues/208 ?

**Comment by andersevenrud** [comment]
The server does not require anything extra. ENV vars are passed always.

**Comment by andersevenrud** [comment]
> Didn't you solve this here https://github.com/os-js/osjs-client/issues/208 ?

Hm. Come to think of it you probably might have to add a Webpack plugin. Try https://github.com/mrsteele/dotenv-webpack, but with an older version (6.x.x) for the webpack used here.

The standalone `dotenv` package probably won't work here.

**Comment by maryam4s26** [comment]
> Didn't you solve this here [os-js/osjs-client#208](https://github.com/os-js/osjs-client/issues/208) ?

This issue https://github.com/os-js/osjs-client/issues/208 was for use in Docker.
Here is the question for developer mode.
