### ISSUE TITLE
Add package

### ISSUE THREAD

**Issue by MortezaBiabani** [os-js/OS.js#746]
Hi,

We have developed SWIFT-VFS-Adapter package  for OS.js. The link is available at the following address:

[OS.js SWIFT VFS Adapter](https://github.com/BurnaSmartLab/osjs-monster-adapter)

We want our package included to OS.js as an adapter such as webdav or FTP.
What process should we do to do this?

Best,
Morteza

**Comment by andersevenrud** [comment]
1. Put source onto github. This should preferably use the official eslint rules: https://github.com/os-js/eslint-config
2. Publish onto npm with the following naming convention: https://manual.os-js.org/v3/development/#naming
3. Create a pull-request here: https://github.com/os-js/manual.os-js.org/blob/master/src/v3/resource/contrib/README.md

In step 2 I recommend also adding a keyword to your package: https://github.com/os-js/osjs-ftp-adapter/blob/master/package.json#L15
