### ISSUE TITLE
Package into a bootable disk?

### ISSUE THREAD

**Issue by sfmemz** [os-js/OS.js#748]
This seems to be a dumb question, but I'm still wondering if we can package this into a bootable disk, because I think Javascript is enough for anything.

**Comment by andersevenrud** [comment]
Hey! I actually have a setup for this based on Debian that runs an Electron instance in sort of a "kiosk mode" on X11.

I think I have this on Github, but might be private. I'll look into it and get back to you ASAP. I was just heading to bed :)

**Comment by TwilightSparkleLover** [comment]
Okay thanks :)

**Comment by andersevenrud** [comment]
Sorry for taking so long to reply.

This is the repository I was thinking about: https://github.com/andersevenrud/osjs-debian -- this produces a debian package that can be installed onto an image.

Now, I notice that the following is missing:

1. The electron wrapper
2. Bootable image creator

I'm going to look into those things this week so I can produce a fully working image and upload it here for you.

**Comment by TwilightSparkleLover** [comment]
Okay. :)

**Comment by andersevenrud** [comment]
Just a small status update.

I've updated the linked repository to build a proper Debian package as well as as Live ISO image with a fully set up environment.

This has been successfully working when testing on a local setup, but not the Live environment, so I have a few small things to iron out (hopefully this weekend) and I'll upload the working binaries :)

**Comment by andersevenrud** [comment]
Closing this issue because it's stale (doing a cleanup) and any further discussion can be taken in the linked repo.
