### ISSUE TITLE
Peer packages 

### ISSUE THREAD

**Issue by Freddson** [os-js/OS.js#750]
I tried running OS.js on localhost on my PC. I ran npm install, but halfway through the process it sends these errors:
`
npm WARN hyperapp-nestable@1.1.0 requires a peer of hyperapp@1.1.x but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

I tried installing hyperapp, sass and fibers, but they all sent errors, and the .bat still didn't work. I don't know why, and if someone knows the issue i'd be really grateful.

**Comment by andersevenrud** [comment]
Those are not errors (but rather warnings) and can safely be ignored.

Also what `.bat` are you mentioning here ?

**Comment by Freddson** [comment]
I made a .bat file with all the scripts i need to run to make OS.js run on localhost, the code is:
`npm install
npm install @osjs/example-application
npm run package:discover
npm run build
npm run serve
pause`

**Comment by Freddson** [comment]
It worked! Thank you!

**Comment by andersevenrud** [comment]
Cool!
