### ISSUE TITLE
Cannot open files outside context menus

### ISSUE THREAD

**Issue by Maho91** [os-js/OS.js#754]
Hi Anders, 

You have solved the mounting problem of the WebDAV, However when I try to open one PDF, Image or Soundtrack, the player, pdf reader or image viewer all run and open empty.

Any help and thank you in advance ?

**Comment by andersevenrud** [comment]
PS: Moved this issue to the main repo and changed the title

**Comment by Maho91** [comment]
Ok, Anders, 

Simply I added Apache Guacamole VMs and Remote apps to be showing inside OSjs Desktop as Iframe apps via one Iframe viewer. So I had to change over the menu, file manager, and desktop to achieve this. everything worked but now I realized this issue. 

I will let you know what is the flow of what is have done as soon as I solve the issue

**Comment by andersevenrud** [comment]
> So I had to change over the menu, file manager, and desktop to achieve this.

The "file manager" part sounds like where the problem lies :sweat_smile: 

I'm a bit interested how this works in practice and what you changed to achieve this though. I assume you changed the application menu to launch whatever you needed, but what was changed in the desktop and fm app ?

**Comment by Maho91** [comment]
Sure, man, it has been some month since I have work on this task I need to see the code again to remember the places I have changed, and on Monday while trying to solve the issue gladly I will send you all the changes so you see it for yourself. Actually, It might not be the best practice 😅  however eventually it got a correct result.

**Comment by andersevenrud** [comment]
Alright :+1: 

> Actually, It might not be the best practice sweat_smile however eventually it got a correct result.

Getting a result is the important part, hehe. If you want I could probably do a review and give you some thoughts on how to make a better approach if you plan on working further with this.

**Comment by Maho91** [comment]
Hi Anders, I have solved the issue, it happened because I have sent a "URL" instead of the args. Now I changed it to embed the URL to the args and it worked correctly.

The approach I have done is listed as below:

1- (osjs-server) a service provider that prepares the URLs.
2-  (osjs-client/src/auth.js- init function) get the URLs and store it in the local storage.
3- (osjs-client/src/pacaghe.js- init function) get the URLs from the local storage and loop to generate the metadata for each URL with including the Viewer name and the URLs. finally, embed it into the class Metadata. Here I had to use the local storage not to call the server directly because the function is not a synchronized so I could not await the promises. 

```
if (localStorage.getItem('guacamole') !== null) {

      const urls = localStorage.getItem('guacamole');

      if (urls !== undefined) {
        for (let i = 0, len = JSON.parse(urls).length; i < len; i++) {
          console.log(JSON.parse(urls)[i]);

          this.metadata.push({
            category: 'development',
            description: {
              en_EN: JSON.parse(urls)[i].name,
            },
            files: ['main.js'],
            mimes: ['^text/html?'],
            length: '1',
            icon: 'remoteico.png',
            name: 'viewer',
            server: null,
            title: {
              en_EN: JSON.parse(urls)[i].name,
            },
            type: 'application',
            url: JSON.parse(urls)[i].url,
          });
        }
      }
    }
```

4- (osjs-client/src/adapters/vfs/apps.js- adapter function) modify the callback 

```
filename:
            pkg.url === undefined ? pkg.name : pkg.title.en_EN,

path:
            pkg.url === undefined
              ? `${path.replace(/(\/+)?$/, '/')}${pkg.name}`
              : `${path.replace(/(\/+)?$/, '/')}${pkg.title.en_EN}`,
url: pkg.url,
```

5- (osjs-client/src/launch.js- init function) check the package name if it included as a package. launch the package that has the title.name with the viewer. and pass the URL to the panels the args in the case of menu clicks or to the viewer in the case of file manager or desktop icons.

```
let metadata = this.metadata.find((pkg) => pkg.name === name);
    if (!metadata) {
      metadata = this.metadata.find((pkg) => pkg.title.en_EN === name);
      args.url = metadata.url;
    }
```

6- (osjs-panels/src/items/menu.js- createItem method)

```
icon: getIcon(m, icon),
    label: getTitle(m),
    data: {
      name: m.name,
      url: m.url
    }
```

7- (osjs-panels/src/items/menu.js- MenuPanelItem class- onclick method) modify to pass the URLs.

```
 this.core.make('osjs/contextmenu').show({
        menu: makeMenu([].concat(packages)),
        position: ev.target,
        callback: (item) => {
          const {name, action, url} = item.data || {};
          if (name) {
            this.core.run(name, {url:url});
          } else if (action === 'saveAndLogOut') {
            logout(true);
          } else if (action === 'logOut') {
            logout(false);
          }
        },
        toggle: true
      });
```

**Comment by andersevenrud** [comment]
Hey!

Looking at this code, I think you can achieve the same result with the following:

```javascript
import { Core, Packages, CoreServiceProvider } from '@osjs/client'

class MyPackages extends Packages {
  async init() {
    const result = await super.init();

    // Override packages registry
    const urls = await this.core.request('/endpoint-with-urls')
    const metadatas = urls.map(({ name, url }) => ({
      name: `Guacamole${name}`,
      type: 'application',
      category: 'development',
      title: {
        en_EN: name,
      },
      description: {
        en_EN: name,
      },
      files: [],
      mimes: [],
      guacamole: {
        url
      }
    }))


    this.addPackages(metadatas)

    return result;
  }

  // Makes guacamole apps launch in viewer app
  _launchApplication(name, metadata, args, options) {
    if (metadata.guacamole) {
      return super._launchApplication('viewer', metadata, args, options);
    }

    return super._launchApplication(name, metadata, args, options);
  }
}

class MyCoreServiceProvider extends CoreServiceProvider {
  constructor(core, options = {}) {
    super(core, options)

    // Override package manager instance
    this.pm = new MyPackages(core);
  }
}

const init = () => {
  const osjs = new Core(config, {});
  // Register our overrides
  osjs.register(MyCoreServiceProvider);
  osjs.boot();
};

window.addEventListener('DOMContentLoaded', () => init());
```

If you give me an example JSON file I could probably test it myself -- I just wrote this blindly with your code as a reference.

**Comment by andersevenrud** [comment]
Silly me, you're just using the name and url, so I mocked one myself. This is what you need to change in the code above:

```javascript
  // Makes guacamole apps launch in viewer app
  _launchApplication(name, metadata, args, options) {
    if (metadata.guacamole) {
      const realName = 'GuacamoleViewer'; // NOTE: Change to fit your needs
      const realMetadata = this.metadata.find(pkg => pkg.name === realName);

      return super._launchApplication(realName, realMetadata, {
        ...args,
        ...metadata.guacamole
      }, options);
    }

    return super._launchApplication(name, metadata, args, options);
  }
```

You can then get the URL from `args.url` in your viewer app and do whatever you need with it :)

**Comment by Maho91** [comment]
Many thanks Anders for your efforts, I will use this. Code. 💯

**Comment by andersevenrud** [comment]
Cool! Let me know how it works out :)
