### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by Vb-dM** [os-js/OS.js#758]
Terminal. Along with fully controllable manual how to programmatically manipulate interface from node js running in background.

I hope it's not react.

Thank you.

I know doing requests is hard but... Whatever.

**Comment by andersevenrud** [comment]
I've made an xterm implementation: https://github.com/os-js/osjs-xterm-application .

Also a concept for a system terminal: https://github.com/andersevenrud/osjs-terminal-application .

> Along with fully controllable manual how to programmatically manipulate interface from node js running in background

What is a a controllable manual ?
