### ISSUE TITLE
Is there a new standalone version?

### ISSUE THREAD

**Issue by hello-smile6** [os-js/OS.js#760]

**Comment by andersevenrud** [comment]
Sorry, but I don't understand what you mean by "new" here. Care to elaborate ?

**Comment by hello-smile6** [comment]
Is there an updated version of the standalone build?

**Comment by andersevenrud** [comment]
I don't host any ready-built standalone versions. You can make an up-to-date version yourself by making your own installation, then:

https://manual.os-js.org/guide/standalone/

**Comment by hello-smile6** [comment]
I still don't have the necessary software.

**Comment by andersevenrud** [comment]
The only software you need is nodejs and that is free and easy to install.

**Comment by andersevenrud** [comment]
Closing this issue because there's discussion in #742 about this.
