### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Yutyo** [os-js/OS.js#765]
I think it should be possible to change icon and desktop theme within the os.js. It would be also great to have an app store where new themes and software for os.js can be installed as said in #722 .

**Comment by andersevenrud** [comment]
It's possible to customize pretty much every aspect of this project, including themes (icons, desktop, components, general styles), initial styles defined via stylesheets, window decorations, etc.

Themes are provided as packages, just like applications. 

Most of the stuff is changed via [configuration](https://manual.os-js.org/config/).

A couple of articles on this subject (there's more than this, all in the manual):

* [Create your own themes](https://manual.os-js.org/tutorial/theme/)
* [Customize general visuals](https://manual.os-js.org/guide/visuals/)


There's an open issue about app store here: https://github.com/os-js/OS.js/issues/722

**Comment by Yutyo** [comment]
PS: I also think that the default icon theme shouldn't be the Gnome ones anymore. It doesn't match the default theme and is very outdated. I would suggest using a custom (purple-based rather than blue) papirus instead.

**Comment by andersevenrud** [comment]
> I think it should be possible to change icon and desktop theme within the os.js

This is done via Settings app.

**Comment by andersevenrud** [comment]
> I also think that the default icon theme shouldn't be the Gnome ones anymore.

Create a separate issue for this and I'll add a poll.
