### ISSUE TITLE
Change default icon theme

### ISSUE THREAD

**Issue by yutyo** [os-js/OS.js#766]
I think that the default icon theme shouldn't be the Gnome ones anymore. It doesn't match the default theme and is very outdated. I would suggest using a custom (purple-based rather than blue) papirus instead.

**Comment by hello-smile6** [comment]
What about using the MacOS Big Sur icons? They're pretty much universal.

**Comment by andersevenrud** [comment]
@hello-smile6 Not sure that's possible due to licensing, copyright, etc.

**Comment by Yutyo** [comment]
@hello-smile6 also don't underestimate the FOSS community. There are bunch of cool and public icon themes out there which make MacOS look obsolete.

**Comment by Yutyo** [comment]
I have a noob attempt at this repo: https://github.com/mercode-org/osjs-papirus-icons

**Comment by vkuehn** [comment]
@yutyo your link should probably be https://github.com/mercode-org/papirus-mer-icon-theme

apart from that. Yes in the moment it looks all ugly but the idea is nice.
Synologies Diskstation has a nice one but also a license issue.

why not having a more exotic solution where things are 3d like in the three js examples ?

**Comment by andersevenrud** [comment]
Closing because issue went stale.
