### ISSUE TITLE
Add miniPaint as default image editor

### ISSUE THREAD

**Issue by Yutyo** [os-js/OS.js#767]
There is an open source web based image editor called miniPaint: https://github.com/viliusle/miniPaint

**Comment by andersevenrud** [comment]
I don't use third party stuff for the default official packages because I cannot provide support for it and has a very high "cost" when it comes to maintenance on my part.

Another issue with apps like this is that it's usually not easy to add in features like the VFS, dialogs, etc. in OS.js (even more job since this is designed to run in an iframe).

Shipping it on the side as an alternative is the best way.

**Comment by hello-smile6** [comment]
> I don't use third party stuff for the default official packages because I cannot provide support for it and has a very high "cost" (time) when it comes to maintenance on my part.
> 
> Another issue with apps like this is that it's usually not easy to add in features like the VFS, dialogs, etc. in OS.js (even more job since this is designed to run in an iframe).
> 
> Shipping it on the side as an alternative is the best way.

Why not add it to your set of packages?

**Comment by andersevenrud** [comment]
> Why not add it to your set of packages?

That was the alternative I was thinking of. Shipping it on the side and have it in the official list(s).

**Comment by hello-smile6** [comment]
You have plenty of packages on NPM already. Why not just redesign it, change element class references to add menus to the title bar of OS.JS, and you'd have it!

**Comment by andersevenrud** [comment]
> You have plenty of packages on NPM already

Sure. But all of the default installed apps are first-party. That was kind of my point in the initial response here.

> Why not just redesign it, change element class references to add menus to the title bar of OS.JS, and you'd have it!

That's the thing. I don't really have time to do this kind of stuff. The time I have to spare goes into maintenance and enchantments in the core.

If anyone wants to take on this task, then please do and submit it and I will put it into the documentation, etc.
