### ISSUE TITLE
Adding Office to OSjs

### ISSUE THREAD

**Issue by mahsashadi** [os-js/OS.js#769]
Hello 

we have a plan to add **office** into OSjs.‌ We consider using a compatible open source app. Some available office apps are mentioned in [https://blog.cloudron.io/four-open-source-alternatives-to-google-docs/](https://blog.cloudron.io/four-open-source-alternatives-to-google-docs/)

Now we have two options:

1.  Adding office app in a native manner in OSjs. In this way, for example the user can right click on a file in File Manager and open it via the available office apps. 
2.  Making office apps to be available externally via a URL in the browser. In this way, we also need to develop an application in Osjs to handle server-side tasks as browsing among available files or saving them.

Which option is more accessible and time-saving in your idea? 
Do you think the open source apps, listed in the above link, are compatible with OSjs?

**Comment by andersevenrud** [comment]
If these office apps provide a way to open a file via a buffer or something like that then its possible to have a hybrid solution. The actual apps runs in an iframe but there's a bridge that connects to the VFS etc.

**Comment by andersevenrud** [comment]
Out of all the choices in the article, ONLYOFFICE seems the most interesting because you can just slap it onto a docker instance, which would make it very easy to set up. Collabora seems to compare pretty well, but it seems like you have to register to get access to a trial, and not something you can run on your own.

**Comment by mahsashadi** [comment]
> Out of all the choices in the article, ONLYOFFICE seems the most interesting because you can just slap it onto a docker instance, which would make it very easy to set up

So you mean that I can set up ONLYOFFICE docker container, and set the `src` attribute of `iframe` tag with this container address, right?



> but there's a bridge that connects to the VFS etc.

Could you please describe a bit more about this?

**Comment by andersevenrud** [comment]
> So you mean that I can set up ONLYOFFICE docker container, and set the src attribute of iframe tag with this container address, right?

This is correct. 

> Could you please describe a bit more about this?

I looked up their docs and found that they have support for [Integration connectors
](https://api.onlyoffice.com/editors/plugins) like NextCloud. This means that it's possible to write one that communicates with the OS.js VFS HTTP API.

**Comment by msjavan** [comment]
ONLYOFFICE has problem with RTL support [since 2016](https://github.com/ONLYOFFICE/DocumentServer/issues/19)  
It seems that Collabora is better. It has integration capabilities with external web applications (e.g. owncloud); hope to be integrated with osjs using iframe.

**Comment by andersevenrud** [comment]
How do you even get Collabora ?

**Comment by mahsashadi** [comment]
We consider using its [docker image with own cloud](https://www.collaboraoffice.com/code/quick-tryout-owncloud-docker/), but it seems it does not have all features!

**Comment by andersevenrud** [comment]
What features are missing from this setup ?

**Comment by mahsashadi** [comment]
We did not complete the setup, I could not integrate owncloud with collabora yet, so not sure!
Up to now, the missing features were about owncloud, which was not responsive as I try.

**Comment by mahsashadi** [comment]
Hi again :)
We have finished developing **Office application v1** in OS.js.
It is available in [NPM Registery](https://www.npmjs.com/package/@burna/osjs-office-collabora) and [Github](https://github.com/BurnaSmartLab/osjs-office-collabora).

We would be happy if you agree to contribute it in Osjs project.

**Comment by mahsashadi** [comment]
Pull request : https://github.com/os-js/manual.os-js.org/pull/36

**Comment by andersevenrud** [comment]
Woah! This looks awesome :D Nice job!
