### ISSUE TITLE
Add file upload progress indicator 

### ISSUE THREAD

**Issue by valp124** [os-js/OS.js#775]
When uploading large files from File Manager, it's always a nail-biter waiting for the magic to happen. It would be super useful to see the progress of the upload, or at least have some kind of indicator that it's still in progress. The browser automatically takes care of that for the downloads, wish it were the case for uploads, as well...

Thanks a bunch!

**Comment by andersevenrud** [comment]
I'll look into that. The current upload mechanic used is via `fetch` which does not support progress events, sadly. However `XMLHttpRequest` does, which should be fairly easy to add support for and should not impact performance.

Note to self:

* Add abstraction for XMLMHttpRequest that is identical to the fetch one
* Add progress event callback to upload VFS api function options
* Add support for optional text in progress dialog
* Update the upload api dialog with new option and add translation texts

**Comment by andersevenrud** [comment]
This has been implemented :blush: 

You have to update the following packages:

* `osjs/client`
* `osjs/dialogs`
* `osjs/filemanager-application`

**Comment by valp124** [comment]
You're awesome, man!! This looks great, but with one caveat 😜

![image](https://user-images.githubusercontent.com/7969539/126837769-874089d7-0b75-47aa-8894-ba86d480ac00.png)


It stays at `0%` until the file is uploaded, and then disappears. No incremental progress. (Maybe I'm doing something wrong...)

**Comment by andersevenrud** [comment]
Initial thoughts are:

1. One of the packages did not get updated
2. `npm run build` was not executed
3. cache ?

**Comment by andersevenrud** [comment]
Hold on... I think  might have forgotten something here on my end :blush:

**Comment by valp124** [comment]
I was gonna say, check on all three items ;)

**Comment by andersevenrud** [comment]
Sorry about that... I forgot to add a detection of which progress to used. What you saw was the response :joy: Update `@osjs/client` and it should display correctly.

**Comment by andersevenrud** [comment]
Also, I just realized that the upload is a modal -- that's not really good UX. I'll take care of that one.

**Comment by andersevenrud** [comment]
> I'll take care of that one.

`@osjs/filemanager-application` has been updated wit this.

**Comment by valp124** [comment]
Awesome, the progress is working! 😁

**Comment by andersevenrud** [comment]
Sweet!

If you want any changes or improvements to this, please file an issue here: https://github.com/os-js/osjs-filemanager-application

**Comment by valp124** [comment]
This is awesome, man!! Thank you so much!

I have a suggestion for the file manager, but it's something different. I forget if I had mentioned it. It'd be great to be able to expand the left panel in the case below:

![image](https://user-images.githubusercontent.com/7969539/126843353-4b8c4ed3-d46c-4749-9b1e-d1d389974044.png)

I can submit an issue if I haven't yet 😊

**Comment by andersevenrud** [comment]
I just pinged you in an issue you made about the UI gitch there.

As for resizing, hold and drag your cursor between the panes (the gray space). You should get a cursor indication when you're at the correct spot.

**Comment by valp124** [comment]
Yep, resizing the _pane_ works, but the file names remain cut. And yes, I can see the issue I have submitted. Memory, my man, doesn't work the same way as before at my age 🤓

**Comment by andersevenrud** [comment]
My memory is starting to degrade as well... but so far only the less important stuff is getting garbage collected. Let's hope it stays like :joy: Well, then we can continue the discussion there. I left a quick Q for you there.
