### ISSUE TITLE
No such file or directory npm error in docker mode

### ISSUE THREAD

**Issue by mahsashadi** [os-js/OS.js#778]
I need to create a yml file, for creating and configuring osjs container (deployment operation), but I faced a npm error related when trying to run a container from my image.

I already have a container running (I used your yml file of osjs), having these content:
```
node@7b822f0c11d8:/usr/src/osjs$ ls
CONTRIBUTING.md  LICENSE    dist                entrypoint.sh  package-lock.json  packages.json     src  webpack.config.js
Dockerfile       README.md  docker-compose.yml  node_modules   package.json       session-store.db  vfs
```
I added what I neede to osjs and created an image from my running container:

```
docker commit 7b822f0c11d8 hafez/hafez:version1.1

REPOSITORY    TAG          IMAGE ID       CREATED         SIZE
hafez/hafez   version1.1   528fd0061a33   4 seconds ago   923MB
```

I put my yml and config files in myDirectory. Here is the output of ls in myDirectory:
`server-config.js  client-config.js   hafez-docker-compose.yml`

This is the hafez-docker-compose.yml content:

```
version: "3"

services:
  hafez:
    image: hafez/hafez:version1.1
    restart: always
    container_name: hafez
    ports:
      - 8000:8000
    volumes:
      - ./server-config.js:/usr/src/osjs/src/client/config.js
      - ./client-config.js:/usr/src/osjs/src/server/config.js
```
And here is the output of docker-compose -f hafez-docker-compose.yml up :thinking: 

```
Creating hafez ... done
Attaching to hafez
hafez    | npm WARN saveError ENOENT: no such file or directory, open '/usr/src/osjs/package.json'
hafez    | npm WARN saveError EACCES: permission denied, open '/usr/src/osjs/package-lock.json.1134850457'
hafez    | npm WARN enoent ENOENT: no such file or directory, open '/usr/src/osjs/package.json'
hafez    | npm WARN osjs No description
hafez    | npm WARN osjs No repository field.
hafez    | npm WARN osjs No README data
hafez    | npm WARN osjs No license field.
hafez    | 
hafez    | up to date in 1.506s
hafez    | found 0 vulnerabilities
hafez    | 
hafez    | npm ERR! code ENOENT
hafez    | npm ERR! syscall open
hafez    | npm ERR! path /usr/src/osjs/package.json
hafez    | npm ERR! errno -2
hafez    | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/osjs/package.json'
hafez    | npm ERR! enoent This is related to npm not being able to find a file.
hafez    | npm ERR! enoent 
hafez    | 
hafez    | npm ERR! A complete log of this run can be found in:
hafez    | npm ERR!     /home/node/.npm/_logs/2021-09-17T11_15_37_791Z-debug.log
hafez    | npm ERR! code ENOENT
hafez    | npm ERR! syscall open
hafez    | npm ERR! path /usr/src/osjs/package.json
hafez    | npm ERR! errno -2
hafez    | npm ERR! enoent ENOENT: no such file or directory, open '/usr/src/osjs/package.json'
hafez    | npm ERR! enoent This is related to npm not being able to find a file.
hafez    | npm ERR! enoent 
hafez    | 
hafez    | npm ERR! A complete log of this run can be found in:
hafez    | npm ERR!     /home/node/.npm/_logs/2021-09-17T11_15_38_196Z-debug.log
hafez    |   Usage: nodemon [nodemon options] [script.js] [args]
hafez    | 
hafez    |   See "nodemon --help" for more.
hafez    | 
```
The problem is not about `docker-compose,` since I have a same error with `docker run`.
Do you know how can I fix this error and create/config container successfully?

**Comment by andersevenrud** [comment]
What's the contents of the Dockerfile that creates `hafez/hafez:version1.1`?

**Comment by mahsashadi** [comment]
I have not written any docker-file (since I am not familiar with). I just use docker commit which seems cause the problem.

**Comment by andersevenrud** [comment]
Hm. I don't think I've ever had to use the commit command before. What you wanna do is to create a Dockerfile here so you have a proper base image that is built automatically.

**Comment by mahsashadi** [comment]
https://docs.docker.com/engine/reference/commandline/commit/
But its task actually is to make an image from running docker container! I did not understand why such errors may happen.

**Comment by andersevenrud** [comment]
Have you tried inspecting the docker image ? For example with a tool like https://github.com/wagoodman/dive

**Comment by mahsashadi** [comment]
I made some progress, but still I have problems.

To start, I just want my **vfs_adapter package**  work in osjs, using dockerFile.

Here is my **DockerFile**: (I just add the package and change server index file)
Run with `docker build . -t hafez/hafez:version1.1`
```
FROM node:10
WORKDIR /usr/src/osjs
ADD . .
RUN npm install
RUN npm install @burna/osjs-monster-adapter
RUN npm run build
RUN npm run package:discover
ADD files/server-index.js ./src/server/index.js

EXPOSE 8000

CMD npm run serve
```

Here is my **docker compose yml file**: (I Need to apply configs)
Run with `docker-compose -f hafez-docker-compose.yml up`
```
version: "3"

services:
  hafez:
    image: hafez/hafez:version1.1
    restart: always
    container_name: hafez
    ports:
      - 8000:8000
    volumes:
      - ./client-config.js:/usr/src/osjs/src/client/config.js
      - ./server-config.js:/usr/src/osjs/src/server/config.js
```
But my adapter does not work (seems the configs don't applied)
Also some of icons are not rendered (like search icon).

Can you help how should I change these files to work properly?

**Comment by andersevenrud** [comment]
> But my adapter does not work (seems the configs don't applied)

This is because client needs to be built with settings. It will not work with a volume.

## Solution 1

```
FROM node:10
WORKDIR /usr/src/osjs
ADD . .
ADD files/server-index.js ./src/server/index.js
ADD files/client-config.js ./src/server/config.js
RUN npm install
RUN npm install @burna/osjs-monster-adapter
RUN npm run build
RUN npm run package:discover
EXPOSE 8000
CMD npm run serve
```

## Solution 2

```
FROM node:10
WORKDIR /usr/src/osjs
ADD . .
ADD files/server-index.js ./src/server/index.js
RUN npm install
RUN npm install @burna/osjs-monster-adapter
RUN npm run package:discover
EXPOSE 8000
CMD my-entrypoint.sh
```

Where `my-entrypoint.sh` is:

```
#!/bin/sh
npm run build
npm run serve
```

and then keep your current volume.

**Comment by andersevenrud** [comment]
Ideally you'd just make a whole pre-made image, remove your volumes, and then instead use an environmental file if you need credentials etc in the server (that you can access via `process.env`).

**Comment by mahsashadi** [comment]
Great, I applied your comment for server configs :+1: Thanks.
What is your suggestion if any client configs needed, for example _Mountpoint label_.
I think I should use some simple json files, use it in docker-compose volumes.

**Comment by andersevenrud** [comment]
I already suggested a solution for how you can create a docker build with the client config.

Remember that the client always needs to be pre-built!

--

If you want to dynamically load something, not embed it inside the build then you can just side load it. For example:

`src/client/index.ejs`:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="google" content="notranslate" />
    <meta name="description" content="OS.js - JavaScript Cloud/Web Desktop Platform" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title><%= htmlWebpackPlugin.options.title %></title>

    <!-- Dynamically loaded files here. These area ALWAYS loaded before the bundles -->
    <script src="my-dynamic-script.js"></script>
  </head>
  <body>
  </body>
</html>
```

`src/client/config.js`:

```js
import deepmerge from 'deepmerge';

// Make sure to fall back to empty objects to not make things crash
const myNameSpace = window.myNameSpace || {}
const dynamicConfig = myNameSpace.osjsConfig || {}

const defaultConfig = {
  auth: {
    login: {
      username: 'demo',
      password: 'demo'
    }
  }
}

const config = deepmerge(defaultConfig, dynamicConfig)

export default 
```

Now you can have the following volume:

```yaml
services:
  osjs:
    volumes:
      - ./my-dynamic-script.js:/usr/src/osjs/dist/my-dynamic-script.js
```

And you can make your file `my-dynamic-script.js` look like the following to export your configs:

```js
window.myNamespace = window.myNamespace || {}
window.myNameSpace.osjsConfig = {
  auth: {
    login: {
      username: 'override',
      password: 'override'
    }
  }
}
```
