### ISSUE TITLE
use os.js as linux graphical environment

### ISSUE THREAD

**Issue by essential-existence** [os-js/OS.js#787]
Hello! Is it possible to use os.js as a graphical linux environment, i.e. instead of x11-server, wayland, LXQt, and so on? Or is os.js something more abstract and different?

**Comment by andersevenrud** [comment]
It's technically possible by using Electron or similar technologies (basically kiosk mode, like [this](https://github.com/andersevenrud/osjs-debian)). Still requires X or Wayland though.

The intended usage is as a browser application platform.

**Comment by essential-existence** [comment]
OK, thanks!
