### ISSUE TITLE
Define a command to install customized patch 

### ISSUE THREAD

**Issue by mahsashadi** [os-js/OS.js#790]
After cloning [OSjs project](https://github.com/os-js/OS.js.git), I need to install my patch by simply executing one command in terminal (right after installation commands).
My patch include adding or changing files, for example:

-  adding some fonts files
-  changing client index file to add some tray icon. 

What is you suggestion for this functionality?

**Comment by andersevenrud** [comment]
Sound like all you need is a shell script maybe ?

**Comment by mahsashadi** [comment]
By executing a script, I think all needed files for changes should be available.
I need it to be as simple as executing a command like `npm`.

**Comment by andersevenrud** [comment]
> So, is there any better way to achieve this?

Create a fork of the repo and replace anything you need.

**Comment by andersevenrud** [comment]
This repo almost never changes. It's just a basic template project.

But if you want to get the updates, simply add a upstream remote that points to this repo in your project, then do a git merge.

**Comment by andersevenrud** [comment]
https://stefanbauer.me/articles/how-to-keep-your-git-fork-up-to-date
