### ISSUE TITLE
Autostarting widgets

### ISSUE THREAD

**Issue by mr0rogers** [os-js/OS.js#791]
Applications can be set to autostart on login in their metadata.json files. Is it possible to create a widget that starts by default for all users? If not, how would one go about doing this?

**Comment by andersevenrud** [comment]
There is no setting for this like in applications. But I think you can achieve this by using the following in your config.

This will create a set of defaults for all users:

```
{

  settings: {
    defaults: {
      'osjs/desktop': {
        widgets: [
          {
            name: "WidgetName",
            options: {}
          }
        ]
    }
  }
}
```

**Comment by mr0rogers** [comment]
Yep, that works. Thanks!
