### ISSUE TITLE
Disable transparency to unfocussed Windows

### ISSUE THREAD

**Issue by rocheston** [os-js/OS.js#792]
How do I disable the transparency to unfocussed windows on the desktop? I want all the windows to be visible fully. Even unfocused ones. Please help!

Love your project. I just wish Apple created this OS for their iPad.

![grab1](https://user-images.githubusercontent.com/16910669/154825368-16b72d0b-3476-4507-ad07-e6c0706c0662.png)

**Comment by andersevenrud** [comment]
Try placing this in your `src/client/index.scss` and do a rebuild:

```
.osjs-window {
  &[data-focused=false] {
    opacity: 1;
  }
}
```

Love the Windows 3.1 you got there. That brings back some memories :slightly_smiling_face:

**Comment by rocheston** [comment]
That worked. Thank you. 😎

**Comment by hello-smile6** [comment]
How win31? v86?

**Comment by rocheston** [comment]
Yes. Windows 3.1 using v86 emulator.
