### ISSUE TITLE
Disable Connection Lost Notification

### ISSUE THREAD

**Issue by rocheston** [os-js/OS.js#793]
I uploaded os.js to our remote server and everything works great. Super smooth. The server uses Cloudflare. There is one problem though. The notification "Connection Lost - The connection to the OS.js was lost. Reconnecting..." keeps popping up every second. Annoying. (There is no connection issue though, everything loads fine) I disabled the Proxy in Cloudflare - but the same issue.

This is the Chrome console message:
>>WebSocket connection to 'ws://www.example.com' failed:  (domain name masked here)
I followed your documentation instructions for Apache2 setup and client config.js change. Still no go.

How do I disable this notification, all notifications? Please help. 

Note: I included NeXTSTEP, Macintosh iframe app screenshots. You might like it. os.js platform is super cool. I'm having so much fun configuring this desktop. Brilliant work. Kudos to the os.js team :)

![grab2](https://user-images.githubusercontent.com/16910669/154839393-039b8216-cad8-4503-adc1-eb0da6fd5d66.png)

![grab2](https://user-images.githubusercontent.com/16910669/154840173-138350b2-35ff-4669-b380-2c76d59fc072.jpg)

![grab3](https://user-images.githubusercontent.com/16910669/154840381-58b16152-90e6-4da7-85d8-83a16c4558bd.jpg)

![grab1](https://user-images.githubusercontent.com/16910669/154840595-fba46317-db48-4f2d-84c7-2cf1710c2039.jpg)

**Comment by andersevenrud** [comment]
Your server is probably not configured correctly for websockets, hence why you see that message.

I would recommend fixing it, but you can disable the connection if you want.


In your client config:

```
{
  ws: {
    disabled: true
  }
}
```
