### ISSUE TITLE
Disable Window Resizing

### ISSUE THREAD

**Issue by rocheston** [os-js/OS.js#794]
**iframe applications** - For some applications I want to lock the window from resizing. How do I do that? Example: I have a clock application and I want to restrict the resizing. Lock the height/width.

What should I add to package/clock/dist/main.js file?

**Comment by rocheston** [comment]
It is not working for iFrame applications. Resizable option is still enabled and I can resize the windows. Here is the code. Please tell me what I am doing wrong? I want to lock the chess game from being resized.


File location: src/Package/AboutMaya/index.js
```

import osjs from 'osjs';
import {name as applicationName} from './metadata.json';

// Our launcher
const register = (core, args, options, metadata) => {
  // Create a new Application instance
  const proc = core.make('osjs/application', {args, options, metadata});

  // Create  a new Window instance
  proc
    .createWindow({
      id: 'AboutMayaWindow', resizable: false,
      title: metadata.title.en_EN,
      icon: proc.resource(proc.metadata.icon),
      dimension: {width: 400, height: 400},
      position: {left: 700, top: 200}
    })
    .on('destroy', () => proc.destroy())
    .render($content => {
      const iframe = document.createElement('iframe');
      iframe.style.width = '100%';
      iframe.style.height = '100%';
      iframe.src = proc.resource('/data/index.html');
      iframe.setAttribute('border', '0');
      $content.appendChild(iframe);
    });
```
![grab0](https://user-images.githubusercontent.com/16910669/155485370-54142790-1eb3-48fa-9ac8-7a4b0f24d665.png)

**Comment by andersevenrud** [comment]
That should be:
```
.createWindow({
  attributes: {
    resizable: false,
  }
})
```

**Comment by rocheston** [comment]
That totally worked. Your support is fantastic. Thank you. 🙏
