### ISSUE TITLE
Disable Download option in File Manager

### ISSUE THREAD

**Issue by rocheston** [os-js/OS.js#795]
How do I disable the 'Download' option in the File Manager application? I don't want users to download anything. They can upload documents though.

![grab0](https://user-images.githubusercontent.com/16910669/155905989-4b8e9ca2-72fa-4d1e-9c03-cac43f02c354.jpg)

**Comment by andersevenrud** [comment]
This is currently not possible to disable via an option. It could be added pretty easily though.

I'll have a look into this ASAP.

**Comment by hello-smile6** [comment]
Couldn't people download files using the same path as is used for HTML viewing?

**Comment by rocheston** [comment]
Thanks. I want to restrict people from downloading copyrighted content.

**Comment by hello-smile6** [comment]
> Thanks. I want to restrict people from downloading copyrighted content.

You'd probably want to use Youtube embeds, then. If you send the data to the browser unencrypted, someone will figure out how to get it.

**Comment by rocheston** [comment]
Encrypted using Cloudflare with Argo tunnel.

**Comment by hello-smile6** [comment]
> Encrypted using Cloudflare with Argo tunnel.

But it's decrypted client-side to play the video, right?

**Comment by rocheston** [comment]
Make it hard for someone to figure that out. I will be hosting company videos, PDF, Word documents, configuration files, training materials, etc. I don't want the user to know you can download easily.

Just like Youtube. You can download the videos if you know the right tool lime wondershare but for a normal person, there is a 'no download' button.

I understand this is not a super-duper content protection mechanism. I simply don't want the download option in my case. I'm building a read-only portal with osjs for an internal work deployment.

**Comment by andersevenrud** [comment]
If you update `@osjs/filemanager-application` you can now to the following in your client config: 

```
// src/client/config.js
export default {
  filemanager: {
    disableDownload: true
  }
}
```

Then rebuild with `npm run build` and the menu item should disappear.

**Comment by rocheston** [comment]
Your solution totally worked. Awesome. The Download option is gone from the file manager application. Thank you, Anders. OS.js makes the best Intranet portal for organizations. What a beautiful platform. And your support is fantastic. Thanks again.
