### ISSUE TITLE
Hide OS.js folder from view in File Manager

### ISSUE THREAD

**Issue by rocheston** [os-js/OS.js#796]
How do I hide the OS.js folder from view? I want it hidden. I don't want the logged-on users to view the system folder. The users should only see the home folder in File Manager and nothing else.

Thanks.

. 
![grab0](https://user-images.githubusercontent.com/16910669/156938383-193abe74-313e-4ecd-ae12-ba114b7f1c74.png)

**Comment by andersevenrud** [comment]
Try the following in your `src/client/index.js` and do a rebuild:

```
const osjs = new Core(config, {});

// Right after line above
const foundMount = osjs.config.vfs.mountpoints.find((mount) => mount.name === 'osjs')
if (foundMount) {
  foundMount.enabled = false
}
```

**Comment by rocheston** [comment]
I configured this in src/client/index.js. Rebuild. Now the login screen does not show up. I only see the blank desktop wallpaper and nothing else. Mysql database is used for authentication. Here is the index.js

`import {
  Core,
  CoreServiceProvider,
  DesktopServiceProvider,
  VFSServiceProvider,
  NotificationServiceProvider,
  SettingsServiceProvider,
  AuthServiceProvider
} from '@osjs/client';

import {PanelServiceProvider} from '@osjs/panels';
import {GUIServiceProvider} from '@osjs/gui';
import {DialogServiceProvider} from '@osjs/dialogs';
import config from './config.js';
import './index.scss';

const init = () => {
  const osjs = new Core(config, {});

  const foundMount = osjs.config.vfs.mountpoints.find((mount) => mount.name === 'os.js')
  if (foundMount) {
      foundMount.enabled = false
  }

  // Register your service providers
  osjs.register(CoreServiceProvider);
  osjs.register(DesktopServiceProvider);
  osjs.register(VFSServiceProvider);
  osjs.register(NotificationServiceProvider);
  osjs.register(SettingsServiceProvider, {before: true});
  osjs.register(AuthServiceProvider, {before: true});
  osjs.register(PanelServiceProvider);
  osjs.register(DialogServiceProvider);
  osjs.register(GUIServiceProvider);

  osjs.boot();
};

window.addEventListener('DOMContentLoaded', () => init()); 
`

Blank screen shows up with no login dialog box.
![grab1](https://user-images.githubusercontent.com/16910669/156940259-638b80ac-f3e2-4fdb-8a0b-12d48c63b508.png)

**Comment by andersevenrud** [comment]
Check devtools for errors.

**Comment by rocheston** [comment]
Safari devtools console:

TypeError: undefined is not an object (evaluating 'osjs.config.vfs.mountpoints')
init — index.js:22

Line 22: const foundMount = osjs.config.vfs.mountpoints.find((mount) => mount.name === 'osjs')

Looks like the system does not recognize osjs. I tries even naming OS.js. Still no go.

**Comment by andersevenrud** [comment]
It should be `configuration`, not `config`. That's where the undefined value comes from.

**Comment by rocheston** [comment]
Your response is ligtning fast Mr. Anders Evenrud. That totally worked. Million thanks. God bless.

![grab2](https://user-images.githubusercontent.com/16910669/156942592-e31d3de1-4370-457f-b7be-b699e31a9cd0.png)

**Comment by andersevenrud** [comment]
Nice!
