### ISSUE TITLE
Can't open files

### ISSUE THREAD

**Issue by for-the-zero** [os-js/OS.js#799]
###### (My English is not good)

**Comment by andersevenrud** [comment]
It's possible to open files from the desktop as long as there is an app supporting the file type.

**Comment by rocheston** [comment]
It is not bad. Why use the desktop for files? You have the File Manager for that. Desktop is a clean place to organize only running Windows. That's it. Placing files on the desktop is the worst thing you can do. OSJS is not like the Microsoft Windows 10/11 crap. It is a beautiful cloud OS.

I love the clean look of the desktop. Display only the wallpaper. The OS project designers are very creative indeed.

**Comment by ajmeese7** [comment]
@rocheston my personal preference is also to not have icons on my desktop, but I like to have the option of the feature. No sense in trying to tell someone where they should put their files :)

**Comment by andersevenrud** [comment]
This got a bit off-topic and there has been no response from OP, so I'm going to close this one.

> but I like to have the option of the feature

In case it's unclear, there's an option to disable the desktop iconview in settings :)

**Comment by ajmeese7** [comment]
It is clear, that's what I was speaking in favor of! Have a good weekend :)
