### ISSUE TITLE
new feature: synchronizes all system notifications with the browser notifications 

### ISSUE THREAD

**Issue by mahdi00021** [os-js/OS.js#829]
@andersevenrud 
**Hello, we have added a new feature to the system which synchronizes all system notifications with the browser. If you are interested, we would like to send a pull request as a new feature to be merged into the main system.**

**File Notification.js is in path:**
`src/client`

**This file called in** `src/client/index.js`

**screenshot of test in os-js:**
**in windows and ubuntu**

![push-hafez-with-browser](https://user-images.githubusercontent.com/9013165/221372931-9191ccaf-79c9-4e4b-bfcd-19243702528f.jpg)

![push-hafez-with-browser-ubuntu](https://user-images.githubusercontent.com/9013165/221372959-31a81d72-ff8a-47b9-83e3-f3a1fd9e26ba.jpg)

**Comment by andersevenrud** [comment]
I'm not really sure if there's a use-case for this to be provided by default.

But if you create a service provider package (npm compatible) and provide the full source I will gladly add it to the documentation.

**Comment by mahdi00021** [comment]
There is no need for a service provider, here you only need a file for notification that is written with JavaScript and called in the index.js
Also, a listener is used in the index file to listen to create notifications

**Comment by mahdi00021** [comment]
this file called in index.js and in 

```
osjs.on('osjs/notification:create', (notification) => {
		   let message = notification.options.message;
		   
		   sendNotification(notification.options.title,message,'#'); 
		   console.log('notificationnotificationnotification',message);
		  
	});
```

this is Notification.js:
```
export default function sendNotification(title, message, url) {
    //First, check notification is supported or not in your browser!
    if (!Notification) {
      console.log('Push notifications are not supported in your browser..');
      return;
    }

    //Ask for permission from user 
    if (Notification.permission !== "granted") {
      Notification.requestPermission();
    } else {
      var notification = new Notification(title, {
        icon: 'favicon.png',
        body: message,
      });

      // Remove the notification when clicked and open the URL.
      notification.onclick = function() {
      
      };

      // Callback function when the notification is closed.
      notification.onclose = function() {
        console.log('Notification closed');
      };
    }
}
```

**Comment by andersevenrud** [comment]
Looks like this is actually creating native notifications. I thought by "synchronize" that it was the other way around.

Creating native notifications is actually already supported globally with configuration `notifications.native` or the `native` option in the service API.

If you want the option to do *both*, simply publish a PR for the client with changes to the Notification to allow that :)

**Comment by mahdi00021** [comment]
Now there isn't this feature in os-js.
that sync all notifications os-js with browser for example Firefox and chorom

Now can I pull request for add this feature?

**Comment by andersevenrud** [comment]
Yes, you can open a Pull Request to add a feature to support **both** "OS.js notifications" and "Native notifications" at the same time.

But just to make sure we're talking about the same thing here; this needs to be implemented in the actual client module.

I.e.: https://github.com/os-js/osjs-client/blob/master/src/notification.js where existing functionality exists.

**Comment by mahdi00021** [comment]
All implement is Notifications.js and call this file in index.js in listener
