### ISSUE TITLE
Remove clock widget in demo

### ISSUE THREAD

**Issue by maryam4s26** [os-js/OS.js#845]
hi @andersevenrud 
Why can't I remove the clock widget? https://demo.os-js.org/
But can I add it indefinitely?

![image](https://github.com/os-js/osjs-widgets/assets/65979871/d791dd5d-de59-47c1-a956-d092b0173713)

**Comment by andersevenrud** [comment]
The widget(s) *should* have a context menu with an option to remove. A bug ?

**Comment by maryam4s26** [comment]
I don't have this problem in my local version, but I encountered this in the demo version

![image](https://github.com/os-js/osjs-widgets/assets/65979871/e8124e6a-1220-4f05-851c-383c0c7bb91c)


I guess you haven't added the following line in the client.
`src/client/index.scss`

```js
@import "~@osjs/widgets/dist/main.css";
```

**Comment by andersevenrud** [comment]
Thank you for reporting this. I just checked my demo setup and the import is missing🤦

**Comment by andersevenrud** [comment]
Fixed!
