### ISSUE TITLE
The latest version of Node compatible with Osjs

### ISSUE THREAD

**Issue by maryam4s26** [os-js/OS.js#852]
hello @andersevenrud 
what is the latest version of NODE that we can use with Osjs without any conflict?

**Comment by andersevenrud** [comment]
Node 16 should work.

https://github.com/os-js/OS.js/issues/785

**Comment by maryam4s26** [comment]
Does it mean it doesn't work with 18 and 20? @andersevenrud

**Comment by andersevenrud** [comment]
I think the legacy Webpack version supplied here is still broken on anything later than 16. You can always try to migrate to a later version of Webpack.

**Comment by andersevenrud** [comment]
FYI you can use https://github.com/nvm-sh/nvm to manage your node on a per directory basis. This way you can lock to 16 inside your osjs stuff.

**Comment by maryam4s26** [comment]
> FYI you can use https://github.com/nvm-sh/nvm to manage your node on a per directory basis. This way you can lock to 16 inside your osjs stuff.

Thank you for your complete explanation.
