### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by marktopper** [os-js/OS.js#853]
Is the OS.js project still active, or has it been abandoned? Just checking to stay aligned. Thanks!

**Comment by andersevenrud** [comment]
Not abandoned :)

This repo is not very active (because it's just a template, really), but others are: https://github.com/os-js

I haven't personally found any time to work on new features (but I do look at all bugs etc coming in), but there are some stuff from contributors in the pipeline.

**Comment by marktopper** [comment]
Perfect. 😄 Thanks @andersevenrud
