### ISSUE TITLE
Single HTML file.

### ISSUE THREAD

**Issue by MuhammedSaleem-Brej** [os-js/OS.js#855]
Hello, I hope you will provide a copy of this operating system as a single HTML file that can be easily shared among users and run anywhere, even on smart devices, without the need for complex tools such as NodeJS and the use of a terminal. Thank you very much.

**Comment by andersevenrud** [comment]
Hi!

This is possible by creating a "standalone" build: https://manual.os-js.org/guide/standalone/ .

After a standalone build the `dist` folder can be shared and you just have to open the `index.html` file within (both with or without a webserver).

I do not provide any ready made standalone builds here on github.

**Comment by andersevenrud** [comment]
It's also possible to use online coding editors and CDN provided libraries to share completely custom systems.

Example: https://codesandbox.io/p/sandbox/w6vrvzo03l
