### ISSUE TITLE
Code Problem in packages

### ISSUE THREAD

**Issue by michaelbong** [os-js/OS.js#859]
An error occured while trying to launch: ApplicationSettings

> Application 'ApplicationSettings' preloading failed:  /packages/target/Settings/combined.js?63558

**Comment by andersevenrud** [comment]
Did this occur on the demo server ? If that's the case then it could be any of the following reasons:

* General intermittent issue on the server
* Usage of VPN and/or adblockers or security filters
* Browser plugin causing some kind of interference
* Some kind of internet connection issue (causing timeouts)

I cannot reproduce this myself, so I can only assume that this is the issue.

---

If this is a problem on a self hosted instance, then I would suggest to start looking at network requests in your browser's devtools, and then at the server logs.
