### ISSUE TITLE
[Applications] Firefox Marketplace App support

### ISSUE THREAD

**Issue by andersevenrud** [os-js/OS.js#98]
@khoaakt initiated this.

I've done some reasearch and am currently writing an early prototype of the OS.js API.

**I think this is broken as of late. Maybe they changed some rules and now will always have to be loaded by proxy ?!**

- [x] Firefox Marketplace API Helper
  - [x] Listing of Marketplace
  - [x] Searching
  - [x] Launching
  - [ ] Support for installable apps (not only hosted ones)
- [x] https is not supported apparently (for the most part) **added warning**
- [x] Custom Window type for FF Apps
- [x] Would be nice to have #89 in place
- [x] Correctly resolve app path. Currently there is something wrong
- [ ] Some apps have restrictions `Refused to display 'foo' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.`
- [x] Keyboard input seems to be buggy (focus loss)
- [ ] Resize windows (scaling)

**Comment by andersevenrud** [comment]
It's now actually possible to launch an application by id. There are quite a few things that needs to be sourted out though.

```
OSjs.Helpers.FirefoxMarketplace.createInstance({}, function(err, inst) {
  inst.launch(452888);
});
```

**Comment by andersevenrud** [comment]
You can now run hosted packages (mostly games apparently) via the Settings application, which now has Firefox Marketplace integration.

A little screenshot:
![Screenshot](http://i.imgur.com/ca3E2Kf.jpg)

@khoaakt Starting to take shape now :)

**Comment by khoaakt** [comment]
:/ You're so fast, code in just 1 day :P. I think you should make an app store that display images of the software

**Comment by khoaakt** [comment]
oh...I forgot it :/, did you have any api, ide,... etc to supporting programming OS.js platform

**Comment by andersevenrud** [comment]
@khoaakt When you got the right tools and documentation available, things go really fast! :)

Yes, I will create a dedicated application that displays it in a nice way. Right now this is just a temporary solution, like you described.

There is no need for a custom IDE since OS.js runs purely on javascript (it's better to let developers use their own tools), I started working with an application designer (you can see pictures of it on the Facebook page).

There is however, quite an extensive API for developers to use :)

- API Documentation: http://andersevenrud.github.io/OS.js-v2/doc/client/
- Tutorials: http://andersevenrud.github.io/OS.js-v2/doc/tutorials/
- Manuals: http://andersevenrud.github.io/OS.js-v2/doc/manuals/

**Comment by andersevenrud** [comment]
Added standalone *Firefox Marketplace* application with preview.

Screenshot:
![screenshot](http://i.imgur.com/Ael8EYb.png)

@khoaakt ;)

**Comment by khoaakt** [comment]
congratulations, your os.js finally had a app store(or not 😆). Good job!

**Comment by andersevenrud** [comment]
Actually, OS.js recently got an App Store too (in Settings application), but is in very early development (see: #99). I will have too look at that too :P

But this is really nice too.

Thanks! :smile:

**Comment by andersevenrud** [comment]
@khoaakt Actually, OS.js recently got an App Store too (in Settings application), but is in very early development (see: #99). I will have too look at that too :P

But this is really nice too.

Thanks! :smile:

**Comment by EGhiorzi** [comment]
I was just passing by, so I don't know much about this project. Though, as far as I know, Firefox Marketplace is being discontinued (following some timescale I don't remember well). There should be some official Mozilla communication somewhere. Were you aware of that?

**Comment by andersevenrud** [comment]
@EGhiorzi https://wiki.mozilla.org/Marketplace/FutureofMarketplaceFAQ

> As of March 29, 2016, the Firefox Marketplace will no longer support Android, Desktop, Tablets, or payments of any kind (paid apps or in-app payments). Payments are being deactivated, and the Web Runtime is being removed in Firefox 47 for Android and Firefox 48 for Windows, Mac OS X, and Linux.

Was it this ?

**Comment by EGhiorzi** [comment]
@andersevenrud yes that's it!

**Comment by andersevenrud** [comment]
@EGhiorzi Looks like I can close this issue then :) I had no idea actually.... or it might have slipped my mind entirely!
